	.set noreorder

#include "pspimport.s"

#ifdef F_sceKermitMsfs_driver_0000
	IMPORT_START "sceKermitMsfs_driver",0x00010000
#endif
#ifdef F_sceKermitMsfs_driver_0001
	IMPORT_FUNC	"sceKermitMsfs_driver",0x1A4DC9B7,sceKermitMsfs_driver_1A4DC9B7
#endif
#ifdef F_sceKermitMsfs_driver_0002
	IMPORT_FUNC	"sceKermitMsfs_driver",0x7668D90C,sceKermitMsfs_driver_7668D90C
#endif
#ifdef F_sceKermitMsfs_driver_0003
	IMPORT_FUNC	"sceKermitMsfs_driver",0x93B61A29,sceKermitMsfs_driver_93B61A29
#endif
#ifdef F_sceKermitMsfs_driver_0004
	IMPORT_FUNC	"sceKermitMsfs_driver",0xBE954163,sceKermitMsfs_driver_BE954163
#endif
#ifdef F_sceKermitMsfs_driver_0005
	IMPORT_FUNC	"sceKermitMsfs_driver",0xC1B4213A,sceKermitMsfs_driver_C1B4213A
#endif
#ifdef F_sceKermitMsfs_driver_0006
	IMPORT_FUNC	"sceKermitMsfs_driver",0xEAD1D2C6,sceKermitMsfs_driver_EAD1D2C6
#endif
