	.set noreorder

#include "pspimport.s"

#ifdef F_scePaf_0000
	IMPORT_START	"scePaf",0x00010000
#endif
#ifdef F_scePaf_0001
	IMPORT_FUNC	"scePaf",0xC9831AFF,scePaf_C9831AFF
#endif
#ifdef F_scePaf_0002
	IMPORT_FUNC	"scePaf",0xBFE9E90B,scePaf_BFE9E90B
#endif
#ifdef F_scePaf_0003
	IMPORT_FUNC	"scePaf",0x5FAC9869,scePaf_5FAC9869
#endif
#ifdef F_scePaf_0004
	IMPORT_FUNC	"scePaf",0xFCB4E053,scePaf_FCB4E053
#endif
#ifdef F_scePaf_0005
	IMPORT_FUNC	"scePaf",0x26DE971C,scePaf_26DE971C
#endif
#ifdef F_scePaf_0006
	IMPORT_FUNC	"scePaf",0x613E9AA2,scePaf_613E9AA2
#endif
#ifdef F_scePaf_0007
	IMPORT_FUNC	"scePaf",0x40C95283,scePaf_40C95283
#endif
#ifdef F_scePaf_0008
	IMPORT_FUNC	"scePaf",0xB61E88F2,scePaf_B61E88F2
#endif
#ifdef F_scePaf_0009
	IMPORT_FUNC	"scePaf",0x545FE2DA,scePaf_545FE2DA
#endif
#ifdef F_scePaf_0010
	IMPORT_FUNC	"scePaf",0x7EC15225,scePaf_7EC15225
#endif
#ifdef F_scePaf_0011
	IMPORT_FUNC	"scePaf",0x60DECA7E,scePaf_60DECA7E
#endif
#ifdef F_scePaf_0012
	IMPORT_FUNC	"scePaf",0xFD4C9F47,scePaf_FD4C9F47
#endif
#ifdef F_scePaf_0013
	IMPORT_FUNC	"scePaf",0xF95EA3F1,scePaf_F95EA3F1
#endif
#ifdef F_scePaf_0014
	IMPORT_FUNC	"scePaf",0x6829D7AF,scePaf_6829D7AF
#endif
#ifdef F_scePaf_0015
	IMPORT_FUNC	"scePaf",0xCA79D58B,scePaf_CA79D58B
#endif
#ifdef F_scePaf_0016
	IMPORT_FUNC	"scePaf",0x66FE90D7,scePaf_66FE90D7
#endif
#ifdef F_scePaf_0017
	IMPORT_FUNC	"scePaf",0x980228BA,scePaf_980228BA
#endif
#ifdef F_scePaf_0018
	IMPORT_FUNC	"scePaf",0x296897BC,scePaf_296897BC
#endif
#ifdef F_scePaf_0019
	IMPORT_FUNC	"scePaf",0xDEDF238F,scePaf_DEDF238F
#endif
#ifdef F_scePaf_0020
	IMPORT_FUNC	"scePaf",0x7BED034E,scePaf_7BED034E
#endif
#ifdef F_scePaf_0021
	IMPORT_FUNC	"scePaf",0xB3D58D25,scePaf_B3D58D25
#endif
#ifdef F_scePaf_0022
	IMPORT_FUNC	"scePaf",0x44AAF96C,scePaf_44AAF96C
#endif
#ifdef F_scePaf_0023
	IMPORT_FUNC	"scePaf",0x49A81B18,scePaf_49A81B18
#endif
#ifdef F_scePaf_0024
	IMPORT_FUNC	"scePaf",0xFF2F98C6,scePaf_FF2F98C6
#endif
#ifdef F_scePaf_0025
	IMPORT_FUNC	"scePaf",0x77D981F5,scePaf_77D981F5
#endif
#ifdef F_scePaf_0026
	IMPORT_FUNC	"scePaf",0x45D851D1,scePaf_45D851D1
#endif
#ifdef F_scePaf_0027
	IMPORT_FUNC	"scePaf",0x71712601,scePaf_71712601
#endif
#ifdef F_scePaf_0028
	IMPORT_FUNC	"scePaf",0x71460F7C,scePaf_71460F7C
#endif
#ifdef F_scePaf_0029
	IMPORT_FUNC	"scePaf",0xABBBB335,scePaf_ABBBB335
#endif
#ifdef F_scePaf_0030
	IMPORT_FUNC	"scePaf",0x07A5F495,scePaf_07A5F495
#endif
#ifdef F_scePaf_0031
	IMPORT_FUNC	"scePaf",0xF1552447,scePaf_F1552447
#endif
#ifdef F_scePaf_0032
	IMPORT_FUNC	"scePaf",0x83944053,scePaf_83944053
#endif
#ifdef F_scePaf_0033
	IMPORT_FUNC	"scePaf",0x2FDC80B3,scePaf_2FDC80B3
#endif
#ifdef F_scePaf_0034
	IMPORT_FUNC	"scePaf",0x993E9FDC,scePaf_993E9FDC
#endif
#ifdef F_scePaf_0035
	IMPORT_FUNC	"scePaf",0x3188E7DB,scePaf_3188E7DB
#endif
#ifdef F_scePaf_0036
	IMPORT_FUNC	"scePaf",0xDC38941B,scePaf_DC38941B
#endif
#ifdef F_scePaf_0037
	IMPORT_FUNC	"scePaf",0xF0B4CAE7,scePaf_F0B4CAE7
#endif
#ifdef F_scePaf_0038
	IMPORT_FUNC	"scePaf",0x6C234A6A,scePaf_6C234A6A
#endif
#ifdef F_scePaf_0039
	IMPORT_FUNC	"scePaf",0x37A98AE9,scePaf_37A98AE9
#endif
#ifdef F_scePaf_0040
	IMPORT_FUNC	"scePaf",0x3DD2A27B,scePaf_3DD2A27B
#endif
#ifdef F_scePaf_0041
	IMPORT_FUNC	"scePaf",0x9870A25B,scePaf_9870A25B
#endif
#ifdef F_scePaf_0042
	IMPORT_FUNC	"scePaf",0x503BA324,scePaf_503BA324
#endif
#ifdef F_scePaf_0043
	IMPORT_FUNC	"scePaf",0x2FA84441,scePaf_2FA84441
#endif
#ifdef F_scePaf_0044
	IMPORT_FUNC	"scePaf",0x84BD418F,scePaf_84BD418F
#endif
#ifdef F_scePaf_0045
	IMPORT_FUNC	"scePaf",0x902515FB,scePaf_902515FB
#endif
#ifdef F_scePaf_0046
	IMPORT_FUNC	"scePaf",0x3586BE05,scePaf_3586BE05
#endif
#ifdef F_scePaf_0047
	IMPORT_FUNC	"scePaf",0x2FA0EDDC,scePaf_2FA0EDDC
#endif
#ifdef F_scePaf_0048
	IMPORT_FUNC	"scePaf",0x3FBD9639,scePaf_3FBD9639
#endif
#ifdef F_scePaf_0049
	IMPORT_FUNC	"scePaf",0x6BA9C299,scePaf_6BA9C299
#endif
#ifdef F_scePaf_0050
	IMPORT_FUNC	"scePaf",0xF1B52E86,scePaf_F1B52E86
#endif
#ifdef F_scePaf_0051
	IMPORT_FUNC	"scePaf",0x10B901E7,scePaf_10B901E7
#endif
#ifdef F_scePaf_0052
	IMPORT_FUNC	"scePaf",0x4370175A,scePaf_4370175A
#endif
#ifdef F_scePaf_0053
	IMPORT_FUNC	"scePaf",0x809A4F83,scePaf_809A4F83
#endif
#ifdef F_scePaf_0054
	IMPORT_FUNC	"scePaf",0xA82E3C19,scePaf_A82E3C19
#endif
#ifdef F_scePaf_0055
	IMPORT_FUNC	"scePaf",0xED2B47FA,scePaf_ED2B47FA
#endif
#ifdef F_scePaf_0056
	IMPORT_FUNC	"scePaf",0x26168DD3,scePaf_26168DD3
#endif
#ifdef F_scePaf_0057
	IMPORT_FUNC	"scePaf",0x626D68A1,scePaf_626D68A1
#endif
#ifdef F_scePaf_0058
	IMPORT_FUNC	"scePaf",0xFBA47E77,scePaf_FBA47E77
#endif
#ifdef F_scePaf_0059
	IMPORT_FUNC	"scePaf",0x44A0BCE4,scePaf_44A0BCE4
#endif
#ifdef F_scePaf_0060
	IMPORT_FUNC	"scePaf",0x4B1A374C,scePaf_4B1A374C
#endif
#ifdef F_scePaf_0061
	IMPORT_FUNC	"scePaf",0x1D5D9A68,scePaf_1D5D9A68
#endif
#ifdef F_scePaf_0062
	IMPORT_FUNC	"scePaf",0x51AAAAF4,scePaf_51AAAAF4
#endif
#ifdef F_scePaf_0063
	IMPORT_FUNC	"scePaf",0x54C0DD23,scePaf_54C0DD23
#endif
#ifdef F_scePaf_0064
	IMPORT_FUNC	"scePaf",0x9F10613F,scePaf_9F10613F
#endif
#ifdef F_scePaf_0065
	IMPORT_FUNC	"scePaf",0x8F12B63A,scePaf_8F12B63A
#endif
#ifdef F_scePaf_0066
	IMPORT_FUNC	"scePaf",0x9D0192FD,scePaf_9D0192FD
#endif
#ifdef F_scePaf_0067
	IMPORT_FUNC	"scePaf",0xFEAFC77A,scePaf_FEAFC77A
#endif
#ifdef F_scePaf_0068
	IMPORT_FUNC	"scePaf",0x99A5CD38,scePaf_99A5CD38
#endif
#ifdef F_scePaf_0069
	IMPORT_FUNC	"scePaf",0xCE699963,scePaf_CE699963
#endif
#ifdef F_scePaf_0070
	IMPORT_FUNC	"scePaf",0xCB2198AB,scePaf_CB2198AB
#endif
#ifdef F_scePaf_0071
	IMPORT_FUNC	"scePaf",0x11EF5210,scePaf_11EF5210
#endif
#ifdef F_scePaf_0072
	IMPORT_FUNC	"scePaf",0xB7E6052B,scePaf_B7E6052B
#endif
#ifdef F_scePaf_0073
	IMPORT_FUNC	"scePaf",0xF13EBB78,scePaf_F13EBB78
#endif
#ifdef F_scePaf_0074
	IMPORT_FUNC	"scePaf",0x4E67BB08,scePaf_4E67BB08
#endif
#ifdef F_scePaf_0075
	IMPORT_FUNC	"scePaf",0xB3D2C3BB,scePaf_B3D2C3BB
#endif
#ifdef F_scePaf_0076
	IMPORT_FUNC	"scePaf",0x962FA087,scePaf_962FA087
#endif
#ifdef F_scePaf_0077
	IMPORT_FUNC	"scePaf",0xD4C6CC7A,scePaf_D4C6CC7A
#endif
#ifdef F_scePaf_0078
	IMPORT_FUNC	"scePaf",0x927854C5,scePaf_927854C5
#endif
#ifdef F_scePaf_0079
	IMPORT_FUNC	"scePaf",0xD02C0D2E,scePaf_D02C0D2E
#endif
#ifdef F_scePaf_0080
	IMPORT_FUNC	"scePaf",0x2FF0A287,scePaf_2FF0A287
#endif
#ifdef F_scePaf_0081
	IMPORT_FUNC	"scePaf",0xF47CA1C2,scePaf_F47CA1C2
#endif
#ifdef F_scePaf_0082
	IMPORT_FUNC	"scePaf",0xEAA5AFF6,scePaf_EAA5AFF6
#endif
#ifdef F_scePaf_0083
	IMPORT_FUNC	"scePaf",0x58BFC2AC,scePaf_58BFC2AC
#endif
#ifdef F_scePaf_0084
	IMPORT_FUNC	"scePaf",0x72514A05,scePaf_72514A05
#endif
#ifdef F_scePaf_0085
	IMPORT_FUNC	"scePaf",0xA69BABE3,scePaf_A69BABE3
#endif
#ifdef F_scePaf_0086
	IMPORT_FUNC	"scePaf",0x9430557B,scePaf_9430557B
#endif
#ifdef F_scePaf_0087
	IMPORT_FUNC	"scePaf",0x607713A6,scePaf_607713A6
#endif
#ifdef F_scePaf_0088
	IMPORT_FUNC	"scePaf",0x5EFC5387,scePaf_5EFC5387
#endif
#ifdef F_scePaf_0089
	IMPORT_FUNC	"scePaf",0x79C3CBF7,scePaf_79C3CBF7
#endif
#ifdef F_scePaf_0090
	IMPORT_FUNC	"scePaf",0x3A4934E3,scePaf_3A4934E3
#endif
#ifdef F_scePaf_0091
	IMPORT_FUNC	"scePaf",0x4FF65BDC,scePaf_4FF65BDC
#endif
#ifdef F_scePaf_0092
	IMPORT_FUNC	"scePaf",0x26DF747F,scePaf_26DF747F
#endif
#ifdef F_scePaf_0093
	IMPORT_FUNC	"scePaf",0x41BCFB59,scePaf_41BCFB59
#endif
#ifdef F_scePaf_0094
	IMPORT_FUNC	"scePaf",0xFA05BF7B,scePaf_FA05BF7B
#endif
#ifdef F_scePaf_0095
	IMPORT_FUNC	"scePaf",0xAAA8D3DA,scePaf_AAA8D3DA
#endif
#ifdef F_scePaf_0096
	IMPORT_FUNC	"scePaf",0xA18DB948,scePaf_A18DB948
#endif
#ifdef F_scePaf_0097
	IMPORT_FUNC	"scePaf",0x2313DDCA,scePaf_2313DDCA
#endif
#ifdef F_scePaf_0098
	IMPORT_FUNC	"scePaf",0x4FC2470C,scePaf_4FC2470C
#endif
#ifdef F_scePaf_0099
	IMPORT_FUNC	"scePaf",0xB77039E4,scePaf_B77039E4
#endif
#ifdef F_scePaf_0100
	IMPORT_FUNC	"scePaf",0x0C6EEA21,scePaf_0C6EEA21
#endif
#ifdef F_scePaf_0101
	IMPORT_FUNC	"scePaf",0xCB7B666E,scePaf_CB7B666E
#endif
#ifdef F_scePaf_0102
	IMPORT_FUNC	"scePaf",0x7B6F0E32,scePaf_7B6F0E32
#endif
#ifdef F_scePaf_0103
	IMPORT_FUNC	"scePaf",0x256218C2,scePaf_256218C2
#endif
#ifdef F_scePaf_0104
	IMPORT_FUNC	"scePaf",0x96C46364,scePaf_96C46364
#endif
#ifdef F_scePaf_0105
	IMPORT_FUNC	"scePaf",0x7C31F453,scePaf_7C31F453
#endif
#ifdef F_scePaf_0106
	IMPORT_FUNC	"scePaf",0x503FA456,scePaf_503FA456
#endif
#ifdef F_scePaf_0107
	IMPORT_FUNC	"scePaf",0xD5F5E68F,scePaf_D5F5E68F
#endif
#ifdef F_scePaf_0108
	IMPORT_FUNC	"scePaf",0xCAE6374A,scePaf_CAE6374A
#endif
#ifdef F_scePaf_0109
	IMPORT_FUNC	"scePaf",0x84A71447,scePaf_84A71447
#endif
#ifdef F_scePaf_0110
	IMPORT_FUNC	"scePaf",0xD2463C79,scePaf_D2463C79
#endif
#ifdef F_scePaf_0111
	IMPORT_FUNC	"scePaf",0xED3E4EB1,scePaf_ED3E4EB1
#endif
#ifdef F_scePaf_0112
	IMPORT_FUNC	"scePaf",0x8DB4B066,scePaf_8DB4B066
#endif
#ifdef F_scePaf_0113
	IMPORT_FUNC	"scePaf",0xB104EC1B,scePaf_B104EC1B
#endif
#ifdef F_scePaf_0114
	IMPORT_FUNC	"scePaf",0xB3659499,scePaf_B3659499
#endif
#ifdef F_scePaf_0115
	IMPORT_FUNC	"scePaf",0x6E94BA7B,scePaf_6E94BA7B
#endif
#ifdef F_scePaf_0116
	IMPORT_FUNC	"scePaf",0xFF74C932,scePaf_FF74C932
#endif
#ifdef F_scePaf_0117
	IMPORT_FUNC	"scePaf",0xF6F3E99E,scePaf_F6F3E99E
#endif
#ifdef F_scePaf_0118
	IMPORT_FUNC	"scePaf",0xA72594EF,scePaf_A72594EF
#endif
#ifdef F_scePaf_0119
	IMPORT_FUNC	"scePaf",0x5075C799,scePaf_5075C799
#endif
#ifdef F_scePaf_0120
	IMPORT_FUNC	"scePaf",0xA76B9604,scePaf_A76B9604
#endif
#ifdef F_scePaf_0121
	IMPORT_FUNC	"scePaf",0xE1C76B22,scePaf_E1C76B22
#endif
#ifdef F_scePaf_0122
	IMPORT_FUNC	"scePaf",0x44EB8C62,scePaf_44EB8C62
#endif
#ifdef F_scePaf_0123
	IMPORT_FUNC	"scePaf",0xC2C25056,scePaf_C2C25056
#endif
#ifdef F_scePaf_0124
	IMPORT_FUNC	"scePaf",0xAEEF2A7C,scePaf_AEEF2A7C
#endif
#ifdef F_scePaf_0125
	IMPORT_FUNC	"scePaf",0x55CC4749,scePaf_55CC4749
#endif
#ifdef F_scePaf_0126
	IMPORT_FUNC	"scePaf",0x37DD37B8,scePaf_37DD37B8
#endif
#ifdef F_scePaf_0127
	IMPORT_FUNC	"scePaf",0x16033F84,scePaf_16033F84
#endif
#ifdef F_scePaf_0128
	IMPORT_FUNC	"scePaf",0xA0A25707,scePaf_A0A25707
#endif
#ifdef F_scePaf_0129
	IMPORT_FUNC	"scePaf",0xF6AB6655,scePaf_F6AB6655
#endif
#ifdef F_scePaf_0130
	IMPORT_FUNC	"scePaf",0xC6CF9352,scePaf_C6CF9352
#endif
#ifdef F_scePaf_0131
	IMPORT_FUNC	"scePaf",0x0A189A1A,scePaf_0A189A1A
#endif
#ifdef F_scePaf_0132
	IMPORT_FUNC	"scePaf",0xCB7CCB28,scePaf_CB7CCB28
#endif
#ifdef F_scePaf_0133
	IMPORT_FUNC	"scePaf",0x7B099943,scePaf_7B099943
#endif
#ifdef F_scePaf_0134
	IMPORT_FUNC	"scePaf",0xE9BF6BEB,scePaf_E9BF6BEB
#endif
#ifdef F_scePaf_0135
	IMPORT_FUNC	"scePaf",0xCEAC29F3,scePaf_CEAC29F3
#endif
#ifdef F_scePaf_0136
	IMPORT_FUNC	"scePaf",0x275BCDC6,scePaf_275BCDC6
#endif
#ifdef F_scePaf_0137
	IMPORT_FUNC	"scePaf",0x65C19AC0,scePaf_65C19AC0
#endif
#ifdef F_scePaf_0138
	IMPORT_FUNC	"scePaf",0x8BA04801,scePaf_8BA04801
#endif
#ifdef F_scePaf_0139
	IMPORT_FUNC	"scePaf",0x93A60B78,scePaf_93A60B78
#endif
#ifdef F_scePaf_0140
	IMPORT_FUNC	"scePaf",0xAEE1CBAD,scePaf_AEE1CBAD
#endif
#ifdef F_scePaf_0141
	IMPORT_FUNC	"scePaf",0x19A779E2,scePaf_19A779E2
#endif
#ifdef F_scePaf_0142
	IMPORT_FUNC	"scePaf",0xCDC81771,scePaf_CDC81771
#endif
#ifdef F_scePaf_0143
	IMPORT_FUNC	"scePaf",0xC1FAF826,scePaf_C1FAF826
#endif
#ifdef F_scePaf_0144
	IMPORT_FUNC	"scePaf",0x9C9B6732,scePaf_9C9B6732
#endif
#ifdef F_scePaf_0145
	IMPORT_FUNC	"scePaf",0x78054045,scePaf_78054045
#endif
#ifdef F_scePaf_0146
	IMPORT_FUNC	"scePaf",0xDF9138A8,scePaf_DF9138A8
#endif
#ifdef F_scePaf_0147
	IMPORT_FUNC	"scePaf",0xF7FB133E,scePaf_F7FB133E
#endif
#ifdef F_scePaf_0148
	IMPORT_FUNC	"scePaf",0xCFF2B69C,scePaf_CFF2B69C
#endif
#ifdef F_scePaf_0149
	IMPORT_FUNC	"scePaf",0xEF52945B,scePaf_EF52945B
#endif
#ifdef F_scePaf_0150
	IMPORT_FUNC	"scePaf",0xBAA88CDA,scePaf_BAA88CDA
#endif
#ifdef F_scePaf_0151
	IMPORT_FUNC	"scePaf",0xBDC894D8,scePaf_BDC894D8
#endif
#ifdef F_scePaf_0152
	IMPORT_FUNC	"scePaf",0x5045C01F,scePaf_5045C01F
#endif
#ifdef F_scePaf_0153
	IMPORT_FUNC	"scePaf",0xA89157EE,scePaf_A89157EE
#endif
#ifdef F_scePaf_0154
	IMPORT_FUNC	"scePaf",0x1F0B8678,scePaf_1F0B8678
#endif
#ifdef F_scePaf_0155
	IMPORT_FUNC	"scePaf",0x33096E46,scePaf_33096E46
#endif
#ifdef F_scePaf_0156
	IMPORT_FUNC	"scePaf",0x47E35A50,scePaf_47E35A50
#endif
#ifdef F_scePaf_0157
	IMPORT_FUNC	"scePaf",0x25391E36,scePaf_25391E36
#endif
#ifdef F_scePaf_0158
	IMPORT_FUNC	"scePaf",0x50FFFCD2,scePaf_50FFFCD2
#endif
#ifdef F_scePaf_0159
	IMPORT_FUNC	"scePaf",0x206C1F70,scePaf_206C1F70
#endif
#ifdef F_scePaf_0160
	IMPORT_FUNC	"scePaf",0x0C66B594,scePaf_0C66B594
#endif
#ifdef F_scePaf_0161
	IMPORT_FUNC	"scePaf",0x39F89900,scePaf_39F89900
#endif
#ifdef F_scePaf_0162
	IMPORT_FUNC	"scePaf",0xB6841F37,scePaf_B6841F37
#endif
#ifdef F_scePaf_0163
	IMPORT_FUNC	"scePaf",0x360956CC,scePaf_360956CC
#endif
#ifdef F_scePaf_0164
	IMPORT_FUNC	"scePaf",0x0AEDCDA1,scePaf_0AEDCDA1
#endif
#ifdef F_scePaf_0165
	IMPORT_FUNC	"scePaf",0x222526B6,scePaf_222526B6
#endif
#ifdef F_scePaf_0166
	IMPORT_FUNC	"scePaf",0x41A7BDD2,scePaf_41A7BDD2
#endif
#ifdef F_scePaf_0167
	IMPORT_FUNC	"scePaf",0xD07AF3FA,scePaf_D07AF3FA
#endif
#ifdef F_scePaf_0168
	IMPORT_FUNC	"scePaf",0x29DC646F,scePaf_29DC646F
#endif
#ifdef F_scePaf_0169
	IMPORT_FUNC	"scePaf",0x2A6499A5,scePaf_2A6499A5
#endif
#ifdef F_scePaf_0170
	IMPORT_FUNC	"scePaf",0x4FCA0DE9,scePaf_4FCA0DE9
#endif
#ifdef F_scePaf_0171
	IMPORT_FUNC	"scePaf",0xE796C85B,scePaf_E796C85B
#endif
#ifdef F_scePaf_0172
	IMPORT_FUNC	"scePaf",0xBAFF6806,scePaf_BAFF6806
#endif
#ifdef F_scePaf_0173
	IMPORT_FUNC	"scePaf",0xAA978F61,scePaf_AA978F61
#endif
#ifdef F_scePaf_0174
	IMPORT_FUNC	"scePaf",0xFCF42D6D,scePaf_FCF42D6D
#endif
#ifdef F_scePaf_0175
	IMPORT_FUNC	"scePaf",0x5DB527D4,scePaf_5DB527D4
#endif
#ifdef F_scePaf_0176
	IMPORT_FUNC	"scePaf",0x2E6CA751,scePaf_2E6CA751
#endif
#ifdef F_scePaf_0177
	IMPORT_FUNC	"scePaf",0x3F52824F,scePaf_3F52824F
#endif
#ifdef F_scePaf_0178
	IMPORT_FUNC	"scePaf",0x1C286704,scePaf_1C286704
#endif
#ifdef F_scePaf_0179
	IMPORT_FUNC	"scePaf",0x672036FE,scePaf_672036FE
#endif
#ifdef F_scePaf_0180
	IMPORT_FUNC	"scePaf",0x08A02EFF,scePaf_08A02EFF
#endif
#ifdef F_scePaf_0181
	IMPORT_FUNC	"scePaf",0x01A35C15,scePaf_01A35C15
#endif
#ifdef F_scePaf_0182
	IMPORT_FUNC	"scePaf",0x470ABD60,scePaf_470ABD60
#endif
#ifdef F_scePaf_0183
	IMPORT_FUNC	"scePaf",0xB42D784E,scePaf_B42D784E
#endif
#ifdef F_scePaf_0184
	IMPORT_FUNC	"scePaf",0x84485F54,scePaf_84485F54
#endif
#ifdef F_scePaf_0185
	IMPORT_FUNC	"scePaf",0x87516C3B,scePaf_87516C3B
#endif
#ifdef F_scePaf_0186
	IMPORT_FUNC	"scePaf",0x715E8DAB,scePaf_715E8DAB
#endif
#ifdef F_scePaf_0187
	IMPORT_FUNC	"scePaf",0xD35B454A,scePaf_D35B454A
#endif
#ifdef F_scePaf_0188
	IMPORT_FUNC	"scePaf",0xCFB1A402,scePaf_CFB1A402
#endif
#ifdef F_scePaf_0189
	IMPORT_FUNC	"scePaf",0x5D7F1F27,scePaf_5D7F1F27
#endif
#ifdef F_scePaf_0190
	IMPORT_FUNC	"scePaf",0x3291BDDD,scePaf_3291BDDD
#endif
#ifdef F_scePaf_0191
	IMPORT_FUNC	"scePaf",0x515EE222,scePaf_515EE222
#endif
#ifdef F_scePaf_0192
	IMPORT_FUNC	"scePaf",0x3987B5C4,scePaf_3987B5C4
#endif
#ifdef F_scePaf_0193
	IMPORT_FUNC	"scePaf",0xF89ECA28,scePaf_F89ECA28
#endif
#ifdef F_scePaf_0194
	IMPORT_FUNC	"scePaf",0x4AF8E417,scePaf_4AF8E417
#endif
#ifdef F_scePaf_0195
	IMPORT_FUNC	"scePaf",0x76D5A950,scePaf_76D5A950
#endif
#ifdef F_scePaf_0196
	IMPORT_FUNC	"scePaf",0xF577BC82,scePaf_F577BC82
#endif
#ifdef F_scePaf_0197
	IMPORT_FUNC	"scePaf",0x369E597A,scePaf_369E597A
#endif
#ifdef F_scePaf_0198
	IMPORT_FUNC	"scePaf",0x293A01D8,scePaf_293A01D8
#endif
#ifdef F_scePaf_0199
	IMPORT_FUNC	"scePaf",0x45386654,scePaf_45386654
#endif
#ifdef F_scePaf_0200
	IMPORT_FUNC	"scePaf",0x73D49419,scePaf_73D49419
#endif
#ifdef F_scePaf_0201
	IMPORT_FUNC	"scePaf",0xAD007AB6,scePaf_AD007AB6
#endif
#ifdef F_scePaf_0202
	IMPORT_FUNC	"scePaf",0xF49F3C59,scePaf_F49F3C59
#endif
#ifdef F_scePaf_0203
	IMPORT_FUNC	"scePaf",0x05EEE8A6,scePaf_05EEE8A6
#endif
#ifdef F_scePaf_0204
	IMPORT_FUNC	"scePaf",0x15EF8E18,scePaf_15EF8E18
#endif
#ifdef F_scePaf_0205
	IMPORT_FUNC	"scePaf",0xFE84212F,scePaf_FE84212F
#endif
#ifdef F_scePaf_0206
	IMPORT_FUNC	"scePaf",0x9D92765E,scePaf_9D92765E
#endif
#ifdef F_scePaf_0207
	IMPORT_FUNC	"scePaf",0x98A6C193,scePaf_98A6C193
#endif
#ifdef F_scePaf_0208
	IMPORT_FUNC	"scePaf",0x1943B875,scePaf_1943B875
#endif
#ifdef F_scePaf_0209
	IMPORT_FUNC	"scePaf",0xD7074BD1,scePaf_D7074BD1
#endif
#ifdef F_scePaf_0210
	IMPORT_FUNC	"scePaf",0xBD49CAEF,scePaf_BD49CAEF
#endif
#ifdef F_scePaf_0211
	IMPORT_FUNC	"scePaf",0x6C4976AF,scePaf_6C4976AF
#endif
#ifdef F_scePaf_0212
	IMPORT_FUNC	"scePaf",0x85112756,scePaf_85112756
#endif
#ifdef F_scePaf_0213
	IMPORT_FUNC	"scePaf",0xFDB39519,scePaf_FDB39519
#endif
#ifdef F_scePaf_0214
	IMPORT_FUNC	"scePaf",0xDA3A6D88,scePaf_DA3A6D88
#endif
#ifdef F_scePaf_0215
	IMPORT_FUNC	"scePaf",0x199896A3,scePaf_199896A3
#endif
#ifdef F_scePaf_0216
	IMPORT_FUNC	"scePaf",0x5458E412,scePaf_5458E412
#endif
#ifdef F_scePaf_0217
	IMPORT_FUNC	"scePaf",0x43374E9E,scePaf_43374E9E
#endif
#ifdef F_scePaf_0218
	IMPORT_FUNC	"scePaf",0x6797988C,scePaf_6797988C
#endif
#ifdef F_scePaf_0219
	IMPORT_FUNC	"scePaf",0x449C8821,scePaf_449C8821
#endif
#ifdef F_scePaf_0220
	IMPORT_FUNC	"scePaf",0x6C386158,scePaf_6C386158
#endif
#ifdef F_scePaf_0221
	IMPORT_FUNC	"scePaf",0x8E751FCC,scePaf_8E751FCC
#endif
#ifdef F_scePaf_0222
	IMPORT_FUNC	"scePaf",0xF32223AC,scePaf_F32223AC
#endif
#ifdef F_scePaf_0223
	IMPORT_FUNC	"scePaf",0x40B21F4F,scePaf_40B21F4F
#endif
#ifdef F_scePaf_0224
	IMPORT_FUNC	"scePaf",0x501E9BC9,scePaf_501E9BC9
#endif
#ifdef F_scePaf_0225
	IMPORT_FUNC	"scePaf",0x4E60E34C,scePaf_4E60E34C
#endif
#ifdef F_scePaf_0226
	IMPORT_FUNC	"scePaf",0x39C55C03,scePaf_39C55C03
#endif
#ifdef F_scePaf_0227
	IMPORT_FUNC	"scePaf",0x65920294,scePaf_65920294
#endif
#ifdef F_scePaf_0228
	IMPORT_FUNC	"scePaf",0x37DDBDD8,scePaf_37DDBDD8
#endif
#ifdef F_scePaf_0229
	IMPORT_FUNC	"scePaf",0x92A46B32,scePaf_92A46B32
#endif
#ifdef F_scePaf_0230
	IMPORT_FUNC	"scePaf",0x905347E9,scePaf_905347E9
#endif
#ifdef F_scePaf_0231
	IMPORT_FUNC	"scePaf",0xDF887DED,scePaf_DF887DED
#endif
#ifdef F_scePaf_0232
	IMPORT_FUNC	"scePaf",0xDC544921,scePaf_DC544921
#endif
#ifdef F_scePaf_0233
	IMPORT_FUNC	"scePaf",0x585B93BC,scePaf_585B93BC
#endif
#ifdef F_scePaf_0234
	IMPORT_FUNC	"scePaf",0x1AD33D73,scePaf_1AD33D73
#endif
#ifdef F_scePaf_0235
	IMPORT_FUNC	"scePaf",0xA4F53FED,scePaf_A4F53FED
#endif
#ifdef F_scePaf_0236
	IMPORT_FUNC	"scePaf",0x01CF521E,scePaf_01CF521E
#endif
#ifdef F_scePaf_0237
	IMPORT_FUNC	"scePaf",0x3C68DCB7,scePaf_3C68DCB7
#endif
#ifdef F_scePaf_0238
	IMPORT_FUNC	"scePaf",0x3F81333A,scePaf_3F81333A
#endif
#ifdef F_scePaf_0239
	IMPORT_FUNC	"scePaf",0x9A8E343E,scePaf_9A8E343E
#endif
#ifdef F_scePaf_0240
	IMPORT_FUNC	"scePaf",0x95040C08,scePaf_95040C08
#endif
#ifdef F_scePaf_0241
	IMPORT_FUNC	"scePaf",0x0CFDBE2F,scePaf_0CFDBE2F
#endif
#ifdef F_scePaf_0242
	IMPORT_FUNC	"scePaf",0x3829AC24,scePaf_3829AC24
#endif
#ifdef F_scePaf_0243
	IMPORT_FUNC	"scePaf",0x1F0E9712,scePaf_1F0E9712
#endif
#ifdef F_scePaf_0244
	IMPORT_FUNC	"scePaf",0xD24E4016,scePaf_D24E4016
#endif
#ifdef F_scePaf_0245
	IMPORT_FUNC	"scePaf",0x409E25A3,scePaf_409E25A3
#endif
#ifdef F_scePaf_0246
	IMPORT_FUNC	"scePaf",0xDC8B0309,scePaf_DC8B0309
#endif
#ifdef F_scePaf_0247
	IMPORT_FUNC	"scePaf",0xEB553D60,scePaf_EB553D60
#endif
#ifdef F_scePaf_0248
	IMPORT_FUNC	"scePaf",0x4EA868E6,scePaf_4EA868E6
#endif
#ifdef F_scePaf_0249
	IMPORT_FUNC	"scePaf",0x8AB03D91,scePaf_8AB03D91
#endif
#ifdef F_scePaf_0250
	IMPORT_FUNC	"scePaf",0x5CA7F421,scePaf_5CA7F421
#endif
#ifdef F_scePaf_0251
	IMPORT_FUNC	"scePaf",0xB7865607,scePaf_B7865607
#endif
#ifdef F_scePaf_0252
	IMPORT_FUNC	"scePaf",0x95948FB6,scePaf_95948FB6
#endif
#ifdef F_scePaf_0253
	IMPORT_FUNC	"scePaf",0xBA433BEF,scePaf_BA433BEF
#endif
#ifdef F_scePaf_0254
	IMPORT_FUNC	"scePaf",0xED89C94B,scePaf_ED89C94B
#endif
#ifdef F_scePaf_0255
	IMPORT_FUNC	"scePaf",0x0E8A3B52,scePaf_0E8A3B52
#endif
#ifdef F_scePaf_0256
	IMPORT_FUNC	"scePaf",0xD587826C,scePaf_D587826C
#endif
#ifdef F_scePaf_0257
	IMPORT_FUNC	"scePaf",0x61B105C0,scePaf_61B105C0
#endif
#ifdef F_scePaf_0258
	IMPORT_FUNC	"scePaf",0xDAD477C1,scePaf_DAD477C1
#endif
#ifdef F_scePaf_0259
	IMPORT_FUNC	"scePaf",0xD91B2651,scePaf_D91B2651
#endif
#ifdef F_scePaf_0260
	IMPORT_FUNC	"scePaf",0xA02E66FA,scePaf_A02E66FA
#endif
#ifdef F_scePaf_0261
	IMPORT_FUNC	"scePaf",0x2D79697E,scePaf_2D79697E
#endif
#ifdef F_scePaf_0262
	IMPORT_FUNC	"scePaf",0xEDF1C662,scePaf_EDF1C662
#endif
#ifdef F_scePaf_0263
	IMPORT_FUNC	"scePaf",0xA7818BCE,scePaf_A7818BCE
#endif
#ifdef F_scePaf_0264
	IMPORT_FUNC	"scePaf",0x695BCD34,scePaf_695BCD34
#endif
#ifdef F_scePaf_0265
	IMPORT_FUNC	"scePaf",0xC4D819AA,scePaf_C4D819AA
#endif
#ifdef F_scePaf_0266
	IMPORT_FUNC	"scePaf",0x70B92642,scePaf_70B92642
#endif
#ifdef F_scePaf_0267
	IMPORT_FUNC	"scePaf",0x447974D1,scePaf_447974D1
#endif
#ifdef F_scePaf_0268
	IMPORT_FUNC	"scePaf",0x63EA1815,scePaf_63EA1815
#endif
#ifdef F_scePaf_0269
	IMPORT_FUNC	"scePaf",0xCB65103E,scePaf_CB65103E
#endif
#ifdef F_scePaf_0270
	IMPORT_FUNC	"scePaf",0x32B27ADD,scePaf_32B27ADD
#endif
#ifdef F_scePaf_0271
	IMPORT_FUNC	"scePaf",0xADC146F0,scePaf_ADC146F0
#endif
#ifdef F_scePaf_0272
	IMPORT_FUNC	"scePaf",0xD5A254F9,scePaf_D5A254F9
#endif
#ifdef F_scePaf_0273
	IMPORT_FUNC	"scePaf",0x42F43213,scePaf_42F43213
#endif
#ifdef F_scePaf_0274
	IMPORT_FUNC	"scePaf",0x5D242D11,scePaf_5D242D11
#endif
#ifdef F_scePaf_0275
	IMPORT_FUNC	"scePaf",0x11361F12,scePaf_11361F12
#endif
#ifdef F_scePaf_0276
	IMPORT_FUNC	"scePaf",0x51FF9D24,scePaf_51FF9D24
#endif
#ifdef F_scePaf_0277
	IMPORT_FUNC	"scePaf",0xB2ED6CAA,scePaf_B2ED6CAA
#endif
#ifdef F_scePaf_0278
	IMPORT_FUNC	"scePaf",0x79F4AE65,scePaf_79F4AE65
#endif
#ifdef F_scePaf_0279
	IMPORT_FUNC	"scePaf",0x905CF2A7,scePaf_905CF2A7
#endif
#ifdef F_scePaf_0280
	IMPORT_FUNC	"scePaf",0xE732CF74,scePaf_E732CF74
#endif
#ifdef F_scePaf_0281
	IMPORT_FUNC	"scePaf",0xB711DC69,scePaf_B711DC69
#endif
#ifdef F_scePaf_0282
	IMPORT_FUNC	"scePaf",0x0ED80B09,scePaf_0ED80B09
#endif
#ifdef F_scePaf_0283
	IMPORT_FUNC	"scePaf",0xBB457D6F,scePaf_BB457D6F
#endif
#ifdef F_scePaf_0284
	IMPORT_FUNC	"scePaf",0xB6F52424,scePaf_B6F52424
#endif
#ifdef F_scePaf_0285
	IMPORT_FUNC	"scePaf",0xBA6B8B02,scePaf_BA6B8B02
#endif
#ifdef F_scePaf_0286
	IMPORT_FUNC	"scePaf",0xB9BE69FD,scePaf_B9BE69FD
#endif
#ifdef F_scePaf_0287
	IMPORT_FUNC	"scePaf",0xFA758B05,scePaf_FA758B05
#endif
#ifdef F_scePaf_0288
	IMPORT_FUNC	"scePaf",0xFA87D725,scePaf_FA87D725
#endif
#ifdef F_scePaf_0289
	IMPORT_FUNC	"scePaf",0xFC37FABD,scePaf_FC37FABD
#endif
#ifdef F_scePaf_0290
	IMPORT_FUNC	"scePaf",0x64775957,scePaf_64775957
#endif
#ifdef F_scePaf_0291
	IMPORT_FUNC	"scePaf",0x7F2442DC,scePaf_7F2442DC
#endif
#ifdef F_scePaf_0292
	IMPORT_FUNC	"scePaf",0x86B41BA3,scePaf_86B41BA3
#endif
#ifdef F_scePaf_0293
	IMPORT_FUNC	"scePaf",0x541F36E9,scePaf_541F36E9
#endif
#ifdef F_scePaf_0294
	IMPORT_FUNC	"scePaf",0x86C87E62,scePaf_86C87E62
#endif
#ifdef F_scePaf_0295
	IMPORT_FUNC	"scePaf",0xF1546D14,scePaf_F1546D14
#endif
#ifdef F_scePaf_0296
	IMPORT_FUNC	"scePaf",0x6840D208,scePaf_6840D208
#endif
#ifdef F_scePaf_0297
	IMPORT_FUNC	"scePaf",0xD1EE972C,scePaf_D1EE972C
#endif
#ifdef F_scePaf_0298
	IMPORT_FUNC	"scePaf",0x1232B7A3,scePaf_1232B7A3
#endif
#ifdef F_scePaf_0299
	IMPORT_FUNC	"scePaf",0x8D7FC7DB,scePaf_8D7FC7DB
#endif
#ifdef F_scePaf_0300
	IMPORT_FUNC	"scePaf",0x5DE0445F,scePaf_5DE0445F
#endif
#ifdef F_scePaf_0301
	IMPORT_FUNC	"scePaf",0x09AC6844,scePaf_09AC6844
#endif
#ifdef F_scePaf_0302
	IMPORT_FUNC	"scePaf",0xD2E0D705,scePaf_D2E0D705
#endif
#ifdef F_scePaf_0303
	IMPORT_FUNC	"scePaf",0xAE02F241,scePaf_AE02F241
#endif
#ifdef F_scePaf_0304
	IMPORT_FUNC	"scePaf",0xD1159069,scePaf_D1159069
#endif
#ifdef F_scePaf_0305
	IMPORT_FUNC	"scePaf",0xBFFAEE83,scePaf_BFFAEE83
#endif
#ifdef F_scePaf_0306
	IMPORT_FUNC	"scePaf",0xDDA68BE8,scePaf_DDA68BE8
#endif
#ifdef F_scePaf_0307
	IMPORT_FUNC	"scePaf",0x9AFD4AD4,scePaf_9AFD4AD4
#endif
#ifdef F_scePaf_0308
	IMPORT_FUNC	"scePaf",0x6E1B5B50,scePaf_6E1B5B50
#endif
#ifdef F_scePaf_0309
	IMPORT_FUNC	"scePaf",0x8DEB3DB3,scePaf_8DEB3DB3
#endif
#ifdef F_scePaf_0310
	IMPORT_FUNC	"scePaf",0xBA09CF46,scePaf_BA09CF46
#endif
#ifdef F_scePaf_0311
	IMPORT_FUNC	"scePaf",0x6DD28F44,scePaf_6DD28F44
#endif
#ifdef F_scePaf_0312
	IMPORT_FUNC	"scePaf",0x4ADAEF94,scePaf_4ADAEF94
#endif
#ifdef F_scePaf_0313
	IMPORT_FUNC	"scePaf",0x95708BC0,scePaf_95708BC0
#endif
#ifdef F_scePaf_0314
	IMPORT_FUNC	"scePaf",0xC85155C9,scePaf_C85155C9
#endif
#ifdef F_scePaf_0315
	IMPORT_FUNC	"scePaf",0xDEF9EBE7,scePaf_DEF9EBE7
#endif
#ifdef F_scePaf_0316
	IMPORT_FUNC	"scePaf",0xF23F3226,scePaf_F23F3226
#endif
#ifdef F_scePaf_0317
	IMPORT_FUNC	"scePaf",0xD153385E,scePaf_D153385E
#endif
#ifdef F_scePaf_0318
	IMPORT_FUNC	"scePaf",0x86A5AE7D,scePaf_86A5AE7D
#endif
#ifdef F_scePaf_0319
	IMPORT_FUNC	"scePaf",0x5A8D4BDB,scePaf_5A8D4BDB
#endif
#ifdef F_scePaf_0320
	IMPORT_FUNC	"scePaf",0x2120282A,scePaf_2120282A
#endif
#ifdef F_scePaf_0321
	IMPORT_FUNC	"scePaf",0x8159EB28,scePaf_8159EB28
#endif
#ifdef F_scePaf_0322
	IMPORT_FUNC	"scePaf",0x5CE11C03,scePaf_5CE11C03
#endif
#ifdef F_scePaf_0323
	IMPORT_FUNC	"scePaf",0x05073826,scePaf_05073826
#endif
#ifdef F_scePaf_0324
	IMPORT_FUNC	"scePaf",0xA4B48F00,scePaf_A4B48F00
#endif
#ifdef F_scePaf_0325
	IMPORT_FUNC	"scePaf",0x224C33F0,scePaf_224C33F0
#endif
#ifdef F_scePaf_0326
	IMPORT_FUNC	"scePaf",0x3DBE861F,scePaf_3DBE861F
#endif
#ifdef F_scePaf_0327
	IMPORT_FUNC	"scePaf",0xFA78AF39,scePaf_FA78AF39
#endif
#ifdef F_scePaf_0328
	IMPORT_FUNC	"scePaf",0xA3761F27,scePaf_A3761F27
#endif
#ifdef F_scePaf_0329
	IMPORT_FUNC	"scePaf",0xDE75C2BA,scePaf_DE75C2BA
#endif
#ifdef F_scePaf_0330
	IMPORT_FUNC	"scePaf",0x4129A915,scePaf_4129A915
#endif
#ifdef F_scePaf_0331
	IMPORT_FUNC	"scePaf",0x8A51BA1E,scePaf_8A51BA1E
#endif
#ifdef F_scePaf_0332
	IMPORT_FUNC	"scePaf",0x0FFA3ECE,scePaf_0FFA3ECE
#endif
#ifdef F_scePaf_0333
	IMPORT_FUNC	"scePaf",0x89582FD0,scePaf_89582FD0
#endif
#ifdef F_scePaf_0334
	IMPORT_FUNC	"scePaf",0x84913A3A,scePaf_84913A3A
#endif
#ifdef F_scePaf_0335
	IMPORT_FUNC	"scePaf",0x06EA7CDE,scePaf_06EA7CDE
#endif
#ifdef F_scePaf_0336
	IMPORT_FUNC	"scePaf",0x9563887D,scePaf_9563887D
#endif
#ifdef F_scePaf_0337
	IMPORT_FUNC	"scePaf",0x21B885B8,scePaf_21B885B8
#endif
#ifdef F_scePaf_0338
	IMPORT_FUNC	"scePaf",0xB0FD305A,scePaf_B0FD305A
#endif
#ifdef F_scePaf_0339
	IMPORT_FUNC	"scePaf",0x777635B9,scePaf_777635B9
#endif
#ifdef F_scePaf_0340
	IMPORT_FUNC	"scePaf",0xF8301DBC,scePaf_F8301DBC
#endif
#ifdef F_scePaf_0341
	IMPORT_FUNC	"scePaf",0x5A818E41,scePaf_5A818E41
#endif
#ifdef F_scePaf_0342
	IMPORT_FUNC	"scePaf",0xA9970EF5,scePaf_A9970EF5
#endif
#ifdef F_scePaf_0343
	IMPORT_FUNC	"scePaf",0x6741C662,scePaf_6741C662
#endif
#ifdef F_scePaf_0344
	IMPORT_FUNC	"scePaf",0x14CE7F6F,scePaf_14CE7F6F
#endif
#ifdef F_scePaf_0345
	IMPORT_FUNC	"scePaf",0xDFC8650C,scePaf_DFC8650C
#endif
#ifdef F_scePaf_0346
	IMPORT_FUNC	"scePaf",0xECE59E24,scePaf_ECE59E24
#endif
#ifdef F_scePaf_0347
	IMPORT_FUNC	"scePaf",0x4D810FDC,scePaf_4D810FDC
#endif
#ifdef F_scePaf_0348
	IMPORT_FUNC	"scePaf",0xABCBC1C5,scePaf_ABCBC1C5
#endif
#ifdef F_scePaf_0349
	IMPORT_FUNC	"scePaf",0x7C2C2742,scePaf_7C2C2742
#endif
#ifdef F_scePaf_0350
	IMPORT_FUNC	"scePaf",0xD0AD10FF,scePaf_D0AD10FF
#endif
#ifdef F_scePaf_0351
	IMPORT_FUNC	"scePaf",0x2A2EB136,scePaf_2A2EB136
#endif
#ifdef F_scePaf_0352
	IMPORT_FUNC	"scePaf",0x20F5234E,scePaf_20F5234E
#endif
#ifdef F_scePaf_0353
	IMPORT_FUNC	"scePaf",0x6F74F263,scePaf_6F74F263
#endif
#ifdef F_scePaf_0354
	IMPORT_FUNC	"scePaf",0xD6232F26,scePaf_D6232F26
#endif
#ifdef F_scePaf_0355
	IMPORT_FUNC	"scePaf",0xED83B18F,scePaf_ED83B18F
#endif
#ifdef F_scePaf_0356
	IMPORT_FUNC	"scePaf",0xD6C1FF36,scePaf_D6C1FF36
#endif
#ifdef F_scePaf_0357
	IMPORT_FUNC	"scePaf",0x7952AE83,scePaf_7952AE83
#endif
#ifdef F_scePaf_0358
	IMPORT_FUNC	"scePaf",0xFDB98CAC,scePaf_FDB98CAC
#endif
#ifdef F_scePaf_0359
	IMPORT_FUNC	"scePaf",0xBA1F20EE,scePaf_BA1F20EE
#endif
#ifdef F_scePaf_0360
	IMPORT_FUNC	"scePaf",0xD96449B4,scePaf_D96449B4
#endif
#ifdef F_scePaf_0361
	IMPORT_FUNC	"scePaf",0x71EDAD83,scePaf_71EDAD83
#endif
#ifdef F_scePaf_0362
	IMPORT_FUNC	"scePaf",0x2CB6FBBE,scePaf_2CB6FBBE
#endif
#ifdef F_scePaf_0363
	IMPORT_FUNC	"scePaf",0x442F1731,scePaf_442F1731
#endif
#ifdef F_scePaf_0364
	IMPORT_FUNC	"scePaf",0xE418D7E0,scePaf_E418D7E0
#endif
#ifdef F_scePaf_0365
	IMPORT_FUNC	"scePaf",0xC8FD64AA,scePaf_C8FD64AA
#endif
#ifdef F_scePaf_0366
	IMPORT_FUNC	"scePaf",0xDB230BE1,scePaf_DB230BE1
#endif
#ifdef F_scePaf_0367
	IMPORT_FUNC	"scePaf",0x0FB7D433,scePaf_0FB7D433
#endif
#ifdef F_scePaf_0368
	IMPORT_FUNC	"scePaf",0xC2E4423A,scePaf_C2E4423A
#endif
#ifdef F_scePaf_0369
	IMPORT_FUNC	"scePaf",0xA574DB92,scePaf_A574DB92
#endif
#ifdef F_scePaf_0370
	IMPORT_FUNC	"scePaf",0xC6F44EF9,scePaf_C6F44EF9
#endif
#ifdef F_scePaf_0371
	IMPORT_FUNC	"scePaf",0x6B678D44,scePaf_6B678D44
#endif
#ifdef F_scePaf_0372
	IMPORT_FUNC	"scePaf",0xE15A64EA,scePaf_E15A64EA
#endif
#ifdef F_scePaf_0373
	IMPORT_FUNC	"scePaf",0x6A772BF7,scePaf_6A772BF7
#endif
#ifdef F_scePaf_0374
	IMPORT_FUNC	"scePaf",0xD180ACBA,scePaf_D180ACBA
#endif
#ifdef F_scePaf_0375
	IMPORT_FUNC	"scePaf",0x4C5F6657,scePaf_4C5F6657
#endif
#ifdef F_scePaf_0376
	IMPORT_FUNC	"scePaf",0xDFB912CB,scePaf_DFB912CB
#endif
#ifdef F_scePaf_0377
	IMPORT_FUNC	"scePaf",0xBAA76FDE,scePaf_BAA76FDE
#endif
#ifdef F_scePaf_0378
	IMPORT_FUNC	"scePaf",0x6CF44237,scePaf_6CF44237
#endif
#ifdef F_scePaf_0379
	IMPORT_FUNC	"scePaf",0xCFAF88AB,scePaf_CFAF88AB
#endif
#ifdef F_scePaf_0380
	IMPORT_FUNC	"scePaf",0xD34D0B82,scePaf_D34D0B82
#endif
#ifdef F_scePaf_0381
	IMPORT_FUNC	"scePaf",0x8CDEDC6F,scePaf_8CDEDC6F
#endif
#ifdef F_scePaf_0382
	IMPORT_FUNC	"scePaf",0x22B0D7D8,scePaf_22B0D7D8
#endif
#ifdef F_scePaf_0383
	IMPORT_FUNC	"scePaf",0xCA8CDF32,scePaf_CA8CDF32
#endif
#ifdef F_scePaf_0384
	IMPORT_FUNC	"scePaf",0xFCABD0E7,scePaf_FCABD0E7
#endif
#ifdef F_scePaf_0385
	IMPORT_FUNC	"scePaf",0xEE10AEF1,scePaf_EE10AEF1
#endif
#ifdef F_scePaf_0386
	IMPORT_FUNC	"scePaf",0xD99BEC81,scePaf_D99BEC81
#endif
#ifdef F_scePaf_0387
	IMPORT_FUNC	"scePaf",0x4D4805AF,scePaf_4D4805AF
#endif
#ifdef F_scePaf_0388
	IMPORT_FUNC	"scePaf",0x28F8DE83,scePaf_28F8DE83
#endif
#ifdef F_scePaf_0389
	IMPORT_FUNC	"scePaf",0xB1F587EF,scePaf_B1F587EF
#endif
#ifdef F_scePaf_0390
	IMPORT_FUNC	"scePaf",0x8C1ED07B,scePaf_8C1ED07B
#endif
#ifdef F_scePaf_0391
	IMPORT_FUNC	"scePaf",0x04EF78CD,scePaf_04EF78CD
#endif
#ifdef F_scePaf_0392
	IMPORT_FUNC	"scePaf",0x75A553A2,scePaf_75A553A2
#endif
#ifdef F_scePaf_0393
	IMPORT_FUNC	"scePaf",0xF4404EAF,scePaf_F4404EAF
#endif
#ifdef F_scePaf_0394
	IMPORT_FUNC	"scePaf",0xD63D4561,scePaf_D63D4561
#endif
#ifdef F_scePaf_0395
	IMPORT_FUNC	"scePaf",0x81667058,scePaf_81667058
#endif
#ifdef F_scePaf_0396
	IMPORT_FUNC	"scePaf",0x149CDEB9,scePaf_149CDEB9
#endif
#ifdef F_scePaf_0397
	IMPORT_FUNC	"scePaf",0x62081F34,scePaf_62081F34
#endif
#ifdef F_scePaf_0398
	IMPORT_FUNC	"scePaf",0xBECD1827,scePaf_BECD1827
#endif
#ifdef F_scePaf_0399
	IMPORT_FUNC	"scePaf",0xA8711520,scePaf_A8711520
#endif
#ifdef F_scePaf_0400
	IMPORT_FUNC	"scePaf",0xFCDD55E3,scePaf_FCDD55E3
#endif
#ifdef F_scePaf_0401
	IMPORT_FUNC	"scePaf",0x2EABF548,scePaf_2EABF548
#endif
#ifdef F_scePaf_0402
	IMPORT_FUNC	"scePaf",0x50F72192,scePaf_50F72192
#endif
#ifdef F_scePaf_0403
	IMPORT_FUNC	"scePaf",0x73712598,scePaf_73712598
#endif
#ifdef F_scePaf_0404
	IMPORT_FUNC	"scePaf",0x8B439A23,scePaf_8B439A23
#endif
#ifdef F_scePaf_0405
	IMPORT_FUNC	"scePaf",0x7435C5D5,scePaf_7435C5D5
#endif
#ifdef F_scePaf_0406
	IMPORT_FUNC	"scePaf",0xCC103AD2,scePaf_CC103AD2
#endif
#ifdef F_scePaf_0407
	IMPORT_FUNC	"scePaf",0x566BC690,scePaf_566BC690
#endif
#ifdef F_scePaf_0408
	IMPORT_FUNC	"scePaf",0x68569AAC,scePaf_68569AAC
#endif
#ifdef F_scePaf_0409
	IMPORT_FUNC	"scePaf",0x76491EEA,scePaf_76491EEA
#endif
#ifdef F_scePaf_0410
	IMPORT_FUNC	"scePaf",0x7771BC86,scePaf_7771BC86
#endif
#ifdef F_scePaf_0411
	IMPORT_FUNC	"scePaf",0x06BB62B7,scePaf_06BB62B7
#endif
#ifdef F_scePaf_0412
	IMPORT_FUNC	"scePaf",0x30F5E7DF,scePaf_30F5E7DF
#endif
#ifdef F_scePaf_0413
	IMPORT_FUNC	"scePaf",0x97B9C21E,scePaf_97B9C21E
#endif
#ifdef F_scePaf_0414
	IMPORT_FUNC	"scePaf",0xD16E5935,scePaf_D16E5935
#endif
#ifdef F_scePaf_0415
	IMPORT_FUNC	"scePaf",0x9D496842,scePaf_9D496842
#endif
#ifdef F_scePaf_0416
	IMPORT_FUNC	"scePaf",0x2750CF68,scePaf_2750CF68
#endif
#ifdef F_scePaf_0417
	IMPORT_FUNC	"scePaf",0xFB3A9617,scePaf_FB3A9617
#endif
#ifdef F_scePaf_0418
	IMPORT_FUNC	"scePaf",0x35F003C0,scePaf_35F003C0
#endif
#ifdef F_scePaf_0419
	IMPORT_FUNC	"scePaf",0xEBDC149C,scePaf_EBDC149C
#endif
#ifdef F_scePaf_0420
	IMPORT_FUNC	"scePaf",0x08DD2D50,scePaf_08DD2D50
#endif
#ifdef F_scePaf_0421
	IMPORT_FUNC	"scePaf",0x846E1F0A,scePaf_846E1F0A
#endif
#ifdef F_scePaf_0422
	IMPORT_FUNC	"scePaf",0x4AB0D3F4,scePaf_4AB0D3F4
#endif
#ifdef F_scePaf_0423
	IMPORT_FUNC	"scePaf",0x9122393C,scePaf_9122393C
#endif
#ifdef F_scePaf_0424
	IMPORT_FUNC	"scePaf",0x5C4BF618,scePaf_5C4BF618
#endif
#ifdef F_scePaf_0425
	IMPORT_FUNC	"scePaf",0x93538664,scePaf_93538664
#endif
#ifdef F_scePaf_0426
	IMPORT_FUNC	"scePaf",0x952CE8AF,scePaf_952CE8AF
#endif
#ifdef F_scePaf_0427
	IMPORT_FUNC	"scePaf",0x21DBFF5B,scePaf_21DBFF5B
#endif
#ifdef F_scePaf_0428
	IMPORT_FUNC	"scePaf",0x359CBCAF,scePaf_359CBCAF
#endif
#ifdef F_scePaf_0429
	IMPORT_FUNC	"scePaf",0x3684D457,scePaf_3684D457
#endif
#ifdef F_scePaf_0430
	IMPORT_FUNC	"scePaf",0x0598FFD6,scePaf_0598FFD6
#endif
#ifdef F_scePaf_0431
	IMPORT_FUNC	"scePaf",0xCAF82B9B,scePaf_CAF82B9B
#endif
#ifdef F_scePaf_0432
	IMPORT_FUNC	"scePaf",0x5B202AED,scePaf_5B202AED
#endif
#ifdef F_scePaf_0433
	IMPORT_FUNC	"scePaf",0x50DC7446,scePaf_50DC7446
#endif
#ifdef F_scePaf_0434
	IMPORT_FUNC	"scePaf",0x36CB5601,scePaf_36CB5601
#endif
#ifdef F_scePaf_0435
	IMPORT_FUNC	"scePaf",0xBA32D6E6,scePaf_BA32D6E6
#endif
#ifdef F_scePaf_0436
	IMPORT_FUNC	"scePaf",0xEAB7BD23,scePaf_EAB7BD23
#endif
#ifdef F_scePaf_0437
	IMPORT_FUNC	"scePaf",0x669DE9B1,scePaf_669DE9B1
#endif
#ifdef F_scePaf_0438
	IMPORT_FUNC	"scePaf",0x940D9797,scePaf_940D9797
#endif
#ifdef F_scePaf_0439
	IMPORT_FUNC	"scePaf",0x4708AED4,scePaf_4708AED4
#endif
#ifdef F_scePaf_0440
	IMPORT_FUNC	"scePaf",0x32A70C80,scePaf_32A70C80
#endif
#ifdef F_scePaf_0441
	IMPORT_FUNC	"scePaf",0xCAF05F1D,scePaf_CAF05F1D
#endif
#ifdef F_scePaf_0442
	IMPORT_FUNC	"scePaf",0x49CE42F7,scePaf_49CE42F7
#endif
#ifdef F_scePaf_0443
	IMPORT_FUNC	"scePaf",0xFC6B7234,scePaf_FC6B7234
#endif
#ifdef F_scePaf_0444
	IMPORT_FUNC	"scePaf",0x63B24F4D,scePaf_63B24F4D
#endif
#ifdef F_scePaf_0445
	IMPORT_FUNC	"scePaf",0x6F33D1DF,scePaf_6F33D1DF
#endif
#ifdef F_scePaf_0446
	IMPORT_FUNC	"scePaf",0x3481F595,scePaf_3481F595
#endif
#ifdef F_scePaf_0447
	IMPORT_FUNC	"scePaf",0x986FEBD1,scePaf_986FEBD1
#endif
#ifdef F_scePaf_0448
	IMPORT_FUNC	"scePaf",0x458A9C95,scePaf_458A9C95
#endif
#ifdef F_scePaf_0449
	IMPORT_FUNC	"scePaf",0xD3D12890,scePaf_D3D12890
#endif
#ifdef F_scePaf_0450
	IMPORT_FUNC	"scePaf",0x9D1633BC,scePaf_9D1633BC
#endif
#ifdef F_scePaf_0451
	IMPORT_FUNC	"scePaf",0x98E1BC87,scePaf_98E1BC87
#endif
#ifdef F_scePaf_0452
	IMPORT_FUNC	"scePaf",0x84240C1D,scePaf_84240C1D
#endif
#ifdef F_scePaf_0453
	IMPORT_FUNC	"scePaf",0x5D786CDD,scePaf_5D786CDD
#endif
#ifdef F_scePaf_0454
	IMPORT_FUNC	"scePaf",0x6E95EFAA,scePaf_6E95EFAA
#endif
#ifdef F_scePaf_0455
	IMPORT_FUNC	"scePaf",0x88D73AED,scePaf_88D73AED
#endif
#ifdef F_scePaf_0456
	IMPORT_FUNC	"scePaf",0xD4FAE7D0,scePaf_D4FAE7D0
#endif
#ifdef F_scePaf_0457
	IMPORT_FUNC	"scePaf",0x338C3774,scePaf_338C3774
#endif
#ifdef F_scePaf_0458
	IMPORT_FUNC	"scePaf",0xDC2CA0F7,scePaf_DC2CA0F7
#endif
#ifdef F_scePaf_0459
	IMPORT_FUNC	"scePaf",0x7F7791A1,scePaf_7F7791A1
#endif
#ifdef F_scePaf_0460
	IMPORT_FUNC	"scePaf",0xF28A9DB3,scePaf_F28A9DB3
#endif
#ifdef F_scePaf_0461
	IMPORT_FUNC	"scePaf",0xBB3CBD19,scePaf_BB3CBD19
#endif
#ifdef F_scePaf_0462
	IMPORT_FUNC	"scePaf",0x27F64616,scePaf_27F64616
#endif
#ifdef F_scePaf_0463
	IMPORT_FUNC	"scePaf",0x72129CFB,scePaf_72129CFB
#endif
#ifdef F_scePaf_0464
	IMPORT_FUNC	"scePaf",0xDAB59652,scePaf_DAB59652
#endif
#ifdef F_scePaf_0465
	IMPORT_FUNC	"scePaf",0x1A45C860,scePaf_1A45C860
#endif
#ifdef F_scePaf_0466
	IMPORT_FUNC	"scePaf",0xD7215544,scePaf_D7215544
#endif
#ifdef F_scePaf_0467
	IMPORT_FUNC	"scePaf",0x5DFB5858,scePaf_5DFB5858
#endif
#ifdef F_scePaf_0468
	IMPORT_FUNC	"scePaf",0x5EBC648F,scePaf_5EBC648F
#endif
#ifdef F_scePaf_0469
	IMPORT_FUNC	"scePaf",0xF247A0BD,scePaf_F247A0BD
#endif
#ifdef F_scePaf_0470
	IMPORT_FUNC	"scePaf",0x910A6B7B,scePaf_910A6B7B
#endif
#ifdef F_scePaf_0471
	IMPORT_FUNC	"scePaf",0x5470B915,scePaf_5470B915
#endif
#ifdef F_scePaf_0472
	IMPORT_FUNC	"scePaf",0xD05C226F,scePaf_D05C226F
#endif
#ifdef F_scePaf_0473
	IMPORT_FUNC	"scePaf",0xCE21D21F,scePaf_CE21D21F
#endif
#ifdef F_scePaf_0474
	IMPORT_FUNC	"scePaf",0x8860B0FD,scePaf_8860B0FD
#endif
#ifdef F_scePaf_0475
	IMPORT_FUNC	"scePaf",0x2AA842B0,scePaf_2AA842B0
#endif
#ifdef F_scePaf_0476
	IMPORT_FUNC	"scePaf",0xD5372E90,scePaf_D5372E90
#endif
#ifdef F_scePaf_0477
	IMPORT_FUNC	"scePaf",0xD7C2E0AD,scePaf_D7C2E0AD
#endif
#ifdef F_scePaf_0478
	IMPORT_FUNC	"scePaf",0xF4AB3180,scePaf_F4AB3180
#endif
#ifdef F_scePaf_0479
	IMPORT_FUNC	"scePaf",0xEA026663,scePaf_EA026663
#endif
#ifdef F_scePaf_0480
	IMPORT_FUNC	"scePaf",0xF609FA81,scePaf_F609FA81
#endif
#ifdef F_scePaf_0481
	IMPORT_FUNC	"scePaf",0xBBDE1C17,scePaf_BBDE1C17
#endif
#ifdef F_scePaf_0482
	IMPORT_FUNC	"scePaf",0x8117E6C8,scePaf_8117E6C8
#endif
#ifdef F_scePaf_0483
	IMPORT_FUNC	"scePaf",0x1811AD32,scePaf_1811AD32
#endif
#ifdef F_scePaf_0484
	IMPORT_FUNC	"scePaf",0x6CE39EF8,scePaf_6CE39EF8
#endif
#ifdef F_scePaf_0485
	IMPORT_FUNC	"scePaf",0xB09203B0,scePaf_B09203B0
#endif
#ifdef F_scePaf_0486
	IMPORT_FUNC	"scePaf",0x58C69BDA,scePaf_58C69BDA
#endif
#ifdef F_scePaf_0487
	IMPORT_FUNC	"scePaf",0xE32B3558,scePaf_E32B3558
#endif
#ifdef F_scePaf_0488
	IMPORT_FUNC	"scePaf",0x86237EB3,scePaf_86237EB3
#endif
#ifdef F_scePaf_0489
	IMPORT_FUNC	"scePaf",0xBEF9FF15,scePaf_BEF9FF15
#endif
#ifdef F_scePaf_0490
	IMPORT_FUNC	"scePaf",0xFE4D4112,scePaf_FE4D4112
#endif
#ifdef F_scePaf_0491
	IMPORT_FUNC	"scePaf",0xDAA609BB,scePaf_DAA609BB
#endif
#ifdef F_scePaf_0492
	IMPORT_FUNC	"scePaf",0x69CA1A2D,scePaf_69CA1A2D
#endif
#ifdef F_scePaf_0493
	IMPORT_FUNC	"scePaf",0xD3F5956D,scePaf_D3F5956D
#endif
#ifdef F_scePaf_0494
	IMPORT_FUNC	"scePaf",0x602EB0CE,scePaf_602EB0CE
#endif
#ifdef F_scePaf_0495
	IMPORT_FUNC	"scePaf",0x6A14BB04,scePaf_6A14BB04
#endif
#ifdef F_scePaf_0496
	IMPORT_FUNC	"scePaf",0x95960A88,scePaf_95960A88
#endif
#ifdef F_scePaf_0497
	IMPORT_FUNC	"scePaf",0xD6CD39AF,scePaf_D6CD39AF
#endif
#ifdef F_scePaf_0498
	IMPORT_FUNC	"scePaf",0x79E57CAF,scePaf_79E57CAF
#endif
#ifdef F_scePaf_0499
	IMPORT_FUNC	"scePaf",0x9DED6118,scePaf_9DED6118
#endif
#ifdef F_scePaf_0500
	IMPORT_FUNC	"scePaf",0x997D2809,scePaf_997D2809
#endif
#ifdef F_scePaf_0501
	IMPORT_FUNC	"scePaf",0x7D83FB20,scePaf_7D83FB20
#endif
#ifdef F_scePaf_0502
	IMPORT_FUNC	"scePaf",0xE1242646,scePaf_E1242646
#endif
#ifdef F_scePaf_0503
	IMPORT_FUNC	"scePaf",0x0F3527DD,scePaf_0F3527DD
#endif
#ifdef F_scePaf_0504
	IMPORT_FUNC	"scePaf",0x10C1DB70,scePaf_10C1DB70
#endif
#ifdef F_scePaf_0505
	IMPORT_FUNC	"scePaf",0x39B36025,scePaf_39B36025
#endif
#ifdef F_scePaf_0506
	IMPORT_FUNC	"scePaf",0x01C2FC36,scePaf_01C2FC36
#endif
#ifdef F_scePaf_0507
	IMPORT_FUNC	"scePaf",0x17308FC9,scePaf_17308FC9
#endif
#ifdef F_scePaf_0508
	IMPORT_FUNC	"scePaf",0xF3967AF5,scePaf_F3967AF5
#endif
#ifdef F_scePaf_0509
	IMPORT_FUNC	"scePaf",0x34C973B6,scePaf_34C973B6
#endif
#ifdef F_scePaf_0510
	IMPORT_FUNC	"scePaf",0x4C8C2E25,scePaf_4C8C2E25
#endif
#ifdef F_scePaf_0511
	IMPORT_FUNC	"scePaf",0x81FD71A9,scePaf_81FD71A9
#endif
#ifdef F_scePaf_0512
	IMPORT_FUNC	"scePaf",0xBBBF145C,scePaf_BBBF145C
#endif
#ifdef F_scePaf_0513
	IMPORT_FUNC	"scePaf",0xB52E43FB,scePaf_B52E43FB
#endif
#ifdef F_scePaf_0514
	IMPORT_FUNC	"scePaf",0x95C97571,scePaf_95C97571
#endif
#ifdef F_scePaf_0515
	IMPORT_FUNC	"scePaf",0xF273FE50,scePaf_F273FE50
#endif
#ifdef F_scePaf_0516
	IMPORT_FUNC	"scePaf",0xAD7A45F9,scePaf_AD7A45F9
#endif
#ifdef F_scePaf_0517
	IMPORT_FUNC	"scePaf",0x67C7567E,scePaf_67C7567E
#endif
#ifdef F_scePaf_0518
	IMPORT_FUNC	"scePaf",0x56F4D69F,scePaf_56F4D69F
#endif
#ifdef F_scePaf_0519
	IMPORT_FUNC	"scePaf",0xD7E925A1,scePaf_D7E925A1
#endif
#ifdef F_scePaf_0520
	IMPORT_FUNC	"scePaf",0x296ED0EF,scePaf_296ED0EF
#endif
#ifdef F_scePaf_0521
	IMPORT_FUNC	"scePaf",0xDBD69B7B,scePaf_DBD69B7B
#endif
#ifdef F_scePaf_0522
	IMPORT_FUNC	"scePaf",0x7DDE0658,scePaf_7DDE0658
#endif
#ifdef F_scePaf_0523
	IMPORT_FUNC	"scePaf",0xCC3CFABF,scePaf_CC3CFABF
#endif
#ifdef F_scePaf_0524
	IMPORT_FUNC	"scePaf",0xD2C94856,scePaf_D2C94856
#endif
#ifdef F_scePaf_0525
	IMPORT_FUNC	"scePaf",0xEF346632,scePaf_EF346632
#endif
#ifdef F_scePaf_0526
	IMPORT_FUNC	"scePaf",0x79293604,scePaf_79293604
#endif
#ifdef F_scePaf_0527
	IMPORT_FUNC	"scePaf",0xAECF91A9,scePaf_AECF91A9
#endif
#ifdef F_scePaf_0528
	IMPORT_FUNC	"scePaf",0x3342C5F5,scePaf_3342C5F5
#endif
#ifdef F_scePaf_0529
	IMPORT_FUNC	"scePaf",0x48B5C1C0,scePaf_48B5C1C0
#endif
#ifdef F_scePaf_0530
	IMPORT_FUNC	"scePaf",0xD188831A,scePaf_D188831A
#endif
#ifdef F_scePaf_0531
	IMPORT_FUNC	"scePaf",0x2D08CA09,scePaf_2D08CA09
#endif
#ifdef F_scePaf_0532
	IMPORT_FUNC	"scePaf",0x55C7628A,scePaf_55C7628A
#endif
#ifdef F_scePaf_0533
	IMPORT_FUNC	"scePaf",0xA9CE8FBB,scePaf_A9CE8FBB
#endif
#ifdef F_scePaf_0534
	IMPORT_FUNC	"scePaf",0xD6F088EF,scePaf_D6F088EF
#endif
#ifdef F_scePaf_0535
	IMPORT_FUNC	"scePaf",0xF2E5FDEB,scePaf_F2E5FDEB
#endif
#ifdef F_scePaf_0536
	IMPORT_FUNC	"scePaf",0x6E3E2085,scePaf_6E3E2085
#endif
#ifdef F_scePaf_0537
	IMPORT_FUNC	"scePaf",0x6676FAA6,scePaf_6676FAA6
#endif
#ifdef F_scePaf_0538
	IMPORT_FUNC	"scePaf",0x7D9A4824,scePaf_7D9A4824
#endif
#ifdef F_scePaf_0539
	IMPORT_FUNC	"scePaf",0xD8739C4C,scePaf_D8739C4C
#endif
#ifdef F_scePaf_0540
	IMPORT_FUNC	"scePaf",0x34C7D69A,scePaf_34C7D69A
#endif
#ifdef F_scePaf_0541
	IMPORT_FUNC	"scePaf",0xCDB85442,scePaf_CDB85442
#endif
#ifdef F_scePaf_0542
	IMPORT_FUNC	"scePaf",0xDFD3E855,scePaf_DFD3E855
#endif
#ifdef F_scePaf_0543
	IMPORT_FUNC	"scePaf",0x2AA80564,scePaf_2AA80564
#endif
#ifdef F_scePaf_0544
	IMPORT_FUNC	"scePaf",0x6BAC756B,scePaf_6BAC756B
#endif
#ifdef F_scePaf_0545
	IMPORT_FUNC	"scePaf",0x3A844B7B,scePaf_3A844B7B
#endif
#ifdef F_scePaf_0546
	IMPORT_FUNC	"scePaf",0x9B8CBC5F,scePaf_9B8CBC5F
#endif
#ifdef F_scePaf_0547
	IMPORT_FUNC	"scePaf",0xBE5B0791,scePaf_BE5B0791
#endif
#ifdef F_scePaf_0548
	IMPORT_FUNC	"scePaf",0xFCD816FA,scePaf_FCD816FA
#endif
#ifdef F_scePaf_0549
	IMPORT_FUNC	"scePaf",0x548AA4E7,scePaf_548AA4E7
#endif
#ifdef F_scePaf_0550
	IMPORT_FUNC	"scePaf",0x21A0C6E0,scePaf_21A0C6E0
#endif
#ifdef F_scePaf_0551
	IMPORT_FUNC	"scePaf",0xC01BF169,scePaf_C01BF169
#endif
#ifdef F_scePaf_0552
	IMPORT_FUNC	"scePaf",0xAD1721B8,scePaf_AD1721B8
#endif
#ifdef F_scePaf_0553
	IMPORT_FUNC	"scePaf",0x910BCFE1,scePaf_910BCFE1
#endif
#ifdef F_scePaf_0554
	IMPORT_FUNC	"scePaf",0x75DBA857,scePaf_75DBA857
#endif
#ifdef F_scePaf_0555
	IMPORT_FUNC	"scePaf",0x849ED670,scePaf_849ED670
#endif
#ifdef F_scePaf_0556
	IMPORT_FUNC	"scePaf",0x5148EFE2,scePaf_5148EFE2
#endif
#ifdef F_scePaf_0557
	IMPORT_FUNC	"scePaf",0xD36F3AAA,scePaf_D36F3AAA
#endif
#ifdef F_scePaf_0558
	IMPORT_FUNC	"scePaf",0x1A468B86,scePaf_1A468B86
#endif
#ifdef F_scePaf_0559
	IMPORT_FUNC	"scePaf",0x8E757709,scePaf_8E757709
#endif
#ifdef F_scePaf_0560
	IMPORT_FUNC	"scePaf",0x7BBD70F0,scePaf_7BBD70F0
#endif
#ifdef F_scePaf_0561
	IMPORT_FUNC	"scePaf",0xDFFE9ED6,scePaf_DFFE9ED6
#endif
#ifdef F_scePaf_0562
	IMPORT_FUNC	"scePaf",0x72A0044D,scePaf_72A0044D
#endif
#ifdef F_scePaf_0563
	IMPORT_FUNC	"scePaf",0x4612DB4B,scePaf_4612DB4B
#endif
#ifdef F_scePaf_0564
	IMPORT_FUNC	"scePaf",0x78219D10,scePaf_78219D10
#endif
#ifdef F_scePaf_0565
	IMPORT_FUNC	"scePaf",0x97FDA760,scePaf_97FDA760
#endif
#ifdef F_scePaf_0566
	IMPORT_FUNC	"scePaf",0x298246CD,scePaf_298246CD
#endif
#ifdef F_scePaf_0567
	IMPORT_FUNC	"scePaf",0x12C50A9D,scePaf_12C50A9D
#endif
#ifdef F_scePaf_0568
	IMPORT_FUNC	"scePaf",0x3D451DE8,scePaf_3D451DE8
#endif
#ifdef F_scePaf_0569
	IMPORT_FUNC	"scePaf",0x8FE88010,scePaf_8FE88010
#endif
#ifdef F_scePaf_0570
	IMPORT_FUNC	"scePaf",0x21A183A7,scePaf_21A183A7
#endif
#ifdef F_scePaf_0571
	IMPORT_FUNC	"scePaf",0xABEBF18D,scePaf_ABEBF18D
#endif
#ifdef F_scePaf_0572
	IMPORT_FUNC	"scePaf",0x94136997,scePaf_94136997
#endif
#ifdef F_scePaf_0573
	IMPORT_FUNC	"scePaf",0xA25BDAA2,scePaf_A25BDAA2
#endif
#ifdef F_scePaf_0574
	IMPORT_FUNC	"scePaf",0x9F60CB01,scePaf_9F60CB01
#endif
#ifdef F_scePaf_0575
	IMPORT_FUNC	"scePaf",0x50B0C0A1,scePaf_50B0C0A1
#endif
#ifdef F_scePaf_0576
	IMPORT_FUNC	"scePaf",0x7E304DCF,scePaf_7E304DCF
#endif
#ifdef F_scePaf_0577
	IMPORT_FUNC	"scePaf",0x1F43B8A2,scePaf_1F43B8A2
#endif
#ifdef F_scePaf_0578
	IMPORT_FUNC	"scePaf",0x891B7F7F,scePaf_891B7F7F
#endif
#ifdef F_scePaf_0579
	IMPORT_FUNC	"scePaf",0x14D80C40,scePaf_14D80C40
#endif
#ifdef F_scePaf_0580
	IMPORT_FUNC	"scePaf",0x87E5F9C7,scePaf_87E5F9C7
#endif
#ifdef F_scePaf_0581
	IMPORT_FUNC	"scePaf",0xD3AB4076,scePaf_D3AB4076
#endif
#ifdef F_scePaf_0582
	IMPORT_FUNC	"scePaf",0x537D04C6,scePaf_537D04C6
#endif
#ifdef F_scePaf_0583
	IMPORT_FUNC	"scePaf",0x7AFD6B74,png_create_info_struct
#endif
#ifdef F_scePaf_0584
	IMPORT_FUNC	"scePaf",0x6528115D,png_create_read_struct
#endif
#ifdef F_scePaf_0585
	IMPORT_FUNC	"scePaf",0x211A764A,png_destroy_read_struct
#endif
#ifdef F_scePaf_0586
	IMPORT_FUNC	"scePaf",0x7894B61F,png_error
#endif
#ifdef F_scePaf_0587
	IMPORT_FUNC	"scePaf",0x38F12307,png_get_IHDR
#endif
#ifdef F_scePaf_0588
	IMPORT_FUNC	"scePaf",0xE6432407,png_get_PLTE
#endif
#ifdef F_scePaf_0589
	IMPORT_FUNC	"scePaf",0x07216006,png_get_tRNS
#endif
#ifdef F_scePaf_0590
	IMPORT_FUNC	"scePaf",0xB2290D1A,png_read_end
#endif
#ifdef F_scePaf_0591
	IMPORT_FUNC	"scePaf",0xE327C974,png_read_info
#endif
#ifdef F_scePaf_0592
	IMPORT_FUNC	"scePaf",0x1BDFF258,png_set_read_fn
#endif
#ifdef F_scePaf_0593
	IMPORT_FUNC	"scePaf",0xDB1549DF,png_start_read_image
#endif
#ifdef F_scePaf_0594
	IMPORT_FUNC	"scePaf",0xDDD91620,png_read_image
#endif
#ifdef F_scePaf_0595
	IMPORT_FUNC	"scePaf",0xD4F9270D,png_read_update_info
#endif
#ifdef F_scePaf_0596
	IMPORT_FUNC	"scePaf",0x7333E75A,png_set_packing
#endif
#ifdef F_scePaf_0597
	IMPORT_FUNC	"scePaf",0x1A1F232F,png_set_sig_bytes
#endif
#ifdef F_scePaf_0598
	IMPORT_FUNC	"scePaf",0xC6624F24,png_set_packswap
#endif
#ifdef F_scePaf_0599
	IMPORT_FUNC	"scePaf",0xFBC76D05,sce_png_read
#endif
#ifdef F_scePaf_0600
	IMPORT_FUNC	"scePaf",0xC6A8BEE2,scePaf_C6A8BEE2
#endif
#ifdef F_scePaf_0601
	IMPORT_FUNC	"scePaf",0x8406F469,scePaf_8406F469
#endif
#ifdef F_scePaf_0602
	IMPORT_FUNC	"scePaf",0xB4D1CBBF,scePaf_B4D1CBBF
#endif
#ifdef F_scePaf_0603
	IMPORT_FUNC	"scePaf",0x8D3EAEA3,scePaf_8D3EAEA3
#endif
#ifdef F_scePaf_0604
	IMPORT_FUNC	"scePaf",0xC8E7B03F,scePaf_C8E7B03F
#endif
#ifdef F_scePaf_0605
	IMPORT_FUNC	"scePaf",0xD4DAB044,scePaf_D4DAB044
#endif
#ifdef F_scePaf_0606
	IMPORT_FUNC	"scePaf",0x15939BB8,scePaf_15939BB8
#endif
#ifdef F_scePaf_0607
	IMPORT_FUNC	"scePaf",0x8D736C8F,scePaf_8D736C8F
#endif
#ifdef F_scePaf_0608
	IMPORT_FUNC	"scePaf",0xE0CF8091,scePaf_E0CF8091
#endif
#ifdef F_scePaf_0609
	IMPORT_FUNC	"scePaf",0xBEB47224,scePaf_BEB47224
#endif
#ifdef F_scePaf_0610
	IMPORT_FUNC	"scePaf",0xD9392CCB,scePaf_D9392CCB
#endif
#ifdef F_scePaf_0611
	IMPORT_FUNC	"scePaf",0xF1B73D12,scePaf_F1B73D12
#endif
#ifdef F_scePaf_0612
	IMPORT_FUNC	"scePaf",0x00D1378F,scePaf_00D1378F
#endif
#ifdef F_scePaf_0613
	IMPORT_FUNC	"scePaf",0xD6CDB3BB,scePaf_D6CDB3BB
#endif
#ifdef F_scePaf_0614
	IMPORT_FUNC	"scePaf",0x60CBB63F,scePaf_60CBB63F
#endif
#ifdef F_scePaf_0615
	IMPORT_FUNC	"scePaf",0xF93D4E1F,scePaf_F93D4E1F
#endif
#ifdef F_scePaf_0616
	IMPORT_FUNC	"scePaf",0xB9383A25,scePaf_B9383A25
#endif
#ifdef F_scePaf_0617
	IMPORT_FUNC	"scePaf",0xB7D3C112,scePaf_B7D3C112
#endif
#ifdef F_scePaf_0618
	IMPORT_FUNC	"scePaf",0x4BDEB2A8,scePaf_4BDEB2A8
#endif
#ifdef F_scePaf_0619
	IMPORT_FUNC	"scePaf",0x41B724A5,scePaf_41B724A5
#endif
#ifdef F_scePaf_0620
	IMPORT_FUNC	"scePaf",0xD5F3BAB1,scePaf_D5F3BAB1
#endif
#ifdef F_scePaf_0621
	IMPORT_FUNC	"scePaf",0xEA39A7C1,scePaf_EA39A7C1
#endif
#ifdef F_scePaf_0622
	IMPORT_FUNC	"scePaf",0x6B1E90C7,scePaf_6B1E90C7
#endif
#ifdef F_scePaf_0623
	IMPORT_FUNC	"scePaf",0x66907719,scePaf_66907719
#endif
#ifdef F_scePaf_0624
	IMPORT_FUNC	"scePaf",0xAAD0EE78,scePaf_AAD0EE78
#endif
#ifdef F_scePaf_0625
	IMPORT_FUNC	"scePaf",0xE69C3B1B,scePaf_E69C3B1B
#endif
#ifdef F_scePaf_0626
	IMPORT_FUNC	"scePaf",0xE618F7A8,scePaf_E618F7A8
#endif
#ifdef F_scePaf_0627
	IMPORT_FUNC	"scePaf",0x78F94D84,scePaf_78F94D84
#endif
#ifdef F_scePaf_0628
	IMPORT_FUNC	"scePaf",0x5822F12A,scePaf_5822F12A
#endif
#ifdef F_scePaf_0629
	IMPORT_FUNC	"scePaf",0xFD9DE7B9,scePaf_FD9DE7B9
#endif
#ifdef F_scePaf_0630
	IMPORT_FUNC	"scePaf",0xAD43F865,scePaf_AD43F865
#endif
#ifdef F_scePaf_0631
	IMPORT_FUNC	"scePaf",0x872F948B,scePaf_872F948B
#endif
#ifdef F_scePaf_0632
	IMPORT_FUNC	"scePaf",0xD726F4A2,scePaf_D726F4A2
#endif
#ifdef F_scePaf_0633
	IMPORT_FUNC	"scePaf",0xA044BFC0,scePaf_A044BFC0
#endif
#ifdef F_scePaf_0634
	IMPORT_FUNC	"scePaf",0xF1CF9579,scePaf_F1CF9579
#endif
#ifdef F_scePaf_0635
	IMPORT_FUNC	"scePaf",0x132148FD,scePaf_132148FD
#endif
#ifdef F_scePaf_0636
	IMPORT_FUNC	"scePaf",0x533F3856,scePaf_533F3856
#endif
#ifdef F_scePaf_0637
	IMPORT_FUNC	"scePaf",0x139D9047,scePaf_139D9047
#endif
#ifdef F_scePaf_0638
	IMPORT_FUNC	"scePaf",0x8D3B3587,scePaf_8D3B3587
#endif
#ifdef F_scePaf_0639
	IMPORT_FUNC	"scePaf",0x27760582,scePaf_27760582
#endif
#ifdef F_scePaf_0640
	IMPORT_FUNC	"scePaf",0xFD3FF4AA,scePaf_FD3FF4AA
#endif
#ifdef F_scePaf_0641
	IMPORT_FUNC	"scePaf",0xA0ED77C4,scePaf_A0ED77C4
#endif
#ifdef F_scePaf_0642
	IMPORT_FUNC	"scePaf",0x35F25BA1,scePaf_35F25BA1
#endif
#ifdef F_scePaf_0643
	IMPORT_FUNC	"scePaf",0x75062BCF,scePaf_75062BCF
#endif
#ifdef F_scePaf_0644
	IMPORT_FUNC	"scePaf",0x79493F8F,scePaf_79493F8F
#endif
#ifdef F_scePaf_0645
	IMPORT_FUNC	"scePaf",0x3E203AEB,Heap_Alloc
#endif
#ifdef F_scePaf_0646
	IMPORT_FUNC	"scePaf",0x9948CDB3,Heap_Free
#endif
#ifdef F_scePaf_0647
	IMPORT_FUNC	"scePaf",0xF84A99C8,scePaf_F84A99C8
#endif
#ifdef F_scePaf_0648
	IMPORT_FUNC	"scePaf",0x6D491648,Heap_Create
#endif
#ifdef F_scePaf_0649
	IMPORT_FUNC	"scePaf",0x8A861692,Heap_Destroy
#endif
#ifdef F_scePaf_0650
	IMPORT_FUNC	"scePaf",0xC4BAD564,scePaf_C4BAD564
#endif
#ifdef F_scePaf_0651
	IMPORT_FUNC	"scePaf",0xD27DE19A,scePaf_D27DE19A
#endif
#ifdef F_scePaf_0652
	IMPORT_FUNC	"scePaf",0xBAE16A39,scePaf_BAE16A39
#endif
#ifdef F_scePaf_0653
	IMPORT_FUNC	"scePaf",0x2CFAE498,scePaf_2CFAE498
#endif
#ifdef F_scePaf_0654
	IMPORT_FUNC	"scePaf",0x58846DF3,scePaf_58846DF3
#endif
#ifdef F_scePaf_0655
	IMPORT_FUNC	"scePaf",0xE357380E,scePaf_E357380E
#endif
#ifdef F_scePaf_0656
	IMPORT_FUNC	"scePaf",0x4B4F39FC,scePaf_4B4F39FC
#endif
#ifdef F_scePaf_0657
	IMPORT_FUNC	"scePaf",0x5C5F727C,scePaf_5C5F727C
#endif
#ifdef F_scePaf_0658
	IMPORT_FUNC	"scePaf",0x0F2615A4,scePaf_0F2615A4
#endif
#ifdef F_scePaf_0659
	IMPORT_FUNC	"scePaf",0xEA4C24B3,scePaf_EA4C24B3
#endif
#ifdef F_scePaf_0660
	IMPORT_FUNC	"scePaf",0x28C54317,scePaf_28C54317
#endif
#ifdef F_scePaf_0661
	IMPORT_FUNC	"scePaf",0xCBA9AAB1,scePaf_CBA9AAB1
#endif
#ifdef F_scePaf_0662
	IMPORT_FUNC	"scePaf",0x2C5D3E63,scePaf_2C5D3E63
#endif
#ifdef F_scePaf_0663
	IMPORT_FUNC	"scePaf",0x38316A7D,scePaf_38316A7D
#endif
#ifdef F_scePaf_0664
	IMPORT_FUNC	"scePaf",0x96610AE6,scePaf_96610AE6
#endif
#ifdef F_scePaf_0665
	IMPORT_FUNC	"scePaf",0xA08B0F31,scePaf_A08B0F31
#endif
#ifdef F_scePaf_0666
	IMPORT_FUNC	"scePaf",0xFB3DB2FF,paf_fini
#endif
#ifdef F_scePaf_0667
	IMPORT_FUNC	"scePaf",0xE13B6DAE,sinf
#endif
#ifdef F_scePaf_0668
	IMPORT_FUNC	"scePaf",0xEB6D20A5,cosf
#endif
#ifdef F_scePaf_0669
	IMPORT_FUNC	"scePaf",0x09F5941E,sqrtf
#endif
#ifdef F_scePaf_0670
	IMPORT_FUNC	"scePaf",0x481C9ADA,malloc
#endif
#ifdef F_scePaf_0671
	IMPORT_FUNC	"scePaf",0xAD8AF84F,free
#endif
#ifdef F_scePaf_0672
	IMPORT_FUNC	"scePaf",0xAB7592FF,memcpy
#endif
#ifdef F_scePaf_0673
	IMPORT_FUNC	"scePaf",0x10F3BB61,memset
#endif
#ifdef F_scePaf_0674
	IMPORT_FUNC	"scePaf",0x81D0D1F7,memcpy
#endif
#ifdef F_scePaf_0675
	IMPORT_FUNC	"scePaf",0x7EDCC45E,floorf
#endif
#ifdef F_scePaf_0676
	IMPORT_FUNC	"scePaf",0x820C80E6,acosf
#endif
#ifdef F_scePaf_0677
	IMPORT_FUNC	"scePaf",0xCAB439DF,printf
#endif
