PSPSDK: debug/bitmap.c File Reference
bitmap.c File Reference
#include <pspkernel.h>
#include <pspdisplay.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
Data Structures
struct BitmapHeader
Macros
#define BMP_ID "BM"
#define PSP_SCREEN_WIDTH 480
#define PSP_SCREEN_HEIGHT 272
#define PSP_LINE_SIZE 512
#define BMP_RGB_BYTES_PER_PIXEL 3
Functions
void write_8888_line (void *frame, void *line_buf, int line)
void write_5551_line (void *frame, void *line_buf, int line)
void write_565_line (void *frame, void *line_buf, int line)
void write_4444_line (void *frame, void *line_buf, int line)
int bitmapWrite (void *frame_addr, int format, const char *file)
Macro Definition Documentation
BMP_ID
#define BMP_ID "BM"
Referenced by bitmapWrite().
BMP_RGB_BYTES_PER_PIXEL
#define BMP_RGB_BYTES_PER_PIXEL 3
Referenced by bitmapWrite(), write_4444_line(), write_5551_line(), write_565_line(), and write_8888_line().
PSP_LINE_SIZE
#define PSP_LINE_SIZE 512
Referenced by write_4444_line(), write_5551_line(), write_565_line(), and write_8888_line().
PSP_SCREEN_HEIGHT
#define PSP_SCREEN_HEIGHT 272
Referenced by bitmapWrite().
PSP_SCREEN_WIDTH
#define PSP_SCREEN_WIDTH 480
Referenced by bitmapWrite(), write_4444_line(), write_5551_line(), write_565_line(), and write_8888_line().
Function Documentation
bitmapWrite()
int bitmapWrite (void * frame_addr, int format, const char * file)
References BitmapHeader::bitmapsize, BMP_ID, BMP_RGB_BYTES_PER_PIXEL, BitmapHeader::bpp, BitmapHeader::filesize, BitmapHeader::headsize, BitmapHeader::height, BitmapHeader::hres, BitmapHeader::id, BitmapHeader::offset, BitmapHeader::planes, PSP_DISPLAY_PIXEL_FORMAT_4444, PSP_DISPLAY_PIXEL_FORMAT_5551, PSP_DISPLAY_PIXEL_FORMAT_565, PSP_DISPLAY_PIXEL_FORMAT_8888, PSP_O_CREAT, PSP_O_TRUNC, PSP_O_WRONLY, PSP_SCREEN_HEIGHT, PSP_SCREEN_WIDTH, sceIoClose(), sceIoOpen(), BitmapHeader::vres, BitmapHeader::width, write_4444_line(), write_5551_line(), write_565_line(), and write_8888_line().
Referenced by pspScreenshotSave().
write_4444_line()
void write_4444_line (void * frame, void * line_buf, int line)
References BMP_RGB_BYTES_PER_PIXEL, PSP_DISPLAY_PIXEL_FORMAT_4444, PSP_LINE_SIZE, and PSP_SCREEN_WIDTH.
Referenced by bitmapWrite().
write_5551_line()
void write_5551_line (void * frame, void * line_buf, int line)
References BMP_RGB_BYTES_PER_PIXEL, PSP_DISPLAY_PIXEL_FORMAT_5551, PSP_LINE_SIZE, and PSP_SCREEN_WIDTH.
Referenced by bitmapWrite().
write_565_line()
void write_565_line (void * frame, void * line_buf, int line)
References BMP_RGB_BYTES_PER_PIXEL, PSP_DISPLAY_PIXEL_FORMAT_565, PSP_LINE_SIZE, and PSP_SCREEN_WIDTH.
Referenced by bitmapWrite().
write_8888_line()
void write_8888_line (void * frame, void * line_buf, int line)
References BMP_RGB_BYTES_PER_PIXEL, PSP_DISPLAY_PIXEL_FORMAT_8888, PSP_LINE_SIZE, and PSP_SCREEN_WIDTH.
Referenced by bitmapWrite().