PSPSDK: debug/exception.c File Reference
exception.c File Reference
#include <pspkernel.h>
#include <pspdisplay.h>
#include <pspdebug.h>
Functions
void _pspDebugExceptionHandler (void)
int sceKernelRegisterDefaultExceptionHandler (void *func)
int pspDebugInstallErrorHandler (PspDebugErrorHandler handler)
Install an error handler to catch unhandled exceptions.
void pspDebugDumpException (PspDebugRegBlock *regs)
Dump an exception to screen using the pspDebugScreen functions.
void _pspDebugTrapEntry (void)
The entry point for our exception "trap".
Variables
PspDebugRegBlock _pspDebugExceptRegs
Function Documentation
_pspDebugExceptionHandler()
void _pspDebugExceptionHandler (void)
Referenced by pspDebugInstallErrorHandler().
_pspDebugTrapEntry()
void _pspDebugTrapEntry (void)
The entry point for our exception "trap".
References _pspDebugExceptRegs, NULL, and sceKernelExitDeleteThread().
sceKernelRegisterDefaultExceptionHandler()
int sceKernelRegisterDefaultExceptionHandler (void * func)
Referenced by pspDebugInstallErrorHandler().
Variable Documentation
_pspDebugExceptRegs
PspDebugRegBlock _pspDebugExceptRegs
Referenced by _pspDebugTrapEntry().