PSPSDK: PSPSDK Utility Library
PSPSDK Utility Library
Functions
int pspSdkQueryModuleInfoV1 (SceUID uid, SceKernelModuleInfo *modinfo)
Query a modules information from its uid.
int pspSdkGetModuleIdList (SceUID *readbuf, int readbufsize, int *idcount)
Get the list of module IDs.
int pspSdkInstallNoDeviceCheckPatch (void)
Patch the sceModuleManager module to nullify LoadDeviceCheck() calls.
int pspSdkInstallNoPlainModuleCheckPatch (void)
Patch sceLoadCore module to remove loading plain module checks.
int pspSdkInstallKernelLoadModulePatch (void)
Patch sceLoadModuleWithApiType to remove the kernel check in loadmodule allowing all modules to load.
SceUID pspSdkLoadStartModule (const char *filename, int mpid)
Load a module and start it.
SceUID pspSdkLoadStartModuleWithArgs (const char *filename, int mpid, int argc, char *const argv[])
Load a module and start it with arguments.
void pspSdkFixupImports (int moduleId)
Manually fixup library imports for late binding modules.
int pspSdkLoadInetModules ()
Load Inet related modules.
int pspSdkInetInit ()
Initialize Inet related modules.
void pspSdkInetTerm ()
Terminate Inet related modules.
int pspSdkReferThreadStatusByName (const char *name, SceUID *pUID, SceKernelThreadInfo *pInfo)
Search for a thread with the given name and retrieve it's SceKernelThreadInfo struct.
int pspSdkReferSemaStatusByName (const char *name, SceUID *pUID, SceKernelSemaInfo *pInfo)
Search for a semaphore with the given name and retrieve it's SceKernelSemaInfo struct.
int pspSdkReferEventFlagStatusByName (const char *name, SceUID *pUID, SceKernelEventFlagInfo *pInfo)
Search for an event flag with the given name and retrieve it's SceKernelEventFlagInfo struct.
int pspSdkReferMboxStatusByName (const char *name, SceUID *pUID, SceKernelMbxInfo *pInfo)
Search for a message box with the given name and retrieve it's SceKernelMbxInfo struct.
int pspSdkReferVplStatusByName (const char *name, SceUID *pUID, SceKernelVplInfo *pInfo)
Search for a VPL with the given name and retrieve it's SceKernelVplInfo struct.
int pspSdkReferFplStatusByName (const char *name, SceUID *pUID, SceKernelFplInfo *pInfo)
Search for a FPL with the given name and retrieve it's SceKernelFplInfo struct.
int pspSdkReferMppStatusByName (const char *name, SceUID *pUID, SceKernelMppInfo *pInfo)
Search for a message pipe with the given name and retrieve it's SceKernelMppInfo struct.
int pspSdkReferCallbackStatusByName (const char *name, SceUID *pUID, SceKernelCallbackInfo *pInfo)
Search for a callback with the given name and retrieve it's SceKernelCallbackInfo struct.
int pspSdkReferVTimerStatusByName (const char *name, SceUID *pUID, SceKernelVTimerInfo *pInfo)
Search for a vtimer with the given name and retrieve it's SceKernelVTimerInfo struct.
int pspSdkReferThreadEventHandlerStatusByName (const char *name, SceUID *pUID, SceKernelThreadEventHandlerInfo *pInfo)
Search for a thread event handler with the given name and retrieve it's SceKernelThreadEventHandlerInfo struct.
unsigned int pspSdkDisableInterrupts (void)
Disable interrupts.
void pspSdkEnableInterrupts (unsigned int istate)
Enable interrupts.
unsigned int pspSdkSetK1 (unsigned int k1)
Set the processors K1 register to a known value.
unsigned int pspSdkGetK1 (void)
Get the current value of the processors K1 register.
void pspSdkDisableFPUExceptions (void)
Disable the CPUs FPU exceptions.
SceSize pspSdkTotalFreeUserMemSize (void)
Gets the amount of memory available in the user partition(s).
Detailed Description
Function Documentation
pspSdkDisableFPUExceptions()
void pspSdkDisableFPUExceptions (void)
Disable the CPUs FPU exceptions.
pspSdkDisableInterrupts()
unsigned int pspSdkDisableInterrupts (void)
Disable interrupts.
Note
Do not disable interrupts for too long otherwise the watchdog will get you.
Returns
The previous state of the interrupt enable bit (should be passed back to pspSdkEnableInterrupts)
Referenced by pspSdkTotalFreeUserMemSize().
pspSdkEnableInterrupts()
void pspSdkEnableInterrupts (unsigned int istate)
Enable interrupts.
Parameters
istate - The interrupt state as returned from pspSdkDisableInterrupts
Referenced by pspSdkTotalFreeUserMemSize().
pspSdkFixupImports()
void pspSdkFixupImports (int moduleId)
Manually fixup library imports for late binding modules.
Parameters
moduleId - Id of the module to fixup
References SceLibStubEntry::attr, Kprintf(), module_info, SceLibStubEntry::moduleName, SceLibStubEntry::nidList, NULL, SceLibStubEntry::numFuncs, SceLibStubEntry::numVars, sceKernelDcacheWritebackAll(), sceKernelFindModuleByUID(), sceKernelIcacheClearAll(), _scemoduleinfo::stub_end, _scemoduleinfo::stub_top, and SceLibStubEntry::stubs.
pspSdkGetK1()
unsigned int pspSdkGetK1 (void)
Get the current value of the processors K1 register.
Returns
The current value of K1
pspSdkGetModuleIdList()
int pspSdkGetModuleIdList (SceUID * readbuf, int readbufsize, int * idcount)
Get the list of module IDs.
Note
This is a replacement function for the missing v1.5 sceKernelGetModuleIdList on v1.0 firmware. DO NOT use on anything above that version.
Parameters
readbuf - Buffer to store the module list.
readbufsize - Number of elements in the readbuffer.
idcount - Returns the number of module ids
Returns
>= 0 on success
References sceKernelGetModuleList(), and sceKernelModuleCount().
pspSdkInetInit()
int pspSdkInetInit ()
Initialize Inet related modules.
Returns
- 0 on success, otherwise one of PspKernelErrorCodes.
pspSdkInetTerm()
void pspSdkInetTerm ()
Terminate Inet related modules.
pspSdkInstallKernelLoadModulePatch()
int pspSdkInstallKernelLoadModulePatch (void)
Patch sceLoadModuleWithApiType to remove the kernel check in loadmodule allowing all modules to load.
Note
This function must be called while running in kernel mode
Returns
0 on success
pspSdkInstallNoDeviceCheckPatch()
int pspSdkInstallNoDeviceCheckPatch (void)
Patch the sceModuleManager module to nullify LoadDeviceCheck() calls.
Returns
0 on success, otherwise one of PspKernelErrorCodes.
Note
This function must be called while running in kernel mode. The program must also be linked against the pspkernel library.
pspSdkInstallNoPlainModuleCheckPatch()
int pspSdkInstallNoPlainModuleCheckPatch (void)
Patch sceLoadCore module to remove loading plain module checks.
Note
This function must be called while running in kernel mode.
Returns
0 on success, otherwise one of PspKernelErrorCodes.
pspSdkLoadInetModules()
int pspSdkLoadInetModules ()
Load Inet related modules.
Note
You must be in kernel mode to execute this function.
Returns
- 0 on success, otherwise one of PspKernelErrorCodes.
pspSdkLoadStartModule()
SceUID pspSdkLoadStartModule (const char * filename, int mpid)
Load a module and start it.
Parameters
filename - Path to the module.
mpid - Memory parition ID to use to load the module int.
Returns
- The UID of the module on success, otherwise one of PspKernelErrorCodes.
References NULL, and pspSdkLoadStartModuleWithArgs().
pspSdkLoadStartModuleWithArgs()
SceUID pspSdkLoadStartModuleWithArgs (const char * filename, int mpid, int argc, char *const argv[])
Load a module and start it with arguments.
Parameters
filename - Path to the module.
mpid - Memory parition ID to use to load the module int.
argc - Number of arguments to pass to start module
argv - Array of arguments
Returns
- The UID of the module on success, otherwise one of PspKernelErrorCodes.
References SceKernelLMOption::access, MAX_ARGS, SceKernelLMOption::mpiddata, SceKernelLMOption::mpidtext, NULL, SceKernelLMOption::position, sceKernelLoadModule(), sceKernelStartModule(), and SceKernelLMOption::size.
Referenced by pspSdkLoadStartModule().
pspSdkQueryModuleInfoV1()
int pspSdkQueryModuleInfoV1 (SceUID uid, SceKernelModuleInfo * modinfo)
Query a modules information from its uid.
Note
this is a replacement function for the broken kernel sceKernelQueryModuleInfo in v1.0 firmware DO NOT use on a anything above that version. This also needs kernel mode access where the normal one has a user mode stub.
Parameters
uid - The UID of the module to query.
modinfo - Pointer a module SceKernelModuleInfo structure.
Returns
< 0 on error.
References SceKernelModuleInfo::attribute, SceModule::attribute, SceKernelModuleInfo::bss_size, SceModule::bss_size, SceKernelModuleInfo::data_size, SceModule::data_size, SceKernelModuleInfo::entry_addr, SceModule::entry_addr, SceKernelModuleInfo::gp_value, SceModule::gp_value, SceModule::modname, SceKernelModuleInfo::name, SceKernelModuleInfo::nsegment, SceModule::nsegment, NULL, sceKernelFindModuleByUID(), SceKernelModuleInfo::segmentaddr, SceModule::segmentaddr, SceKernelModuleInfo::segmentsize, SceModule::segmentsize, SceKernelModuleInfo::text_addr, SceModule::text_addr, SceKernelModuleInfo::text_size, SceModule::text_size, SceKernelModuleInfo::version, and SceModule::version.
pspSdkReferCallbackStatusByName()
int pspSdkReferCallbackStatusByName (const char * name, SceUID * pUID, SceKernelCallbackInfo * pInfo)
Search for a callback with the given name and retrieve it's SceKernelCallbackInfo struct.
Parameters
name - The name of to search for.
pUID - If the given name is found, it's SceUID is stored here.
pInfo - If the given name is found, it's SceKernelMppInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Callback, and sceKernelReferCallbackStatus().
pspSdkReferEventFlagStatusByName()
int pspSdkReferEventFlagStatusByName (const char * name, SceUID * pUID, SceKernelEventFlagInfo * pInfo)
Search for an event flag with the given name and retrieve it's SceKernelEventFlagInfo struct.
Parameters
name - The name of the event flag to search for.
pUID - If the event flag with the given name is found, it's SceUID is stored here.
pInfo - If the event flag with the given name is found, it's SceKernelEventFlagInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_EventFlag, and sceKernelReferEventFlagStatus().
pspSdkReferFplStatusByName()
int pspSdkReferFplStatusByName (const char * name, SceUID * pUID, SceKernelFplInfo * pInfo)
Search for a FPL with the given name and retrieve it's SceKernelFplInfo struct.
Parameters
name - The name of to search for.
pUID - If the given name is found, it's SceUID is stored here.
pInfo - If the given name is found, it's SceKernelFplInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Fpl, and sceKernelReferFplStatus().
pspSdkReferMboxStatusByName()
int pspSdkReferMboxStatusByName (const char * name, SceUID * pUID, SceKernelMbxInfo * pInfo)
Search for a message box with the given name and retrieve it's SceKernelMbxInfo struct.
Parameters
name - The name of the message box to search for.
pUID - If the message box with the given name is found, it's SceUID is stored here.
pInfo - If the message box with the given name is found, it's SceKernelMbxInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Mbox, and sceKernelReferMbxStatus().
pspSdkReferMppStatusByName()
int pspSdkReferMppStatusByName (const char * name, SceUID * pUID, SceKernelMppInfo * pInfo)
Search for a message pipe with the given name and retrieve it's SceKernelMppInfo struct.
Parameters
name - The name of to search for.
pUID - If the given name is found, it's SceUID is stored here.
pInfo - If the given name is found, it's SceKernelMppInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Mpipe, and sceKernelReferMsgPipeStatus().
pspSdkReferSemaStatusByName()
int pspSdkReferSemaStatusByName (const char * name, SceUID * pUID, SceKernelSemaInfo * pInfo)
Search for a semaphore with the given name and retrieve it's SceKernelSemaInfo struct.
Parameters
name - The name of the sema to search for.
pUID - If the sema with the given name is found, it's SceUID is stored here.
pInfo - If the sema with the given name is found, it's SceKernelSemaInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Semaphore, and sceKernelReferSemaStatus().
pspSdkReferThreadEventHandlerStatusByName()
int pspSdkReferThreadEventHandlerStatusByName (const char * name, SceUID * pUID, SceKernelThreadEventHandlerInfo * pInfo)
Search for a thread event handler with the given name and retrieve it's SceKernelThreadEventHandlerInfo struct.
Parameters
name - The name of to search for.
pUID - If the given name is found, it's SceUID is stored here.
pInfo - If the given name is found, it's SceKernelThreadEventHandlerInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_ThreadEventHandler, and sceKernelReferThreadEventHandlerStatus().
pspSdkReferThreadStatusByName()
int pspSdkReferThreadStatusByName (const char * name, SceUID * pUID, SceKernelThreadInfo * pInfo)
Search for a thread with the given name and retrieve it's SceKernelThreadInfo struct.
Parameters
name - The name of the thread to search for.
pUID - If the thread with the given name is found, it's SceUID is stored here.
pInfo - If the thread with the given name is found, it's SceKernelThreadInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Thread, and sceKernelReferThreadStatus().
pspSdkReferVplStatusByName()
int pspSdkReferVplStatusByName (const char * name, SceUID * pUID, SceKernelVplInfo * pInfo)
Search for a VPL with the given name and retrieve it's SceKernelVplInfo struct.
Parameters
name - The name of to search for.
pUID - If the given name is found, it's SceUID is stored here.
pInfo - If the given name is found, it's SceKernelVplInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_Vpl, and sceKernelReferVplStatus().
pspSdkReferVTimerStatusByName()
int pspSdkReferVTimerStatusByName (const char * name, SceUID * pUID, SceKernelVTimerInfo * pInfo)
Search for a vtimer with the given name and retrieve it's SceKernelVTimerInfo struct.
Parameters
name - The name of to search for.
pUID - If the given name is found, it's SceUID is stored here.
pInfo - If the given name is found, it's SceKernelVTimerInfo data is stored here.
Returns
0 if successful, otherwise one of PspKernelErrorCodes.
References _ThreadInfoSkel::name, NULL, SCE_KERNEL_TMID_VTimer, and sceKernelReferVTimerStatus().
pspSdkSetK1()
unsigned int pspSdkSetK1 (unsigned int k1)
Set the processors K1 register to a known value.
Note
This function is for use in kernel mode syscall exports. The kernel sets the k1 register to indicate what mode called the function, i.e. whether it was directly called, was called via a syscall from a kernel thread or called via a syscall from a user thread. By setting k1 to 0 before doing anything in your code you can make the other functions think you are calling from a kernel thread and therefore disable numerous protections.
Parameters
k1 - The k1 value to set
Returns
The previous value of k1
pspSdkTotalFreeUserMemSize()
SceSize pspSdkTotalFreeUserMemSize (void)
Gets the amount of memory available in the user partition(s).
Note
This is not to be confused with sceKernelTotalFreeMemSize, which rather contradictorily only returns the amount of memory free in the kernel memory partition.
Returns
The amount of user memory available, in bytes.
References NULL, pspSdkDisableInterrupts(), and pspSdkEnableInterrupts().