PSPSDK: Graphics Utility Library
Graphics Utility Library
Functions
void sceGuDepthBuffer (void *zbp, int zbw)
Set depth buffer parameters.
void sceGuDispBuffer (int width, int height, void *dispbp, int dispbw)
Set display buffer parameters.
void sceGuDrawBuffer (int psm, void *fbp, int fbw)
Set draw buffer parameters (and store in context for buffer-swap)
void sceGuDrawBufferList (int psm, void *fbp, int fbw)
Set draw buffer directly, not storing parameters in the context.
int sceGuDisplay (int state)
Turn display on or off.
void sceGuDepthFunc (int function)
Select which depth-test function to use.
void sceGuDepthMask (int mask)
Mask depth buffer writes.
void sceGuDepthOffset (unsigned int offset)
void sceGuDepthRange (int near, int far)
Set which range to use for depth calculations.
void sceGuFog (float near, float far, unsigned int color)
int sceGuInit (void)
Initalize the GU system.
void sceGuTerm (void)
Shutdown the GU system.
int sceGuBreak (int mode)
Break the display list.
int sceGuContinue (void)
Continue the display list.
void * sceGuSetCallback (int signal, void(*callback)(int))
Setup signal handler.
void sceGuSignal (int mode, int id)
Trigger signal to call code from the command stream.
void sceGuSendCommandf (int cmd, float argument)
Send raw float-command to the GE.
void sceGuSendCommandi (int cmd, int argument)
Send raw command to the GE.
void * sceGuGetMemory (int size)
Allocate memory on the current display list for temporary storage.
int sceGuStart (int ctype, void *list)
Start filling a new display-context.
int sceGuFinish (void)
Finish current display list and go back to the parent context.
int sceGuFinishId (unsigned int id)
Finish current display list and go back to the parent context, sending argument id for the finish callback.
int sceGuCallList (const void *list)
Call previously generated display-list.
void sceGuCallMode (int mode)
Set wether to use stack-based calls or signals to handle execution of called lists.
int sceGuCheckList (void)
Check how large the current display-list is.
int sceGuSendList (int mode, const void *list, PspGeContext *context)
Send a list to the GE directly.
void * sceGuSwapBuffers (void)
Swap display and draw buffer.
int sceGuSync (int mode, int what)
Wait until display list has finished executing.
void sceGuDrawArray (int prim, int vtype, int count, const void *indices, const void *vertices)
Draw array of vertices forming primitives.
void sceGuBeginObject (int vtype, int count, const void *indices, const void *vertices)
Begin conditional rendering of object.
int sceGuEndObject (void)
End conditional rendering of object.
void sceGuSetStatus (int state, int status)
Enable or disable GE state.
int sceGuGetStatus (int state)
Get if state is currently enabled or disabled.
void sceGuSetAllStatus (int status)
Set the status on all 22 available states.
int sceGuGetAllStatus (void)
Query status on all 22 available states.
void sceGuEnable (int state)
Enable GE state.
void sceGuDisable (int state)
Disable GE state.
void sceGuLight (int light, int type, int components, const ScePspFVector3 *position)
Set light parameters.
void sceGuLightAtt (int light, float atten0, float atten1, float atten2)
Set light attenuation.
void sceGuLightColor (int light, int component, unsigned int color)
Set light color.
void sceGuLightMode (int mode)
Set light mode.
void sceGuLightSpot (int light, const ScePspFVector3 *direction, float exponent, float cutoff)
Set spotlight parameters.
void sceGuClear (int flags)
Clear current drawbuffer.
void sceGuClearColor (unsigned int color)
Set the current clear-color.
void sceGuClearDepth (unsigned int depth)
Set the current clear-depth.
void sceGuClearStencil (unsigned int stencil)
Set the current stencil clear value.
void sceGuPixelMask (unsigned int mask)
void sceGuColor (unsigned int color)
Set current primitive color.
void sceGuColorFunc (int func, unsigned int color, unsigned int mask)
Set the color test function.
void sceGuColorMaterial (int components)
Set which color components that the material will receive.
void sceGuAlphaFunc (int func, int value, int mask)
Set the alpha test parameters.
void sceGuAmbient (unsigned int color)
Set the ambient light color.
void sceGuAmbientColor (unsigned int color)
Set the ambient color.
void sceGuBlendFunc (int op, int src, int dest, unsigned int srcfix, unsigned int destfix)
Set the blending-mode.
void sceGuMaterial (int mode, int color)
void sceGuModelColor (unsigned int emissive, unsigned int ambient, unsigned int diffuse, unsigned int specular)
void sceGuStencilFunc (int func, int ref, int mask)
Set stencil function and reference value for stencil testing.
void sceGuStencilOp (int fail, int zfail, int zpass)
Set the stencil test actions.
void sceGuSpecular (float power)
Set the specular power for the material.
void sceGuFrontFace (int order)
Set the current face-order (for culling)
void sceGuLogicalOp (int op)
Set color logical operation.
void sceGuSetDither (const ScePspIMatrix4 *matrix)
Set ordered pixel dither matrix.
void sceGuShadeModel (int mode)
Set how primitives are shaded.
void sceGuCopyImage (int psm, int sx, int sy, int width, int height, int srcw, void *src, int dx, int dy, int destw, void *dest)
Image transfer using the GE.
void sceGuTexEnvColor (unsigned int color)
Specify the texture environment color.
void sceGuTexFilter (int min, int mag)
Set how the texture is filtered.
void sceGuTexFlush (void)
Flush texture page-cache.
void sceGuTexFunc (int tfx, int tcc)
Set how textures are applied.
void sceGuTexImage (int mipmap, int width, int height, int tbw, const void *tbp)
Set current texturemap.
void sceGuTexLevelMode (unsigned int mode, float bias)
Set texture-level mode (mipmapping)
void sceGuTexMapMode (int mode, unsigned int lu, unsigned int lv)
Set the texture-mapping mode.
void sceGuTexMode (int tpsm, int maxmips, int mc, int swizzle)
Set texture-mode parameters.
void sceGuTexOffset (float u, float v)
Set texture offset.
void sceGuTexProjMapMode (int mode)
Set texture projection-map mode.
void sceGuTexScale (float u, float v)
Set texture scale.
void sceGuTexSlope (float slope)
void sceGuTexSync ()
Synchronize rendering pipeline with image upload.
void sceGuTexWrap (int u, int v)
Set if the texture should repeat or clamp.
void sceGuClutLoad (int num_blocks, const void *cbp)
Upload CLUT (Color Lookup Table)
void sceGuClutMode (unsigned int cpsm, unsigned int shift, unsigned int mask, unsigned int csa)
Set current CLUT mode.
void sceGuOffset (unsigned int x, unsigned int y)
Set virtual coordinate offset.
void sceGuScissor (int x, int y, int w, int h)
Set what to scissor within the current viewport.
void sceGuViewport (int cx, int cy, int width, int height)
Set current viewport.
void sceGuDrawBezier (int vtype, int ucount, int vcount, const void *indices, const void *vertices)
Draw bezier surface.
void sceGuPatchDivide (unsigned int ulevel, unsigned int vlevel)
Set dividing for patches (beziers and splines)
void sceGuPatchFrontFace (unsigned int mode)
Set front face for patches (beziers and splines)
void sceGuPatchPrim (int prim)
Set primitive for patches (beziers and splines)
void sceGuDrawSpline (int vtype, int ucount, int vcount, int uedge, int vedge, const void *indices, const void *vertices)
void sceGuSetMatrix (int type, const ScePspFMatrix4 *matrix)
Set transform matrices.
void sceGuBoneMatrix (unsigned int index, const ScePspFMatrix4 *matrix)
Specify skinning matrix entry.
void sceGuMorphWeight (int index, float weight)
Specify morph weight entry.
void sceGuDrawArrayN (int primitive_type, int vertex_type, int vcount, int primcount, const void *indices, const void *vertices)
Draw an array of primitives.
void guSwapBuffersBehaviour (int behaviour)
Set how the display should be set.
void guSwapBuffersCallback (GuSwapBuffersCallback callback)
Set a buffer swap callback to allow for more advanced buffer methods without hacking the library.
void * guGetStaticVramBuffer (unsigned int width, unsigned int height, unsigned int psm)
Allocate a draw buffer in vram.
void * guGetStaticVramTexture (unsigned int width, unsigned int height, unsigned int psm)
Allocate a texture in vram.
int guGetDisplayState ()
Get state of display.
Detailed Description
Function Documentation
guGetDisplayState()
int guGetDisplayState ()
Get state of display.
Available states are:
GU_TRUE (1) - Display is turned on
GU_FALSE (0) - Display is turned off
Returns
State of the display
References gu_display_on.
guGetStaticVramBuffer()
void * guGetStaticVramBuffer (unsigned int width, unsigned int height, unsigned int psm)
Allocate a draw buffer in vram.
Available pixel formats are:
GU_PSM_5650 - Hicolor, 16-bit
GU_PSM_5551 - Hicolor, 16-bit
GU_PSM_4444 - Hicolor, 16-bit
GU_PSM_8888 - Truecolor, 32-bit
Parameters
width - Width of the buffer, usually 512 (must be a power of 2)
height - Height of the buffer, normally the height of the screen 272
psm - Which pixel format to use
Returns
A pointer to the buffer's relative to vram start (as required by sceGuDispBuffer, sceGuDrawBuffer, sceGuDepthBuffer and sceGuDrawBufferList)
References ALIGNMENT.
Referenced by guGetStaticVramTexture().
guGetStaticVramTexture()
void * guGetStaticVramTexture (unsigned int width, unsigned int height, unsigned int psm)
Allocate a texture in vram.
Available texture-formats are:
GU_PSM_5650 - Hicolor, 16-bit
GU_PSM_5551 - Hicolor, 16-bit
GU_PSM_4444 - Hicolor, 16-bit
GU_PSM_8888 - Truecolor, 32-bit
GU_PSM_T4 - Indexed, 4-bit (2 pixels per byte)
GU_PSM_T8 - Indexed, 8-bit
Parameters
width - Width of the texture (must be a power of 2)
height - Height of the texture (must be a power of 2)
psm - Which pixel format to use
Returns
A pointer to the texture
References guGetStaticVramBuffer(), and sceGeEdramGetAddr().
guSwapBuffersBehaviour()
void guSwapBuffersBehaviour (int behaviour)
Set how the display should be set.
Available behaviours are:
PSP_DISPLAY_SETBUF_NEXTHSYNC - Display is swapped on the next hsync
PSP_DISPLAY_SETBUF_NEXTVSYNC - Display is swapped on the next vsync
Do remember that this swaps the pointers internally, regardless of setting, so be careful to wait until the next vertical blank or use another buffering algorithm (see guSwapBuffersCallback()).
References gu_settings, and GuSettings::swapBuffersBehaviour.
guSwapBuffersCallback()
void guSwapBuffersCallback (GuSwapBuffersCallback callback)
Set a buffer swap callback to allow for more advanced buffer methods without hacking the library.
The GuSwapBuffersCallback is defined like this:
void swapBuffersCallback(void** display, void** render);
and on entry they contain the variables that are to be set. To change the pointers that will be used, just write the new pointers. Example of a triple-buffering algorithm:
void* doneBuffer;
void swapBuffersCallback(void** display, void** render)
{
 void* active = doneBuffer;
 doneBuffer = *display;
 *display = active;
}
Parameters
callback - Callback to access when buffers are swapped. Pass 0 to disable.
References gu_settings, and GuSettings::swapBuffersCallback.
sceGuAlphaFunc()
void sceGuAlphaFunc (int func, int value, int mask)
Set the alpha test parameters.
Available comparison functions are:
GU_NEVER
GU_ALWAYS
GU_EQUAL
GU_NOTEQUAL
GU_LESS
GU_LEQUAL
GU_GREATER
GU_GEQUAL
Parameters
func - Specifies the alpha comparison function.
value - Specifies the reference value that incoming alpha values are compared to.
mask - Specifies the mask that both values are ANDed with before comparison.
References ALPHA_TEST, GU_GEQUAL, gu_init, and GU_NEVER.
sceGuAmbient()
void sceGuAmbient (unsigned int color)
Set the ambient light color.
Parameters
color - The light color to set
References AMBIENT_LIGHT_ALPHA, AMBIENT_LIGHT_COLOR, and gu_init.
sceGuAmbientColor()
void sceGuAmbientColor (unsigned int color)
Set the ambient color.
Parameters
color - The color to set
References AMBIENT_ALPHA, AMBIENT_COLOR, and gu_init.
sceGuBeginObject()
void sceGuBeginObject (int vtype, int count, const void * indices, const void * vertices)
Begin conditional rendering of object.
If no vertices passed into this function are inside the scissor region, it will skip rendering the object. There can be up to 32 levels of conditional testing, and all levels HAVE to be terminated by sceGuEndObject().
Example: test a boundingbox against the frustum, and if visible, render object
sceGuBeginObject(GU_VERTEX_32BITF,8,0,boundingBox);
  sceGuDrawArray(GU_TRIANGLES,GU_TEXTURE_32BITF|GU_VERTEX_32BITF,vertexCount,0,vertices);
sceGuEndObject();
Parameters
vtype - Vertex type to process
count - Number of vertices to test
indices - Optional list to an index-list
vertices - Pointer to a vertex-list
References BASE, BJUMP, BOUNDING_BOX, GuDisplayList::current, gu_init, gu_list, gu_object_stack, gu_object_stack_depth, GU_OBJECT_STACK_SIZE, IADDR, VADDR, and VERTEX_TYPE.
sceGuBlendFunc()
void sceGuBlendFunc (int op, int src, int dest, unsigned int srcfix, unsigned int destfix)
Set the blending-mode.
Keys for the blending operations:
Cs - Source color
Cd - Destination color
Bs - Blend function for source fragment
Bd - Blend function for destination fragment
Available blending-operations are:
GU_ADD - (Cs*Bs) + (Cd*Bd)
GU_SUBTRACT - (Cs*Bs) - (Cd*Bd)
GU_REVERSE_SUBTRACT - (Cd*Bd) - (Cs*Bs)
GU_MIN - Cs < Cd ? Cs : Cd
GU_MAX - Cs < Cd ? Cd : Cs
GU_ABS - |Cs-Cd|
Available blending-functions are:
GU_OTHER_COLOR - dstColor if used for source operand; srcColor if used for destination operand
GU_ONE_MINUS_OTHER_COLOR - 1-dstColor if used for source operand; 1-srcColor if used for destination operand
GU_SRC_ALPHA - srcAlpha
GU_ONE_MINUS_SRC_ALPHA - 1-srcAlpha
GU_DST_ALPHA - dstAlpha
GU_ONE_MINUS_DST_ALPHA - 1-dstAlpha
GU_DOUBLE_SRC_ALPHA - 2*srcAlpha
GU_ONE_MINUS_DOUBLE_SRC_ALPHA - 1-2*srcAlpha
GU_DOUBLE_DST_ALPHA - 2*dstAlpha
GU_ONE_MINUS_DOUBLE_DST_ALPHA - 1-2*dstAlpha
GU_FIX - srcFix if used for source operand; dstFix if used for destination operand
Parameters
op - Blending Operation
src - Blending function for source operand
dest - Blending function for dest operand
srcfix - Fix value for GU_FIX (source operand)
destfix - Fix value for GU_FIX (dest operand)
References BLEND_FIXED_A, BLEND_FIXED_B, BLEND_MODE, GU_ABS, GU_ADD, GU_FIX, gu_init, and GU_OTHER_COLOR.
sceGuBoneMatrix()
void sceGuBoneMatrix (unsigned int index, const ScePspFMatrix4 * matrix)
Specify skinning matrix entry.
To enable vertex skinning, pass GU_WEIGHTS(n), where n is between 1-8, and pass available GU_WEIGHT_??? declaration. This will change the amount of weights passed in the vertex araay, and by setting the skinning, matrices, you will multiply each vertex every weight and vertex passed.
Please see sceGuDrawArray() for vertex format information.
Parameters
index - Skinning matrix index (0-7)
matrix - Matrix to set
References BONE_MATRIX_DATA, BONE_MATRIX_NUMBER, and gu_init.
sceGuBreak()
int sceGuBreak (int mode)
Break the display list.
Parameters
mode - Mode to break the display list. Valid modes are:
GU_BREAK_PAUSE - Pause the display list
GU_BREAK_CANCEL - Cancel drawing queue
Returns
0 for success, < 0 for failure
References sceGeBreak().
sceGuCallList()
int sceGuCallList (const void * list)
Call previously generated display-list.
Parameters
list - Display list to call
Returns
0 for success, < 0 for failure
References BASE, CALL, END, gu_call_mode, GU_CALL_SIGNAL, gu_init, and SIGNAL.
sceGuCallMode()
void sceGuCallMode (int mode)
Set wether to use stack-based calls or signals to handle execution of called lists.
Parameters
mode - GU_CALL_SIGNAL(1) to enable signals, GU_CALL_NORMAL(0) to disable signals and use normal calls instead.
References gu_call_mode, GU_CALL_NORMAL, GU_CALL_SIGNAL, and gu_init.
sceGuCheckList()
int sceGuCheckList (void)
Check how large the current display-list is.
Returns
The size of the current display list
References GuDisplayList::current, gu_list, and GuDisplayList::start.
sceGuClear()
void sceGuClear (int flags)
Clear current drawbuffer.
Available clear-flags are (OR them together to get final clear-mode):
GU_COLOR_BUFFER_BIT - Clears the color-buffer
GU_STENCIL_BUFFER_BIT - Clears the stencil-buffer
GU_DEPTH_BUFFER_BIT - Clears the depth-buffer
Parameters
flags - Which part of the buffer to clear
References GuContext::clear_color, GuContext::clear_depth, CLEAR_MODE, GuContext::clear_stencil, GU_COLOR_8888, GU_COLOR_BUFFER_BIT, gu_contexts, gu_curr_context, GU_DEPTH_BUFFER_BIT, gu_draw_buffer, GU_FAST_CLEAR_BIT, gu_init, GU_PSM_4444, GU_PSM_5551, GU_PSM_5650, GU_PSM_8888, GU_SPRITES, GU_STENCIL_BUFFER_BIT, GU_TRANSFORM_2D, GU_VERTEX_16BIT, GuDrawBuffer::height, GuDrawBuffer::pixel_size, sceGuDrawArray(), sceGuGetMemory(), and GuDrawBuffer::width.
sceGuClearColor()
void sceGuClearColor (unsigned int color)
Set the current clear-color.
Parameters
color - Color to clear with
References GuContext::clear_color, gu_contexts, gu_curr_context, and gu_init.
sceGuClearDepth()
void sceGuClearDepth (unsigned int depth)
Set the current clear-depth.
Parameters
depth - Set which depth to clear with (0x0000-0xffff)
References GuContext::clear_depth, gu_contexts, gu_curr_context, and gu_init.
sceGuClearStencil()
void sceGuClearStencil (unsigned int stencil)
Set the current stencil clear value.
Parameters
stencil - Set which stencil value to clear with (0-255)
References GuContext::clear_stencil, gu_contexts, gu_curr_context, gu_draw_buffer, gu_init, GU_PSM_4444, GU_PSM_5551, GU_PSM_5650, GU_PSM_8888, and GuDrawBuffer::pixel_size.
sceGuClutLoad()
void sceGuClutLoad (int num_blocks, const void * cbp)
Upload CLUT (Color Lookup Table)
Note
Data must be aligned to 1 quad word (16 bytes)
Parameters
num_blocks - How many blocks of 8 entries to upload (32*8 is 256 colors)
cbp - Pointer to palette (16 byte aligned)
References CLUT_BUF_PTR, CLUT_BUF_WIDTH, CLUT_LOAD, and gu_init.
sceGuClutMode()
void sceGuClutMode (unsigned int cpsm, unsigned int shift, unsigned int mask, unsigned int csa)
Set current CLUT mode.
Available pixel formats for palettes are:
GU_PSM_5650
GU_PSM_5551
GU_PSM_4444
GU_PSM_8888
Note
Final color index is computed by GE in the following way: ((pixelValue >> shift) & mask) | (csa << 4)
Parameters
cpsm - Which pixel format to use for the palette
shift - Shifts color index by that many bits to the right
mask - Masks the color index with this bitmask after the shift (0-0xFF)
csa - This value is shifted to the left by 4 bits and bitwise ORed with color index after applying mask
References CLUT_FORMAT, gu_init, GU_PSM_5650, and GU_PSM_8888.
sceGuColor()
void sceGuColor (unsigned int color)
Set current primitive color.
Parameters
color - Which color to use (overriden by vertex-colors)
References GU_AMBIENT, GU_DIFFUSE, gu_init, GU_SPECULAR, and sceGuMaterial().
sceGuColorFunc()
void sceGuColorFunc (int func, unsigned int color, unsigned int mask)
Set the color test function.
The color test is only performed while GU_COLOR_TEST is enabled.
Available functions are:
GU_NEVER
GU_ALWAYS
GU_EQUAL
GU_NOTEQUAL
Example: Reject any pixel that does not have 0 as the blue channel
sceGuColorFunc(GU_EQUAL,0,0xff0000);
Parameters
func - Color test function
color - Color to test against
mask - Mask ANDed against both source and destination when testing
References COLOR_REF, COLOR_TEST, COLOR_TESTMASK, gu_init, GU_NEVER, and GU_NOTEQUAL.
sceGuColorMaterial()
void sceGuColorMaterial (int components)
Set which color components that the material will receive.
The components are ORed together from the following values:
GU_AMBIENT
GU_DIFFUSE
GU_SPECULAR
Parameters
components - Which components to receive
References GU_AMBIENT, GU_DIFFUSE, gu_init, GU_SPECULAR, and MATERIAL_COLOR.
Referenced by sceGuStart().
sceGuContinue()
int sceGuContinue (void)
Continue the display list.
Returns
0 for success, < 0 for failure
References gu_init, and sceGeContinue().
sceGuCopyImage()
void sceGuCopyImage (int psm, int sx, int sy, int width, int height, int srcw, void * src, int dx, int dy, int destw, void * dest)
Image transfer using the GE.
Note
Data must be aligned to 1 quad word (16 bytes)
Example: Copy a fullscreen 32-bit image from RAM to VRAM
sceGuCopyImage(GU_PSM_8888,0,0,480,272,512,pixels,0,0,512,(void*)(((unsigned int)framebuffer)+0x4000000));
Parameters
psm - Pixel format for buffer
sx - Source X
sy - Source Y
width - Image width
height - Image height
srcw - Source buffer width (block aligned)
src - Source pointer
dx - Destination X
dy - Destination Y
destw - Destination buffer width (block aligned)
dest - Destination pointer
References gu_init, GU_PSM_5650, GU_PSM_8888, TRANSFER_DST, TRANSFER_DST_OFFSET, TRANSFER_DST_W, TRANSFER_SIZE, TRANSFER_SRC, TRANSFER_SRC_OFFSET, TRANSFER_SRC_W, and TRANSFER_START.
sceGuDepthBuffer()
void sceGuDepthBuffer (void * zbp, int zbw)
Set depth buffer parameters.
Parameters
zbp - VRAM pointer where the depthbuffer should start
zbw - The width of the depth-buffer (block-aligned)
References GuDrawBuffer::depth_buffer, GuDrawBuffer::depth_width, gu_draw_buffer, gu_init, Z_BUF_PTR, and Z_BUF_WIDTH.
sceGuDepthFunc()
void sceGuDepthFunc (int function)
Select which depth-test function to use.
Valid choices for the depth-test are:
GU_NEVER - No pixels pass the depth-test
GU_ALWAYS - All pixels pass the depth-test
GU_EQUAL - Pixels that match the depth-test pass
GU_NOTEQUAL - Pixels that doesn't match the depth-test pass
GU_LESS - Pixels that are less in depth passes
GU_LEQUAL - Pixels that are less or equal in depth passes
GU_GREATER - Pixels that are greater in depth passes
GU_GEQUAL - Pixels that are greater or equal passes
Parameters
function - Depth test function to use
References GU_GEQUAL, gu_init, GU_NEVER, and Z_TEST.
sceGuDepthMask()
void sceGuDepthMask (int mask)
Mask depth buffer writes.
Parameters
mask - GU_TRUE(1) to disable Z writes, GU_FALSE(0) to enable
References gu_init, and Z_MASK.
sceGuDepthOffset()
void sceGuDepthOffset (unsigned int offset)
References GuContext::depth_offset, GuContext::far_plane, gu_contexts, gu_curr_context, gu_init, GuContext::near_plane, and sceGuDepthRange().
sceGuDepthRange()
void sceGuDepthRange (int near, int far)
Set which range to use for depth calculations.
Note
The depth buffer is inversed, and takes values from 65535 to 0.
Example: Use the entire depth-range for calculations:
sceGuDepthRange(65535,0);
Parameters
near - Value to use for the near plane
far - Value to use for the far plane
References GuContext::depth_offset, GuContext::far_plane, gu_contexts, gu_curr_context, gu_init, MAX_Z, MIN_Z, GuContext::near_plane, VIEWPORT_Z_CENTER, and VIEWPORT_Z_SCALE.
Referenced by sceGuDepthOffset().
sceGuDisable()
void sceGuDisable (int state)
Disable GE state.
Look at sceGuEnable() for a list of states
Parameters
state - Which state to disable
References ALPHA_BLEND_ENABLE, ALPHA_TEST_ENABLE, ANTI_ALIAS_ENABLE, COLOR_TEST_ENABLE, CULL_FACE_ENABLE, DEPTH_CLIP_ENABLE, DITHER_ENABLE, FOG_ENABLE, GuContext::fragment_2x, GU_ALPHA_TEST, GU_BLEND, GU_CLIP_PLANES, GU_COLOR_LOGIC_OP, GU_COLOR_TEST, gu_contexts, GU_CULL_FACE, gu_curr_context, GU_DEPTH_TEST, GU_DITHER, gu_draw_buffer, GU_FACE_NORMAL_REVERSE, GU_FOG, GU_FRAGMENT_2X, gu_init, GU_LIGHT0, GU_LIGHT1, GU_LIGHT2, GU_LIGHT3, GU_LIGHTING, GU_LINE_SMOOTH, GU_MAX_STATUS, GU_PATCH_CULL_FACE, GU_PATCH_FACE, GU_SCISSOR_TEST, gu_states, GU_STENCIL_TEST, GU_TEXTURE_2D, GuDrawBuffer::height, LIGHT_ENABLE0, LIGHT_ENABLE1, LIGHT_ENABLE2, LIGHT_ENABLE3, LIGHTING_ENABLE, LOGIC_OP_ENABLE, NORMAL_REVERSE, PATCH_CULL_ENABLE, PATCH_FACING, REGION1, REGION2, SCISSOR1, SCISSOR2, GuContext::scissor_enable, STENCIL_TEST_ENABLE, TEX_FUNC, TEXTURE_ENABLE, GuContext::texture_function, GuDrawBuffer::width, and Z_TEST_ENABLE.
Referenced by sceGuSetAllStatus(), and sceGuSetStatus().
sceGuDispBuffer()
void sceGuDispBuffer (int width, int height, void * dispbp, int dispbw)
Set display buffer parameters.
Example: Setup a standard 16-bit display buffer
sceGuDispBuffer(480,272,(void*)512*272*2,512); // 480*272, skipping the draw buffer located at address 0
Parameters
width - Width of the display buffer in pixels
height - Width of the display buffer in pixels
dispbp - VRAM pointer to where the display-buffer starts
dispbw - Display buffer width (block aligned)
References GuDrawBuffer::disp_buffer, GuDrawBuffer::frame_width, ge_edram_address, GU_DISPLAY_ON, gu_display_on, gu_draw_buffer, gu_init, GuDrawBuffer::height, GuDrawBuffer::pixel_size, PSP_DISPLAY_MODE_LCD, PSP_DISPLAY_SETBUF_NEXTVSYNC, sceDisplaySetFrameBuf(), sceDisplaySetMode(), and GuDrawBuffer::width.
sceGuDisplay()
int sceGuDisplay (int state)
Turn display on or off.
Available states are:
GU_DISPLAY_ON (1) - Turns display on
GU_DISPLAY_OFF (0) - Turns display off
Parameters
state - Turn display on or off
Returns
State of the display prior to this call
References GuDrawBuffer::disp_buffer, GuDrawBuffer::frame_width, ge_edram_address, gu_display_on, gu_draw_buffer, GU_FALSE, gu_init, GU_TRUE, NULL, GuDrawBuffer::pixel_size, PSP_DISPLAY_SETBUF_NEXTVSYNC, and sceDisplaySetFrameBuf().
sceGuDrawArray()
void sceGuDrawArray (int prim, int vtype, int count, const void * indices, const void * vertices)
Draw array of vertices forming primitives.
Available primitive-types are:
GU_POINTS - Single pixel points (1 vertex per primitive)
GU_LINES - Single pixel lines (2 vertices per primitive)
GU_LINE_STRIP - Single pixel line-strip (2 vertices for the first primitive, 1 for every following)
GU_TRIANGLES - Filled triangles (3 vertices per primitive)
GU_TRIANGLE_STRIP - Filled triangles-strip (3 vertices for the first primitive, 1 for every following)
GU_TRIANGLE_FAN - Filled triangle-fan (3 vertices for the first primitive, 1 for every following)
GU_SPRITES - Filled blocks (2 vertices per primitive)
The vertex-type decides how the vertices align and what kind of information they contain.
The following flags are ORed together to compose the final vertex format:
GU_TEXTURE_8BIT - 8-bit texture coordinates
GU_TEXTURE_16BIT - 16-bit texture coordinates
GU_TEXTURE_32BITF - 32-bit texture coordinates (float)
GU_COLOR_5650 - 16-bit color (R5G6B5A0)
GU_COLOR_5551 - 16-bit color (R5G5B5A1)
GU_COLOR_4444 - 16-bit color (R4G4B4A4)
GU_COLOR_8888 - 32-bit color (R8G8B8A8)
GU_NORMAL_8BIT - 8-bit normals
GU_NORMAL_16BIT - 16-bit normals
GU_NORMAL_32BITF - 32-bit normals (float)
GU_VERTEX_8BIT - 8-bit vertex position
GU_VERTEX_16BIT - 16-bit vertex position
GU_VERTEX_32BITF - 32-bit vertex position (float)
GU_WEIGHT_8BIT - 8-bit weights
GU_WEIGHT_16BIT - 16-bit weights
GU_WEIGHT_32BITF - 32-bit weights (float)
GU_INDEX_8BIT - 8-bit vertex index
GU_INDEX_16BIT - 16-bit vertex index
GU_WEIGHTS(n) - Number of weights (1-8)
GU_VERTICES(n) - Number of vertices (1-8)
GU_TRANSFORM_2D - Coordinate is passed directly to the rasterizer
GU_TRANSFORM_3D - Coordinate is transformed before passed to rasterizer
Data members inside a vertex are laid out in the following order:
Weights - if GU_WEIGHTS(n) is used N weights are present
Texture Coordinates
Color
Normal
Position
If GU_VERTICES(n) is used the entire vertex structure is repeated N-times.
A member is only present if related type flag has been used (look at examples below).
Note
Every member making up a vertex must be aligned to 16 bits.
Notes on 16 bit vertex/texture/normal formats:
Values are stored as 16-bit signed integers, with a range of -32768 to 32767
In the floating point coordinate space this is mapped as -1.0 to 1.0
To scale this to be such that the value 1 in 16 bit space is 1 unit in floating point space, use sceGumScale() for vertices; (see pspgum.h)
You can technically use this to create whatever fixed-point space you want (a common one is 5 bits for the decimals)
Caveat: you need to use the sceGumDrawArray method to apply the affine transform to the vertices.
sceGuDrawArray() will not apply the affine transform to the vertices.
To scale this for texture coordinates use sceGuTexOffset() and sceGuTexScale() (see below)
You can't scale the normals with any functions, which is expected since normals by definition are unit vectors.
sceGumScale(32768.0f, 32768.0f, 32768.0f); // This is an identity mapping -- 1 unit in floating point space is 1 unit in 16-bit space
sceGumDrawArray(GU_TRIANGLES, GU_TEXTURE_32BITF|GU_VERTEX_16BIT, 3, 0, vertices);
Notes on 8 bit vertex/texture/normal formats:
Values are stored as 8-bit signed integers with a range of -128 to 127
In the floating point coordinate space this is mapped as -1.0 to 1.0
To scale this to be such that the value 1 in 8 bit space is 1 unit in floating point space, use sceGumScale() for vertices; (see above).
The scaling factor as demonstrated will be 128.0f.
See above for notes on texture and normals.
Example: Render 400 triangles, with floating-point texture coordinates, and floating-point position, no indices
sceGuDrawArray(GU_TRIANGLES,GU_TEXTURE_32BITF|GU_VERTEX_32BITF,400*3,0,vertices);
Parameters
prim - What kind of primitives to render
vtype - Vertex type to process
count - How many vertices to process
indices - Optional pointer to an index-list
vertices - Pointer to a vertex-list
References BASE, gu_init, GU_POINTS, GU_SPRITES, IADDR, PRIM, VADDR, and VERTEX_TYPE.
Referenced by sceGuClear().
sceGuDrawArrayN()
void sceGuDrawArrayN (int primitive_type, int vertex_type, int vcount, int primcount, const void * indices, const void * vertices)
Draw an array of primitives.
Parameters
primitive_type - Type of primitive to draw
vertex_type - Type of vertex to draw
vcount - Number of vertices to draw
primcount - Number of primitives to draw
indices - Pointer to index buffer
vertices - Pointer to vertex buffer
References BASE, gu_init, GU_POINTS, GU_TRIANGLE_FAN, IADDR, PRIM, VADDR, and VERTEX_TYPE.
sceGuDrawBezier()
void sceGuDrawBezier (int vtype, int ucount, int vcount, const void * indices, const void * vertices)
Draw bezier surface.
Parameters
vtype - Vertex type, look at sceGuDrawArray() for vertex definition
ucount - Number of vertices used in the U direction
vcount - Number of vertices used in the V direction
indices - Pointer to index buffer
vertices - Pointer to vertex buffer
References BASE, BEZIER, gu_init, IADDR, VADDR, and VERTEX_TYPE.
sceGuDrawBuffer()
void sceGuDrawBuffer (int psm, void * fbp, int fbw)
Set draw buffer parameters (and store in context for buffer-swap)
Available pixel formats are:
GU_PSM_5650
GU_PSM_5551
GU_PSM_4444
GU_PSM_8888
Example: Setup a standard 16-bit draw buffer
sceGuDrawBuffer(GU_PSM_5551,(void*)0,512);
Parameters
psm - Pixel format to use for rendering (and display)
fbp - VRAM pointer to where the draw buffer starts
fbw - Frame buffer width (block aligned)
References GuDrawBuffer::depth_buffer, GuDrawBuffer::depth_width, FRAME_BUF_PTR, FRAME_BUF_WIDTH, GuDrawBuffer::frame_buffer, GuDrawBuffer::frame_width, FRAMEBUF_PIX_FORMAT, gu_draw_buffer, gu_init, GU_PSM_5650, GU_PSM_8888, GuDrawBuffer::height, GuDrawBuffer::pixel_size, Z_BUF_PTR, and Z_BUF_WIDTH.
sceGuDrawBufferList()
void sceGuDrawBufferList (int psm, void * fbp, int fbw)
Set draw buffer directly, not storing parameters in the context.
Parameters
psm - Pixel format to use for rendering
fbp - VRAM pointer to where the draw buffer starts
fbw - Frame buffer width (block aligned)
References FRAME_BUF_PTR, FRAME_BUF_WIDTH, FRAMEBUF_PIX_FORMAT, gu_init, GU_PSM_5650, and GU_PSM_8888.
sceGuDrawSpline()
void sceGuDrawSpline (int vtype, int ucount, int vcount, int uedge, int vedge, const void * indices, const void * vertices)
References BASE, gu_init, IADDR, SPLINE, VADDR, and VERTEX_TYPE.
sceGuEnable()
void sceGuEnable (int state)
Enable GE state.
The currently available states are:
GU_ALPHA_TEST
GU_DEPTH_TEST
GU_SCISSOR_TEST
GU_BLEND
GU_CULL_FACE
GU_DITHER
GU_CLIP_PLANES
GU_TEXTURE_2D
GU_LIGHTING
GU_LIGHT0
GU_LIGHT1
GU_LIGHT2
GU_LIGHT3
GU_COLOR_LOGIC_OP
Parameters
state - Which state to enable
References ALPHA_BLEND_ENABLE, ALPHA_TEST_ENABLE, ANTI_ALIAS_ENABLE, COLOR_TEST_ENABLE, CULL_FACE_ENABLE, DEPTH_CLIP_ENABLE, DITHER_ENABLE, FOG_ENABLE, GuContext::fragment_2x, GU_ALPHA_TEST, GU_BLEND, GU_CLIP_PLANES, GU_COLOR_LOGIC_OP, GU_COLOR_TEST, gu_contexts, GU_CULL_FACE, gu_curr_context, GU_DEPTH_TEST, GU_DITHER, GU_FACE_NORMAL_REVERSE, GU_FOG, GU_FRAGMENT_2X, gu_init, GU_LIGHT0, GU_LIGHT1, GU_LIGHT2, GU_LIGHT3, GU_LIGHTING, GU_LINE_SMOOTH, GU_MAX_STATUS, GU_PATCH_CULL_FACE, GU_PATCH_FACE, GU_SCISSOR_TEST, gu_states, GU_STENCIL_TEST, GU_TEXTURE_2D, LIGHT_ENABLE0, LIGHT_ENABLE1, LIGHT_ENABLE2, LIGHT_ENABLE3, LIGHTING_ENABLE, LOGIC_OP_ENABLE, NORMAL_REVERSE, PATCH_CULL_ENABLE, PATCH_FACING, REGION1, REGION2, SCISSOR1, SCISSOR2, GuContext::scissor_enable, GuContext::scissor_end, GuContext::scissor_start, STENCIL_TEST_ENABLE, TEX_FUNC, TEXTURE_ENABLE, GuContext::texture_function, and Z_TEST_ENABLE.
Referenced by sceGuSetAllStatus(), and sceGuSetStatus().
sceGuEndObject()
int sceGuEndObject (void)
End conditional rendering of object.
Returns
0 for success, < 0 for failure
References BASE, BJUMP, GuDisplayList::current, ERROR_NOT_FOUND, gu_curr_context, GU_DIRECT, gu_init, gu_list, gu_object_stack, and gu_object_stack_depth.
sceGuFinish()
int sceGuFinish (void)
Finish current display list and go back to the parent context.
If the context is GU_DIRECT, the stall-address is updated so that the entire list will execute. Otherwise, only the terminating action is written to the list, depending on context-type.
The finish-callback will get a zero as argument when using this function.
This also restores control back to whatever context that was active prior to this call.
Returns
Size of finished display list
References sceGuFinishId().
sceGuFinishId()
int sceGuFinishId (unsigned int id)
Finish current display list and go back to the parent context, sending argument id for the finish callback.
If the context is GU_DIRECT, the stall-address is updated so that the entire list will execute. Otherwise, only the terminating action is written to the list, depending on context-type.
Parameters
id - Finish callback id (16-bit)
Returns
Size of finished display list
References GuDisplayList::current, END, FINISH, GU_CALL, gu_call_mode, GU_CALL_SIGNAL, gu_contexts, gu_curr_context, GU_DIRECT, gu_init, gu_list, GU_SEND, GuContext::list, GuDisplayList::parent_context, RET, SCE_DISPLAY_ERROR_ARGUMENT, sceKernelCpuResumeIntr(), sceKernelCpuSuspendIntr(), SIGNAL, and GuDisplayList::start.
Referenced by sceGuFinish().
sceGuFog()
void sceGuFog (float near, float far, unsigned int color)
References FOG1, FOG2, FOG_COLOR, and gu_init.
sceGuFrontFace()
void sceGuFrontFace (int order)
Set the current face-order (for culling)
This only has effect when culling is enabled (GU_CULL_FACE)
Culling order can be:
GU_CW - Clockwise primitives are not culled
GU_CCW - Counter-clockwise are not culled
Parameters
order - Which order to use
References CULL, GU_CCW, GU_CW, and gu_init.
sceGuGetAllStatus()
int sceGuGetAllStatus (void)
Query status on all 22 available states.
Look at sceGuEnable() for a list of states
Returns
Status of all 22 states as a bitmask (0-21)
References gu_states.
sceGuGetMemory()
void * sceGuGetMemory (int size)
Allocate memory on the current display list for temporary storage.
Note
This function is NOT for permanent memory allocation, the memory will be invalid as soon as you start filling the same display list again.
Parameters
size - How much memory to allocate
Returns
Memory-block ready for use
References GuDisplayList::current, ge_list_executed, gu_curr_context, gu_list, and sceGeListUpdateStallAddr().
Referenced by sceGuClear().
sceGuGetStatus()
int sceGuGetStatus (int state)
Get if state is currently enabled or disabled.
Look at sceGuEnable() for a list of states
Parameters
state - Which state to query about
Returns
Wether state is enabled or not
References GU_MAX_STATUS, and gu_states.
sceGuInit()
int sceGuInit (void)
Initalize the GU system.
This function MUST be called as the first function, otherwise state is undetermined.
Returns
0 for success, < 0 for failure
References callbackFin(), callbackSig(), PspGeCallbackData::finish_arg, PspGeCallbackData::finish_func, GuSettings::ge_callback_id, ge_edram_address, ge_list_executed, gu_first_start, gu_init, gu_settings, GuSettings::kernel_event_flag, NULL, PSP_DISPLAY_SETBUF_NEXTHSYNC, PSP_EVENT_WAITMULTIPLE, sceGeDrawSync(), sceGeEdramGetAddr(), sceGeListEnQueue(), sceGeListSync(), sceGeSetCallback(), sceGeUnsetCallback(), sceKernelCreateEventFlag(), sceKernelDeleteEventFlag(), PspGeCallbackData::signal_arg, PspGeCallbackData::signal_func, GuSettings::swapBuffersBehaviour, and GuSettings::swapBuffersCallback.
sceGuLight()
void sceGuLight (int light, int type, int components, const ScePspFVector3 * position)
Set light parameters.
Available light types are:
GU_DIRECTIONAL - Directional light
GU_POINTLIGHT - Single point of light
GU_SPOTLIGHT - Point-light with a cone
Available light components are:
GU_AMBIENT_AND_DIFFUSE
GU_DIFFUSE_AND_SPECULAR
GU_POWERED_DIFFUSE
Parameters
light - Light index
type - Light type
components - Light components
position - Light position
References GU_AMBIENT, GU_AMBIENT_AND_DIFFUSE, GU_DIFFUSE_AND_SPECULAR, GU_DIRECTIONAL, gu_init, GU_POWERED_DIFFUSE, GU_SPOTLIGHT, LIGHT0_X, LIGHT0_Y, LIGHT0_Z, LIGHT_TYPE0, LTYPE_DIFFUSE, LTYPE_DIFFUSE_AND_SPECULAR, LTYPE_POWERED_DIFFUSE, ScePspFVector3::x, ScePspFVector3::y, and ScePspFVector3::z.
sceGuLightAtt()
void sceGuLightAtt (int light, float atten0, float atten1, float atten2)
Set light attenuation.
Parameters
light - Light index
atten0 - Constant attenuation factor
atten1 - Linear attenuation factor
atten2 - Quadratic attenuation factor
References gu_init, LIGHT0_CONSTANT_ATTEN, LIGHT0_LINEAR_ATTEN, and LIGHT0_QUADRATIC_ATTEN.
sceGuLightColor()
void sceGuLightColor (int light, int component, unsigned int color)
Set light color.
Available light components are:
GU_AMBIENT
GU_DIFFUSE
GU_SPECULAR
GU_AMBIENT_AND_DIFFUSE
GU_DIFFUSE_AND_SPECULAR
Parameters
light - Light index
component - Which component to set
color - Which color to use
References GU_AMBIENT, GU_AMBIENT_AND_DIFFUSE, GU_DIFFUSE, GU_DIFFUSE_AND_SPECULAR, gu_init, GU_SPECULAR, LIGHT0_AMBIENT, LIGHT0_DIFFUSE, and LIGHT0_SPECULAR.
sceGuLightMode()
void sceGuLightMode (int mode)
Set light mode.
Available light modes are:
GU_SINGLE_COLOR
GU_SEPARATE_SPECULAR_COLOR
Separate specular colors are used to interpolate the specular component independently, so that it can be added to the fragment after the texture color.
Parameters
mode - Light mode to use
References gu_init, GU_SEPARATE_SPECULAR_COLOR, GU_SINGLE_COLOR, and LIGHT_MODE.
sceGuLightSpot()
void sceGuLightSpot (int light, const ScePspFVector3 * direction, float exponent, float cutoff)
Set spotlight parameters.
Parameters
light - Light index
direction - Spotlight direction
exponent - Spotlight exponent
cutoff - Spotlight cutoff angle (in radians)
References gu_init, LIGHT0_CUTOFF_ATTEN, LIGHT0_DIRECTION_X, LIGHT0_DIRECTION_Y, LIGHT0_DIRECTION_Z, LIGHT0_EXPONENT_ATTEN, ScePspFVector3::x, ScePspFVector3::y, and ScePspFVector3::z.
sceGuLogicalOp()
void sceGuLogicalOp (int op)
Set color logical operation.
Available operations are:
GU_CLEAR
GU_AND
GU_AND_REVERSE
GU_COPY
GU_AND_INVERTED
GU_NOOP
GU_XOR
GU_OR
GU_NOR
GU_EQUIV
GU_INVERTED
GU_OR_REVERSE
GU_COPY_INVERTED
GU_OR_INVERTED
GU_NAND
GU_SET
This operation only has effect if GU_COLOR_LOGIC_OP is enabled.
Note
Unlike OpenGL, GE allows to enable both blending and color logic operations at the same time, in which case color blending will be computed as usual but stored in framebuffer using specified logical operation
Parameters
op - Operation to execute
References GU_CLEAR, gu_init, GU_SET, and LOGIC_OP.
sceGuMaterial()
void sceGuMaterial (int mode, int color)
References AMBIENT_ALPHA, AMBIENT_COLOR, GU_AMBIENT, GU_DIFFUSE, gu_init, GU_SPECULAR, MATERIAL_DIFFUSE, and MATERIAL_SPECULAR.
Referenced by sceGuColor().
sceGuModelColor()
void sceGuModelColor (unsigned int emissive, unsigned int ambient, unsigned int diffuse, unsigned int specular)
References AMBIENT_COLOR, gu_init, MATERIAL_DIFFUSE, MATERIAL_EMISSIVE, and MATERIAL_SPECULAR.
sceGuMorphWeight()
void sceGuMorphWeight (int index, float weight)
Specify morph weight entry.
To enable vertex morphing, pass GU_VERTICES(n), where n is between 1-8. This will change the amount of vertices passed in the vertex array, and by setting the morph weights for every vertex entry in the array, you can blend between them.
Please see sceGuDrawArray() for vertex format information.
Parameters
index - Morph weight index (0-7)
weight - Weight to set
References gu_init, and MORPH_WEIGHT0.
sceGuOffset()
void sceGuOffset (unsigned int x, unsigned int y)
Set virtual coordinate offset.
The PSP has a virtual coordinate-space of 4096x4096, this controls where rendering is performed
Example: Center the virtual coordinate range
sceGuOffset(2048-(480/2),2048-(480/2));
Parameters
x - Offset (0-4095)
y - Offset (0-4095)
References gu_init, OFFSET_X, and OFFSET_Y.
sceGuPatchDivide()
void sceGuPatchDivide (unsigned int ulevel, unsigned int vlevel)
Set dividing for patches (beziers and splines)
Parameters
ulevel - Number of division on u direction
vlevel - Number of division on v direction
References gu_init, and PATCH_DIVISION.
Referenced by sceGuStart().
sceGuPatchFrontFace()
void sceGuPatchFrontFace (unsigned int mode)
Set front face for patches (beziers and splines)
Parameters
mode - Desired front face mode (GU_CW | GU_CCW)
References GU_CCW, GU_CW, gu_init, and PATCH_FACING.
sceGuPatchPrim()
void sceGuPatchPrim (int prim)
Set primitive for patches (beziers and splines)
Parameters
prim - Desired primitive type (GU_POINTS | GU_LINE_STRIP | GU_TRIANGLE_STRIP)
References gu_init, GU_LINE_STRIP, GU_POINTS, GU_TRIANGLE_STRIP, and PATCH_PRIMITIVE.
sceGuPixelMask()
void sceGuPixelMask (unsigned int mask)
References gu_init, MASK_ALPHA, and MASK_COLOR.
sceGuScissor()
void sceGuScissor (int x, int y, int w, int h)
Set what to scissor within the current viewport.
Note that scissoring is only performed if the custom scissoring is enabled (GU_SCISSOR_TEST)
Parameters
x - Left of scissor region
y - Top of scissor region
w - Width of scissor region
h - Height of scissor region
References gu_contexts, gu_curr_context, gu_init, REGION1, REGION2, SCISSOR1, SCISSOR2, GuContext::scissor_enable, GuContext::scissor_end, and GuContext::scissor_start.
sceGuSendCommandf()
void sceGuSendCommandf (int cmd, float argument)
Send raw float-command to the GE.
The argument is converted into a 24-bit float before transfer.
Parameters
cmd - Which command to send
argument - Argument to pass along
References gu_init.
sceGuSendCommandi()
void sceGuSendCommandi (int cmd, int argument)
Send raw command to the GE.
Only the 24 lower bits of the argument is passed along.
Parameters
cmd - Which command to send
argument - Argument to pass along
References gu_init.
sceGuSendList()
int sceGuSendList (int mode, const void * list, PspGeContext * context)
Send a list to the GE directly.
Available modes are:
GU_TAIL - Place list last in the queue, so it executes in-order
GU_HEAD - Place list first in queue so that it executes as soon as possible
Parameters
mode - Whether to place the list first or last in queue
list - List to send
context - Temporary storage for the GE context
Returns
0 for success, < 0 for failure
References PspGeListArgs::context, GuSettings::ge_callback_id, ge_list_executed, GU_HEAD, gu_init, gu_settings, GU_TAIL, NULL, PspGeListArgs::numStacks, sceGeListEnQueue(), sceGeListEnQueueHead(), GuSettings::signal_offset, PspGeListArgs::size, and PspGeListArgs::stacks.
sceGuSetAllStatus()
void sceGuSetAllStatus (int status)
Set the status on all 22 available states.
Look at sceGuEnable() for a list of states
Parameters
status - Bit-mask (0-21) containing the status of all 22 states
References gu_init, GU_MAX_STATUS, sceGuDisable(), and sceGuEnable().
sceGuSetCallback()
void * sceGuSetCallback (int signal, void(* callback)(int))
Setup signal handler.
Available signals are:
GU_CALLBACK_SIGNAL - Called when sceGuSignal is used
GU_CALLBACK_FINISH - Called when display list is finished
Parameters
signal - Signal index to install a handler for
callback - Callback to call when signal index is triggered
Returns
The old callback handler
References GuSettings::fin, GU_CALLBACK_FINISH, GU_CALLBACK_SIGNAL, gu_init, gu_settings, NULL, and GuSettings::sig.
sceGuSetDither()
void sceGuSetDither (const ScePspIMatrix4 * matrix)
Set ordered pixel dither matrix.
This dither matrix is only applied if GU_DITHER is enabled.
Parameters
matrix - Dither matrix
References DITH0, DITH1, DITH2, DITH3, gu_init, ScePspIMatrix4::w, ScePspIVector4::w, ScePspIMatrix4::x, ScePspIVector4::x, ScePspIMatrix4::y, ScePspIVector4::y, ScePspIMatrix4::z, and ScePspIVector4::z.
Referenced by sceGuStart().
sceGuSetMatrix()
void sceGuSetMatrix (int type, const ScePspFMatrix4 * matrix)
Set transform matrices.
Available matrices are:
GU_PROJECTION - View->Projection matrix
GU_VIEW - World->View matrix
GU_MODEL - Model->World matrix
GU_TEXTURE - Texture matrix
Parameters
type - Which matrix-type to set
matrix - Matrix to load
References gu_init, GU_MODEL, GU_PROJECTION, GU_TEXTURE, GU_VIEW, PROJ_MATRIX_DATA, PROJ_MATRIX_NUMBER, TGEN_MATRIX_DATA, TGEN_MATRIX_NUMBER, VIEW_MATRIX_DATA, VIEW_MATRIX_NUMBER, WORLD_MATRIX_DATA, and WORLD_MATRIX_NUMBER.
sceGuSetStatus()
void sceGuSetStatus (int state, int status)
Enable or disable GE state.
Look at sceGuEnable() for a list of states
Parameters
state - Which state to change
status - Wether to enable or disable the state
References gu_init, GU_MAX_STATUS, sceGuDisable(), and sceGuEnable().
sceGuShadeModel()
void sceGuShadeModel (int mode)
Set how primitives are shaded.
The available shading-methods are:
GU_FLAT - Primitives are flatshaded, the last vertex-color takes effet
GU_SMOOTH - Primtives are gouraud-shaded, all vertex-colors take effect
Parameters
mode - Which mode to use
References GU_FLAT, gu_init, GU_SMOOTH, and SHADE_MODE.
sceGuSignal()
void sceGuSignal (int mode, int id)
Trigger signal to call code from the command stream.
Available signal interrupt modes are:
GU_SIGNAL_WAIT - Wait for callback to finish
GU_SIGNAL_NOWAIT - Do not wait for callback to finish
GU_SIGNAL_PAUSE - Pause execution until callback is finished
Parameters
mode - Signal interrupt mode
id - Signal id
References END, FINISH, gu_init, GU_SIGNAL_PAUSE, GU_SIGNAL_WAIT, and SIGNAL.
sceGuSpecular()
void sceGuSpecular (float power)
Set the specular power for the material.
Parameters
power - Specular power
References gu_init, and MATERIAL_SPECULAR_COEF.
Referenced by sceGuStart().
sceGuStart()
int sceGuStart (int ctype, void * list)
Start filling a new display-context.
Contexts available are:
GU_DIRECT - Rendering is performed as list is filled
GU_CALL - List is setup to be called from the main list
GU_SEND - List is buffered for a later call to sceGuSendList()
The previous context-type is stored so that it can be restored at sceGuFinish().
Parameters
ctype - Context Type
list - Pointer to display-list (16 byte aligned)
Returns
0 for success, < 0 for failure
References GuDisplayList::current, FRAME_BUF_PTR, FRAME_BUF_WIDTH, GuDrawBuffer::frame_buffer, GuDrawBuffer::frame_width, GuSettings::ge_callback_id, ge_list_executed, GU_AMBIENT, GU_CALL, gu_contexts, gu_curr_context, GU_DIFFUSE, GU_DIRECT, gu_draw_buffer, gu_first_start, gu_init, gu_list, GU_SEND, gu_settings, GU_SPECULAR, GuContext::list, NULL, GuDisplayList::parent_context, sceGeListEnQueue(), sceGuColorMaterial(), sceGuPatchDivide(), sceGuSetDither(), sceGuSpecular(), sceGuTexScale(), sceKernelCpuResumeIntr(), sceKernelCpuSuspendIntr(), GuSettings::signal_offset, and GuDisplayList::start.
sceGuStencilFunc()
void sceGuStencilFunc (int func, int ref, int mask)
Set stencil function and reference value for stencil testing.
Available functions are:
GU_NEVER
GU_ALWAYS
GU_EQUAL
GU_NOTEQUAL
GU_LESS
GU_LEQUAL
GU_GREATER
GU_GEQUAL
Parameters
func - Test function
ref - The reference value for the stencil test
mask - Mask that is ANDed with both the reference value and stored stencil value when the test is done
References GU_GEQUAL, gu_init, GU_NEVER, and STENCIL_TEST.
sceGuStencilOp()
void sceGuStencilOp (int fail, int zfail, int zpass)
Set the stencil test actions.
Available actions are:
GU_KEEP - Keeps the current value
GU_ZERO - Sets the stencil buffer value to zero
GU_REPLACE - Sets the stencil buffer value to ref, as specified by sceGuStencilFunc()
GU_INCR - Increments the current stencil buffer value
GU_DECR - Decrease the current stencil buffer value
GU_INVERT - Bitwise invert the current stencil buffer value
As stencil buffer shares memory with framebuffer alpha, resolution of the buffer is directly in relation.
Parameters
fail - The action to take when the stencil test fails
zfail - The action to take when stencil test passes, but the depth test fails
zpass - The action to take when both stencil test and depth test passes
References GU_DECR, gu_init, GU_KEEP, and STENCIL_OP.
sceGuSwapBuffers()
void * sceGuSwapBuffers (void)
Swap display and draw buffer.
Returns
Pointer to the new drawbuffer
References GuDrawBuffer::disp_buffer, GuDrawBuffer::frame_buffer, GuDrawBuffer::frame_width, ge_edram_address, gu_display_on, gu_draw_buffer, gu_init, gu_settings, GU_TRUE, GuDrawBuffer::pixel_size, sceDisplaySetFrameBuf(), GuSettings::swapBuffersBehaviour, and GuSettings::swapBuffersCallback.
sceGuSync()
int sceGuSync (int mode, int what)
Wait until display list has finished executing.
Example: Wait for the currently executing display list
sceGuSync(GU_SYNC_FINISH, GU_SYNC_WHAT_DONE);
Available what are:
GU_SYNC_WHAT_DONE
GU_SYNC_WHAT_QUEUED
GU_SYNC_WHAT_DRAW
GU_SYNC_WHAT_STALL
GU_SYNC_WHAT_CANCEL
Available mode are:
GU_SYNC_FINISH - Wait until the last sceGuFinish command is reached
GU_SYNC_SIGNAL - Wait until the last (?) signal is executed
GU_SYNC_DONE - Wait until all commands currently in list are executed
GU_SYNC_LIST - Wait for the currently executed display list (GU_DIRECT)
GU_SYNC_SEND - Wait for the last send list
Parameters
mode - What to wait for
what - What to sync to
Returns
Unknown at this time
References ge_list_executed, gu_init, GU_SYNC_DONE, GU_SYNC_FINISH, GU_SYNC_LIST, GU_SYNC_NOWAIT, GU_SYNC_SEND, GU_SYNC_SIGNAL, GU_SYNC_WAIT, sceGeDrawSync(), and sceGeListSync().
sceGuTerm()
void sceGuTerm (void)
Shutdown the GU system.
Called when GU is no longer needed
References GuSettings::ge_callback_id, gu_init, gu_settings, GuSettings::kernel_event_flag, sceGeUnsetCallback(), and sceKernelDeleteEventFlag().
sceGuTexEnvColor()
void sceGuTexEnvColor (unsigned int color)
Specify the texture environment color.
This is used in the texture function when a constant color is needed.
See sceGuTexFunc() for more information.
Parameters
color - Constant color (0x00BBGGRR)
References gu_init, and TEX_ENV_COLOR.
sceGuTexFilter()
void sceGuTexFilter (int min, int mag)
Set how the texture is filtered.
Available filters are:
GU_NEAREST
GU_LINEAR
GU_NEAREST_MIPMAP_NEAREST
GU_LINEAR_MIPMAP_NEAREST
GU_NEAREST_MIPMAP_LINEAR
GU_LINEAR_MIPMAP_LINEAR
Parameters
min - Minimizing filter
mag - Magnifying filter
References gu_init, GU_LINEAR, GU_LINEAR_MIPMAP_LINEAR, GU_NEAREST, and TEX_FILTER.
sceGuTexFlush()
void sceGuTexFlush (void)
Flush texture page-cache.
Do this if you have copied/rendered into an area currently in the texture-cache
References gu_init, and TEX_FLUSH.
Referenced by sceGuTexImage(), and sceGuTexMode().
sceGuTexFunc()
void sceGuTexFunc (int tfx, int tcc)
Set how textures are applied.
Key for the apply-modes:
Cv - Color value result
Ct - Texture color
Cf - Fragment color
Cc - Constant color (specified by sceGuTexEnvColor())
Available apply-modes are: (TFX)
GU_TFX_MODULATE - Cv=Ct*Cf TCC_RGB: Av=Af TCC_RGBA: Av=At*Af
GU_TFX_DECAL - TCC_RGB: Cv=Ct,Av=Af TCC_RGBA: Cv=Cf*(1-At)+Ct*At Av=Af
GU_TFX_BLEND - Cv=(Cf*(1-Ct))+(Cc*Ct) TCC_RGB: Av=Af TCC_RGBA: Av=At*Af
GU_TFX_REPLACE - Cv=Ct TCC_RGB: Av=Af TCC_RGBA: Av=At
GU_TFX_ADD - Cv=Cf+Ct TCC_RGB: Av=Af TCC_RGBA: Av=At*Af
The fields TCC_RGB and TCC_RGBA specify components that differ between the two different component modes.
GU_TFX_MODULATE - The texture is multiplied with the current diffuse fragment
GU_TFX_REPLACE - The texture replaces the fragment
GU_TFX_ADD - The texture is added on-top of the diffuse fragment
Available component-modes are: (TCC)
GU_TCC_RGB - The texture alpha does not have any effect
GU_TCC_RGBA - The texture alpha is taken into account
Parameters
tfx - Which apply-mode to use
tcc - Which component-mode to use
References GuContext::fragment_2x, gu_contexts, gu_curr_context, gu_init, GU_TCC_RGB, GU_TCC_RGBA, GU_TFX_ADD, GU_TFX_MODULATE, TEX_FUNC, and GuContext::texture_function.
sceGuTexImage()
void sceGuTexImage (int mipmap, int width, int height, int tbw, const void * tbp)
Set current texturemap.
Textures may reside in main RAM, but it has a huge speed-penalty. Swizzle textures to get maximum speed.
Note
Data must be aligned to 1 quad word (16 bytes)
Parameters
mipmap - Mipmap level
width - Width of texture (must be a power of 2)
height - Height of texture (must be a power of 2)
tbw - Texture Buffer Width (block-aligned)
tbp - Texture buffer pointer (16 byte aligned)
References gu_init, sceGuTexFlush(), TEX_ADDR0, TEX_BUF_WIDTH0, and TEX_SIZE0.
sceGuTexLevelMode()
void sceGuTexLevelMode (unsigned int mode, float bias)
Set texture-level mode (mipmapping)
Available modes are:
GU_TEXTURE_AUTO
GU_TEXTURE_CONST
GU_TEXTURE_SLOPE
Parameters
mode - Which mode to use
bias - Which mipmap bias to use
References gu_init, GU_TEXTURE_AUTO, GU_TEXTURE_CONST, GU_TEXTURE_SLOPE, and TEX_LEVEL.
sceGuTexMapMode()
void sceGuTexMapMode (int mode, unsigned int lu, unsigned int lv)
Set the texture-mapping mode.
Available modes are:
GU_TEXTURE_COORDS
GU_TEXTURE_MATRIX
GU_ENVIRONMENT_MAP
Parameters
mode - Which mode to use
lu - Light U
lv - Light V
References gu_contexts, gu_curr_context, GU_ENVIRONMENT_MAP, gu_init, GU_TEXTURE_COORDS, GU_TEXTURE_MATRIX, TEX_MAP_MODE, TEX_SHADE_MAPPING, GuContext::texture_map_mode, and GuContext::texture_proj_map_mode.
sceGuTexMode()
void sceGuTexMode (int tpsm, int maxmips, int mc, int swizzle)
Set texture-mode parameters.
Available texture-formats are:
GU_PSM_5650 - Hicolor, 16-bit
GU_PSM_5551 - Hicolor, 16-bit
GU_PSM_4444 - Hicolor, 16-bit
GU_PSM_8888 - Truecolor, 32-bit
GU_PSM_T4 - Indexed, 4-bit (2 pixels per byte)
GU_PSM_T8 - Indexed, 8-bit
Parameters
tpsm - Which texture format to use
maxmips - Index of the maximum mip level to use (NOT THE NUMBER OF MIPS). Range is 0-7.
mc - Multiclut on/off (0/1)
swizzle - GU_TRUE(1) to swizzle texture-reads
References gu_contexts, gu_curr_context, gu_init, GU_PSM_4444, GU_PSM_5551, GU_PSM_5650, GU_PSM_8888, GU_PSM_T4, GU_PSM_T8, sceGuTexFlush(), TEX_FORMAT, TEX_MODE, and GuContext::texture_mode.
sceGuTexOffset()
void sceGuTexOffset (float u, float v)
Set texture offset.
Note
Only used by the 3D T&L pipe, renders done with GU_TRANSFORM_2D are not affected by this.
Parameters
u - Offset to add to the U coordinate
v - Offset to add to the V coordinate
References gu_init, TEX_OFFSET_U, and TEX_OFFSET_V.
sceGuTexProjMapMode()
void sceGuTexProjMapMode (int mode)
Set texture projection-map mode.
Available modes are:
GU_POSITION
GU_UV
GU_NORMALIZED_NORMAL
GU_NORMAL
Parameters
mode - Which mode to use
References gu_contexts, gu_curr_context, gu_init, GU_NORMAL, GU_NORMALIZED_NORMAL, GU_POSITION, GU_UV, TEX_MAP_MODE, GuContext::texture_map_mode, and GuContext::texture_proj_map_mode.
sceGuTexScale()
void sceGuTexScale (float u, float v)
Set texture scale.
Note
Only used by the 3D T&L pipe, renders ton with GU_TRANSFORM_2D are not affected by this.
Parameters
u - Scalar to multiply U coordinate with
v - Scalar to multiply V coordinate with
References gu_init, TEX_SCALE_U, and TEX_SCALE_V.
Referenced by sceGuStart().
sceGuTexSlope()
void sceGuTexSlope (float slope)
References gu_init, and TEX_LOD_SLOPE.
sceGuTexSync()
void sceGuTexSync ()
Synchronize rendering pipeline with image upload.
This will stall the rendering pipeline until the current image upload initiated by sceGuCopyImage() has completed.
References gu_init, and TEX_SYNC.
sceGuTexWrap()
void sceGuTexWrap (int u, int v)
Set if the texture should repeat or clamp.
Available modes are:
GU_REPEAT - The texture repeats after crossing the border
GU_CLAMP - Texture clamps at the border
Parameters
u - Wrap-mode for the U direction
v - Wrap-mode for the V direction
References GU_CLAMP, gu_init, GU_REPEAT, and TEX_WRAP.
sceGuViewport()
void sceGuViewport (int cx, int cy, int width, int height)
Set current viewport.
Example: Setup a viewport of size (480,272) with origo at (2048,2048)
sceGuViewport(2048,2048,480,272);
Parameters
cx - Center for horizontal viewport
cy - Center for vertical viewport
width - Width of viewport
height - Height of viewport
References gu_init, VIEWPORT_X_CENTER, VIEWPORT_X_SCALE, VIEWPORT_Y_CENTER, and VIEWPORT_Y_SCALE.