PSPSDK: Interface to the LoadCoreForKernel library.
Interface to the LoadCoreForKernel library.
Data Structures
struct SceModule
Describes a loaded module in memory.
struct SceLoadCoreBootModuleInfo
struct SceLibraryEntryTable
Defines a library and its exported functions and variables.
struct SceLibraryStubTable
Specifies a library and a set of imports from that library.
struct SceLoadCoreExecFileInfo
Macros
#define SCE_KERNEL_MAX_MODULE_SEGMENT (4)
Typedefs
typedef s32(* SceKernelRebootBeforeForKernel) (void *arg1, s32 arg2, s32 arg3, s32 arg4)
Reboot preparation functions.
typedef s32(* SceKernelRebootPhaseForKernel) (s32 arg1, void *arg2, s32 arg3, s32 arg4)
typedef struct SceModule SceModule
Describes a loaded module in memory.
typedef struct SceLibraryEntryTable SceLibraryEntryTable
Defines a library and its exported functions and variables.
typedef struct SceLibraryStubTable SceLibraryStubTable
Specifies a library and a set of imports from that library.
typedef struct SceLoadCoreExecFileInfo SceLoadCoreExecFileInfo
Enumerations
enum SceModuleAttribute { SCE_MODULE_ATTR_NONE = 0x0000 , SCE_MODULE_ATTR_CANT_STOP = 0x0001 , SCE_MODULE_ATTR_EXCLUSIVE_LOAD = 0x0002 , SCE_MODULE_ATTR_EXCLUSIVE_START = 0x0004 }
Module type attributes.
enum SceModulePrivilegeLevel {
SCE_MODULE_USER = 0x0000 , SCE_MODULE_MS = 0x0200 , SCE_MODULE_USB_WLAN = 0x0400 , SCE_MODULE_APP = 0x0600 ,
SCE_MODULE_VSH = 0x0800 , SCE_MODULE_KERNEL = 0x1000 , SCE_MODULE_KIRK_MEMLMD_LIB = 0x2000 , SCE_MODULE_KIRK_SEMAPHORE_LIB = 0x4000
}
Module Privilege Levels - These levels define the permissions a module can have.
Functions
SceModule * sceKernelFindModuleByName (const char *modname)
Find a module by it's name.
SceModule * sceKernelFindModuleByAddress (unsigned int addr)
Find a module from an address.
SceModule * sceKernelFindModuleByUID (SceUID modid)
Find a module by it's UID.
int sceKernelModuleCount (void)
Return the count of loaded modules.
void sceKernelIcacheClearAll (void)
Invalidate the CPU's instruction cache.
int sceKernelCheckExecFile (void *buf, SceLoadCoreExecFileInfo *execInfo)
Check an executable file.
int sceKernelProbeExecutableObject (void *buf, SceLoadCoreExecFileInfo *execInfo)
Probe an executable file.
int sceKernelGetModuleIdListForKernel (SceUID *mod_id_list, u32 size, u32 *mod_count, u32 user_mods_only)
Receive a list of UIDs of loaded modules.
int sceKernelCheckPspConfig (void *buf, int size, int flag)
Detailed Description
Macro Definition Documentation
SCE_KERNEL_MAX_MODULE_SEGMENT
#define SCE_KERNEL_MAX_MODULE_SEGMENT (4)
Typedef Documentation
SceKernelRebootBeforeForKernel
typedef s32(* SceKernelRebootBeforeForKernel) (void *arg1, s32 arg2, s32 arg3, s32 arg4)
Reboot preparation functions.
SceKernelRebootPhaseForKernel
typedef s32(* SceKernelRebootPhaseForKernel) (s32 arg1, void *arg2, s32 arg3, s32 arg4)
SceLibraryEntryTable
typedef struct SceLibraryEntryTable SceLibraryEntryTable
Defines a library and its exported functions and variables.
Use the len member to determine the real size of the table (size = len * 4).
SceLibraryStubTable
typedef struct SceLibraryStubTable SceLibraryStubTable
Specifies a library and a set of imports from that library.
Use the len member to determine the real size of the table (size = len * 4).
SceLoadCoreExecFileInfo
typedef struct SceLoadCoreExecFileInfo SceLoadCoreExecFileInfo
SceModule
typedef struct SceModule SceModule
Describes a loaded module in memory.
This structure could change in future firmware revisions.
Enumeration Type Documentation
SceModuleAttribute
enum SceModuleAttribute
Module type attributes.
Enumerator
SCE_MODULE_ATTR_NONE
No module attributes.
SCE_MODULE_ATTR_CANT_STOP
Resident module - stays in memory.
You cannot unload such a module.
SCE_MODULE_ATTR_EXCLUSIVE_LOAD
Only one instance of the module (one version) can be loaded into the system.
If you want to load another version of that module, you have to delete the loaded version first.
SCE_MODULE_ATTR_EXCLUSIVE_START
Only one instance of the module (one version) can be started.
If you want to start another version of that module, you have to stop the currently running version first.
SceModulePrivilegeLevel
enum SceModulePrivilegeLevel
Module Privilege Levels - These levels define the permissions a module can have.
Enumerator
SCE_MODULE_USER
Lowest permission.
SCE_MODULE_MS
POPS/Demo.
SCE_MODULE_USB_WLAN
Module Gamesharing.
SCE_MODULE_APP
Application module.
SCE_MODULE_VSH
VSH module.
SCE_MODULE_KERNEL
Highest permission.
SCE_MODULE_KIRK_MEMLMD_LIB
The module uses KIRK's memlmd resident library.
SCE_MODULE_KIRK_SEMAPHORE_LIB
The module uses KIRK's semaphore resident library.
Function Documentation
sceKernelCheckExecFile()
int sceKernelCheckExecFile (void * buf, SceLoadCoreExecFileInfo * execInfo)
Check an executable file.
This contains scanning its ELF header and ~PSP header (if it has one) and filling the execInfo structure with basic information, like the ELF type, segment information, the size of the executable. The file is also uncompressed, if it was compressed before.
Parameters
buf Pointer to the file's contents.
execInfo Pointer to the executionInfo belonging to that executable.
Returns
0 on success.
sceKernelCheckPspConfig()
int sceKernelCheckPspConfig (void * buf, int size, int flag)
sceKernelFindModuleByAddress()
SceModule * sceKernelFindModuleByAddress (unsigned int addr)
Find a module from an address.
Parameters
addr - Address somewhere within the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
sceKernelFindModuleByName()
SceModule * sceKernelFindModuleByName (const char * modname)
Find a module by it's name.
Parameters
modname - The name of the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
sceKernelFindModuleByUID()
SceModule * sceKernelFindModuleByUID (SceUID modid)
Find a module by it's UID.
Parameters
modid - The UID of the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
Referenced by pspSdkFixupImports(), and pspSdkQueryModuleInfoV1().
sceKernelGetModuleIdListForKernel()
int sceKernelGetModuleIdListForKernel (SceUID * mod_id_list, u32 size, u32 * mod_count, u32 user_mods_only)
Receive a list of UIDs of loaded modules.
Parameters
mod_id_list Pointer to a SceUID array which will receive the UIDs of the loaded modules.
size Size of mod_id_list. Specifies the number of entries that can be stored into mod_id_list.
mod_count A pointer which will receive the total number of loaded modules.
user_mods_only Set to 1 to only receive UIDs from user mode modules. Set to 0 to receive UIDs from all loaded modules.
Returns
0 on success.
sceKernelIcacheClearAll()
void sceKernelIcacheClearAll (void)
Invalidate the CPU's instruction cache.
sceKernelModuleCount()
int sceKernelModuleCount (void)
Return the count of loaded modules.
Returns
The count of loaded modules.
Referenced by pspSdkGetModuleIdList().
sceKernelProbeExecutableObject()
int sceKernelProbeExecutableObject (void * buf, SceLoadCoreExecFileInfo * execInfo)
Probe an executable file.
This contains calculating the sizes for the three segments TEXT, DATA and BSS, filling the execInfo structure with information about the location and sizes of the resident/stub library entry tables.
Furthermore, it is checked whether the executable has valid API type or not.
Parameters
buf Pointer to the file's contents.
execInfo Pointer to the executionInfo belonging to that executable.
Returns
0 on success.