PSPSDK: audio/pspaudiolib.h File Reference
pspaudiolib.h File Reference
Data Structures
struct psp_audio_channelinfo
Macros
#define PSP_NUM_AUDIO_CHANNELS 4
#define PSP_NUM_AUDIO_SAMPLES 1024
This is the number of frames you can update per callback, a frame being 1 sample for mono, 2 samples for stereo etc.
#define PSP_VOLUME_MAX 0x8000
Typedefs
typedef void(* pspAudioCallback_t) (void *buf, unsigned int reqn, void *pdata)
typedef int(* pspAudioThreadfunc_t) (int args, void *argp)
Functions
int pspAudioInit ()
void pspAudioEndPre ()
void pspAudioEnd ()
void pspAudioSetVolume (int channel, int left, int right)
void pspAudioGetVolume (int channel, int *left, int *right)
void pspAudioSetChannelCallback (int channel, pspAudioCallback_t callback, void *pdata)
void pspAudioGetChannelCallback (int channel, pspAudioCallback_t *callback, void **pdata)
int pspAudioOutBlocking (unsigned int channel, unsigned int vol1, unsigned int vol2, void *buf)
Macro Definition Documentation
PSP_NUM_AUDIO_CHANNELS
#define PSP_NUM_AUDIO_CHANNELS 4
Referenced by pspAudioEnd(), pspAudioInit(), and pspAudioOutBlocking().
PSP_NUM_AUDIO_SAMPLES
#define PSP_NUM_AUDIO_SAMPLES 1024
This is the number of frames you can update per callback, a frame being 1 sample for mono, 2 samples for stereo etc.
Referenced by pspAudioInit().
PSP_VOLUME_MAX
#define PSP_VOLUME_MAX 0x8000
Referenced by pspAudioInit(), and pspAudioOutBlocking().
Typedef Documentation
pspAudioCallback_t
typedef void(* pspAudioCallback_t) (void *buf, unsigned int reqn, void *pdata)
pspAudioThreadfunc_t
typedef int(* pspAudioThreadfunc_t) (int args, void *argp)
Function Documentation
pspAudioEnd()
void pspAudioEnd ()
References psp_audio_channelinfo::handle, PSP_NUM_AUDIO_CHANNELS, sceAudioChRelease(), sceKernelDeleteThread(), and psp_audio_channelinfo::threadhandle.
pspAudioEndPre()
void pspAudioEndPre ()
pspAudioGetChannelCallback()
void pspAudioGetChannelCallback (int channel, pspAudioCallback_t * callback, void ** pdata)
References psp_audio_channelinfo::callback, and psp_audio_channelinfo::pdata.
pspAudioGetVolume()
void pspAudioGetVolume (int channel, int * left, int * right)
References psp_audio_channelinfo::volumeleft, and psp_audio_channelinfo::volumeright.
pspAudioInit()
int pspAudioInit ()
References psp_audio_channelinfo::callback, psp_audio_channelinfo::handle, NULL, psp_audio_channelinfo::pdata, PSP_NUM_AUDIO_CHANNELS, PSP_NUM_AUDIO_SAMPLES, PSP_VOLUME_MAX, sceAudioChRelease(), sceAudioChReserve(), sceKernelCreateThread(), sceKernelDeleteThread(), sceKernelStartThread(), psp_audio_channelinfo::threadhandle, psp_audio_channelinfo::volumeleft, and psp_audio_channelinfo::volumeright.
pspAudioOutBlocking()
int pspAudioOutBlocking (unsigned int channel, unsigned int vol1, unsigned int vol2, void * buf)
References PSP_NUM_AUDIO_CHANNELS, PSP_VOLUME_MAX, and sceAudioOutputPannedBlocking().
pspAudioSetChannelCallback()
void pspAudioSetChannelCallback (int channel, pspAudioCallback_t callback, void * pdata)
References psp_audio_channelinfo::callback, and psp_audio_channelinfo::pdata.
pspAudioSetVolume()
void pspAudioSetVolume (int channel, int left, int right)
References psp_audio_channelinfo::volumeleft, and psp_audio_channelinfo::volumeright.