PSPSDK: audio/pspaudiolib.c File Reference
pspaudiolib.c File Reference
#include <stdlib.h>
#include <string.h>
#include <pspthreadman.h>
#include <pspaudio.h>
#include "pspaudiolib.h"
Functions
void pspAudioSetVolume (int channel, int left, int right)
void pspAudioGetVolume (int channel, int *left, int *right)
void pspAudioSetChannelCallback (int channel, pspAudioCallback_t callback, void *pdata)
void pspAudioGetChannelCallback (int channel, pspAudioCallback_t *callback, void **pdata)
int pspAudioOutBlocking (unsigned int channel, unsigned int vol1, unsigned int vol2, void *buf)
int pspAudioInit ()
void pspAudioEndPre ()
void pspAudioEnd ()
Function Documentation
pspAudioEnd()
void pspAudioEnd ()
References psp_audio_channelinfo::handle, PSP_NUM_AUDIO_CHANNELS, sceAudioChRelease(), sceKernelDeleteThread(), and psp_audio_channelinfo::threadhandle.
pspAudioEndPre()
void pspAudioEndPre ()
pspAudioGetChannelCallback()
void pspAudioGetChannelCallback (int channel, pspAudioCallback_t * callback, void ** pdata)
References psp_audio_channelinfo::callback, and psp_audio_channelinfo::pdata.
pspAudioGetVolume()
void pspAudioGetVolume (int channel, int * left, int * right)
References psp_audio_channelinfo::volumeleft, and psp_audio_channelinfo::volumeright.
pspAudioInit()
int pspAudioInit ()
References psp_audio_channelinfo::callback, psp_audio_channelinfo::handle, NULL, psp_audio_channelinfo::pdata, PSP_NUM_AUDIO_CHANNELS, PSP_NUM_AUDIO_SAMPLES, PSP_VOLUME_MAX, sceAudioChRelease(), sceAudioChReserve(), sceKernelCreateThread(), sceKernelDeleteThread(), sceKernelStartThread(), psp_audio_channelinfo::threadhandle, psp_audio_channelinfo::volumeleft, and psp_audio_channelinfo::volumeright.
pspAudioOutBlocking()
int pspAudioOutBlocking (unsigned int channel, unsigned int vol1, unsigned int vol2, void * buf)
References PSP_NUM_AUDIO_CHANNELS, PSP_VOLUME_MAX, and sceAudioOutputPannedBlocking().
pspAudioSetChannelCallback()
void pspAudioSetChannelCallback (int channel, pspAudioCallback_t callback, void * pdata)
References psp_audio_channelinfo::callback, and psp_audio_channelinfo::pdata.
pspAudioSetVolume()
void pspAudioSetVolume (int channel, int left, int right)
References psp_audio_channelinfo::volumeleft, and psp_audio_channelinfo::volumeright.