PSPSDK: debug/pspdebugkb.c File Reference
pspdebugkb.c File Reference
#include <pspdebug.h>
#include <pspctrl.h>
#include <stdio.h>
#include <string.h>
#include "pspdebugkb.h"
Functions
void pspDebugKbShift (int *shiftState)
Switch charTable when SHIFT is pressed.
void pspDebugKbDrawKey (int row, int col, int highlight)
Draw the specified key on the keyboard.
void pspDebugKbClearBox ()
Clear the area where the box resides.
void pspDebugKbDrawBox ()
Draw the entire box on the desbug screen.
void pspDebugKbDrawString (char *str)
Draw the string at the top of the box.
void pspDebugKbInit (char *str)
Make the text box happen.
Variables
char charTable [PSP_DEBUG_KB_NUM_ROWS][PSP_DEBUG_KB_NUM_CHARS]
Function Documentation
pspDebugKbClearBox()
void pspDebugKbClearBox ()
Clear the area where the box resides.
Called from pspDebugKbDrawBox and pspDebugKbInit (on exit).
References PSP_DEBUG_KB_BACK_COLOUR, PSP_DEBUG_KB_BOX_HEIGHT, PSP_DEBUG_KB_BOX_WIDTH, PSP_DEBUG_KB_BOX_X, PSP_DEBUG_KB_BOX_Y, PSP_DEBUG_KB_CHAR_COLOUR, pspDebugScreenPrintf(), pspDebugScreenSetBackColor(), pspDebugScreenSetTextColor(), and pspDebugScreenSetXY().
Referenced by pspDebugKbInit().
pspDebugKbDrawBox()
void pspDebugKbDrawBox ()
Draw the entire box on the desbug screen.
Called from shift() and doInputBox(char*)
References PSP_DEBUG_KB_BACK_COLOUR, PSP_DEBUG_KB_BOX_HEIGHT, PSP_DEBUG_KB_BOX_WIDTH, PSP_DEBUG_KB_BOX_X, PSP_DEBUG_KB_BOX_Y, PSP_DEBUG_KB_CHAR_COLOUR, PSP_DEBUG_KB_COMMAND_ROW, PSP_DEBUG_KB_NUM_CHARS, PSP_DEBUG_KB_NUM_COMMANDS, PSP_DEBUG_KB_NUM_ROWS, pspDebugKbDrawKey(), pspDebugScreenPrintf(), pspDebugScreenSetBackColor(), pspDebugScreenSetTextColor(), and pspDebugScreenSetXY().
Referenced by pspDebugKbInit(), and pspDebugKbShift().
pspDebugKbDrawKey()
void pspDebugKbDrawKey (int row, int col, int highlight)
Draw the specified key on the keyboard.
Parameters
row - The row of the character to print (in charTable)
col - The column of the character to print (in charTable)
highlight - 0 for plain; otherwise highlighted
References charTable, PSP_DEBUG_KB_BACK_COLOUR, PSP_DEBUG_KB_BACK_HIGHLIGHT, PSP_DEBUG_KB_BOX_WIDTH, PSP_DEBUG_KB_BOX_X, PSP_DEBUG_KB_BOX_Y, PSP_DEBUG_KB_CHAR_COLOUR, PSP_DEBUG_KB_CHAR_HIGHLIGHT, PSP_DEBUG_KB_COMMAND_ROW, PSP_DEBUG_KB_NUM_COMMANDS, PSP_DEBUG_KB_OFFSET_X, PSP_DEBUG_KB_SPACING_X, PSP_DEBUG_KB_SPACING_Y, pspDebugScreenPrintf(), pspDebugScreenSetBackColor(), pspDebugScreenSetTextColor(), and pspDebugScreenSetXY().
Referenced by pspDebugKbDrawBox(), and pspDebugKbInit().
pspDebugKbDrawString()
void pspDebugKbDrawString (char * str)
Draw the string at the top of the box.
Parameters
str - The string to print
References PSP_DEBUG_KB_BACK_COLOUR, PSP_DEBUG_KB_BOX_WIDTH, PSP_DEBUG_KB_BOX_X, PSP_DEBUG_KB_BOX_Y, PSP_DEBUG_KB_CHAR_COLOUR, PSP_DEBUG_KB_MAXLEN, pspDebugScreenPrintf(), pspDebugScreenSetBackColor(), pspDebugScreenSetTextColor(), and pspDebugScreenSetXY().
Referenced by pspDebugKbInit().
pspDebugKbInit()
void pspDebugKbInit (char * str)
Make the text box happen.
Parameters
str - The string to edit
References SceCtrlData::Buttons, charTable, PSP_CTRL_CIRCLE, PSP_CTRL_CROSS, PSP_CTRL_DOWN, PSP_CTRL_LEFT, PSP_CTRL_MODE_DIGITAL, PSP_CTRL_RIGHT, PSP_CTRL_SELECT, PSP_CTRL_SQUARE, PSP_CTRL_TRIANGLE, PSP_CTRL_UP, PSP_DEBUG_KB_COMMAND_ROW, PSP_DEBUG_KB_MAXLEN, PSP_DEBUG_KB_NUM_CHARS, PSP_DEBUG_KB_NUM_COMMANDS, pspDebugKbClearBox(), pspDebugKbDrawBox(), pspDebugKbDrawKey(), pspDebugKbDrawString(), pspDebugKbShift(), sceCtrlReadBufferPositive(), sceCtrlSetSamplingCycle(), sceCtrlSetSamplingMode(), and SceCtrlData::TimeStamp.
pspDebugKbShift()
void pspDebugKbShift (int * shiftState)
Switch charTable when SHIFT is pressed.
Parameters
shiftState - Pointer to an int indicating Caps Lock
References charTable, PSP_DEBUG_KB_NUM_CHARS, PSP_DEBUG_KB_NUM_ROWS, and pspDebugKbDrawBox().
Referenced by pspDebugKbInit().
Variable Documentation
charTable
char charTable[PSP_DEBUG_KB_NUM_ROWS][PSP_DEBUG_KB_NUM_CHARS]
Referenced by pspDebugKbDrawKey(), pspDebugKbInit(), and pspDebugKbShift().