PSPSDK: display/pspdisplay.h File Reference
pspdisplay.h File Reference
Macros
#define PSP_DISPLAY_SETBUF_IMMEDIATE PSP_DISPLAY_SETBUF_NEXTHSYNC
Values for retro compatibility.
#define PSP_DISPLAY_SETBUF_NEXTFRAME PSP_DISPLAY_SETBUF_NEXTVSYNC
Enumerations
enum PspDisplayPixelFormats { PSP_DISPLAY_PIXEL_FORMAT_565 = 0 , PSP_DISPLAY_PIXEL_FORMAT_5551 , PSP_DISPLAY_PIXEL_FORMAT_4444 , PSP_DISPLAY_PIXEL_FORMAT_8888 }
Framebuffer pixel formats.
enum PspDisplaySetBufSync { PSP_DISPLAY_SETBUF_NEXTHSYNC = 0 , PSP_DISPLAY_SETBUF_NEXTVSYNC = 1 }
enum PspDisplayMode { PSP_DISPLAY_MODE_LCD = 0 , PSP_DISPLAY_MODE_VESA1A = 0x1A , PSP_DISPLAY_MODE_PSEUDO_VGA = 0x60 }
enum PspDisplayErrorCodes { SCE_DISPLAY_ERROR_OK = 0 , SCE_DISPLAY_ERROR_POINTER = 0x80000103 , SCE_DISPLAY_ERROR_ARGUMENT = 0x80000107 }
Functions
int sceDisplaySetMode (int mode, int width, int height)
Set display mode.
int sceDisplayGetMode (int *pmode, int *pwidth, int *pheight)
Get display mode.
int sceDisplaySetFrameBuf (void *topaddr, int bufferwidth, int pixelformat, int sync)
Display set framebuf.
int sceDisplayGetFrameBuf (void **topaddr, int *bufferwidth, int *pixelformat, int sync)
Get Display Framebuffer information.
unsigned int sceDisplayGetVcount (void)
Number of vertical blank pulses up to now.
int sceDisplayWaitVblankStart (void)
Wait for vertical blank start.
int sceDisplayWaitVblankStartCB (void)
Wait for vertical blank start with callback.
int sceDisplayWaitVblank (void)
Wait for vertical blank.
int sceDisplayWaitVblankCB (void)
Wait for vertical blank with callback.
int sceDisplayGetAccumulatedHcount (void)
Get accumlated HSYNC count.
int sceDisplayGetCurrentHcount (void)
Get current HSYNC count.
float sceDisplayGetFramePerSec (void)
Get number of frames per second.
int sceDisplayIsForeground (void)
Get whether or not frame buffer is being displayed.
int sceDisplayIsVblank (void)
Test whether VBLANK is active.
Macro Definition Documentation
PSP_DISPLAY_SETBUF_IMMEDIATE
#define PSP_DISPLAY_SETBUF_IMMEDIATE PSP_DISPLAY_SETBUF_NEXTHSYNC
Values for retro compatibility.
PSP_DISPLAY_SETBUF_NEXTFRAME
#define PSP_DISPLAY_SETBUF_NEXTFRAME PSP_DISPLAY_SETBUF_NEXTVSYNC
Enumeration Type Documentation
PspDisplayErrorCodes
enum PspDisplayErrorCodes
Enumerator
SCE_DISPLAY_ERROR_OK
SCE_DISPLAY_ERROR_POINTER
SCE_DISPLAY_ERROR_ARGUMENT
PspDisplayMode
enum PspDisplayMode
Enumerator
PSP_DISPLAY_MODE_LCD
LCD MAX 480x272 at 59.94005995 Hz.
PSP_DISPLAY_MODE_VESA1A
VESA VGA MAX 640x480 at 59.94047618Hz.
PSP_DISPLAY_MODE_PSEUDO_VGA
PSEUDO VGA MAX 640x480 at 59.94005995Hz.
PspDisplayPixelFormats
enum PspDisplayPixelFormats
Framebuffer pixel formats.
Enumerator
PSP_DISPLAY_PIXEL_FORMAT_565
16-bit RGB 5:6:5.
PSP_DISPLAY_PIXEL_FORMAT_5551
16-bit RGBA 5:5:5:1.
PSP_DISPLAY_PIXEL_FORMAT_4444
PSP_DISPLAY_PIXEL_FORMAT_8888
PspDisplaySetBufSync
enum PspDisplaySetBufSync
Enumerator
PSP_DISPLAY_SETBUF_NEXTHSYNC
Buffer change effective next hsync.
PSP_DISPLAY_SETBUF_NEXTVSYNC
Buffer change effective next vsync.
Function Documentation
sceDisplayGetAccumulatedHcount()
int sceDisplayGetAccumulatedHcount (void)
Get accumlated HSYNC count.
sceDisplayGetCurrentHcount()
int sceDisplayGetCurrentHcount (void)
Get current HSYNC count.
sceDisplayGetFrameBuf()
int sceDisplayGetFrameBuf (void ** topaddr, int * bufferwidth, int * pixelformat, int sync)
Get Display Framebuffer information.
Parameters
topaddr - pointer to void* to receive address of start of framebuffer
bufferwidth - pointer to int to receive buffer width (must be power of 2)
pixelformat - pointer to int to receive one of PspDisplayPixelFormats.
sync - One of PspDisplaySetBufSync
Returns
0 on success
Referenced by pspScreenshotSave().
sceDisplayGetFramePerSec()
float sceDisplayGetFramePerSec (void)
Get number of frames per second.
sceDisplayGetMode()
int sceDisplayGetMode (int * pmode, int * pwidth, int * pheight)
Get display mode.
Parameters
pmode - Pointer to an integer to receive the current mode.
pwidth - Pointer to an integer to receive the current width.
pheight - Pointer to an integer to receive the current height,
Returns
0 on success
sceDisplayGetVcount()
unsigned int sceDisplayGetVcount (void)
Number of vertical blank pulses up to now.
sceDisplayIsForeground()
int sceDisplayIsForeground (void)
Get whether or not frame buffer is being displayed.
sceDisplayIsVblank()
int sceDisplayIsVblank (void)
Test whether VBLANK is active.
sceDisplaySetFrameBuf()
int sceDisplaySetFrameBuf (void * topaddr, int bufferwidth, int pixelformat, int sync)
Display set framebuf.
Parameters
topaddr - address of start of framebuffer
bufferwidth - buffer width (must be power of 2)
pixelformat - One of PspDisplayPixelFormats.
sync - One of PspDisplaySetBufSync
Returns
0 on success
Referenced by sceGuDispBuffer(), sceGuDisplay(), and sceGuSwapBuffers().
sceDisplaySetMode()
int sceDisplaySetMode (int mode, int width, int height)
Set display mode.
Example1:
int mode = PSP_DISPLAY_MODE_LCD;
int width = 480;
int height = 272;
sceDisplaySetMode(mode, width, height);
Parameters
mode - One of PspDisplayMode
width - Width of screen in pixels.
height - Height of screen in pixels.
Returns
when error, a negative value is returned.
Referenced by sceGuDispBuffer().
sceDisplayWaitVblank()
int sceDisplayWaitVblank (void)
Wait for vertical blank.
sceDisplayWaitVblankCB()
int sceDisplayWaitVblankCB (void)
Wait for vertical blank with callback.
sceDisplayWaitVblankStart()
int sceDisplayWaitVblankStart (void)
Wait for vertical blank start.
Referenced by pspDebugDumpException().
sceDisplayWaitVblankStartCB()
int sceDisplayWaitVblankStartCB (void)
Wait for vertical blank start with callback.