PSPSDK: prof/pspprof.h File Reference
pspprof.h File Reference
Functions
void gprof_start (void)
Start the profiler.
void gprof_stop (const char *filename, int should_dump)
Stop the profiler.
Function Documentation
gprof_start()
void gprof_start (void)
Start the profiler.
If the profiler is already running, this function stop previous one, and ignore the result. Finally, it initializes a new profiler session.
References GMON_PROF_ON, and gp.
gprof_stop()
void gprof_stop (const char * filename, int should_dump)
Stop the profiler.
If the profiler is not running, this function does nothing.
Parameters
filename The name of the file to write the profiling data to.
should_dump If 1, the profiling data will be written to the file. If 0, the profiling data will be discarded.
References fp, GMON_PROF_OFF, GMON_PROF_ON, GMONVERSION, gp, gmonhdr::hpc, gmonhdr::lpc, gmonhdr::ncnt, gmonhdr::profrate, gmonhdr::resv, SAMPLE_FREQ, sceKernelDeleteVTimer(), sceKernelStopVTimer(), and gmonhdr::version.
Referenced by __gprof_cleanup().