var pspusbbus_8h =
[
    [ "UsbInterface", "structUsbInterface.html", "structUsbInterface" ],
    [ "UsbEndpoint", "structUsbEndpoint.html", "structUsbEndpoint" ],
    [ "StringDescriptor", "structStringDescriptor.html", "structStringDescriptor" ],
    [ "DeviceDescriptor", "structDeviceDescriptor.html", "structDeviceDescriptor" ],
    [ "ConfigDescriptor", "structConfigDescriptor.html", "structConfigDescriptor" ],
    [ "InterfaceDescriptor", "structInterfaceDescriptor.html", "structInterfaceDescriptor" ],
    [ "EndpointDescriptor", "structEndpointDescriptor.html", "structEndpointDescriptor" ],
    [ "UsbInterfaces", "structUsbInterfaces.html", "structUsbInterfaces" ],
    [ "UsbConfiguration", "structUsbConfiguration.html", "structUsbConfiguration" ],
    [ "UsbData", "structUsbData.html", "structUsbData" ],
    [ "UsbData::Config", "structUsbData_1_1Config.html", "structUsbData_1_1Config" ],
    [ "UsbData::ConfDesc", "structUsbData_1_1ConfDesc.html", "structUsbData_1_1ConfDesc" ],
    [ "UsbData::Interfaces", "structUsbData_1_1Interfaces.html", "structUsbData_1_1Interfaces" ],
    [ "UsbData::InterDesc", "structUsbData_1_1InterDesc.html", "structUsbData_1_1InterDesc" ],
    [ "UsbData::Endp", "structUsbData_1_1Endp.html", "structUsbData_1_1Endp" ],
    [ "DeviceRequest", "structDeviceRequest.html", "structDeviceRequest" ],
    [ "UsbDriver", "structUsbDriver.html", "structUsbDriver" ],
    [ "UsbdDeviceReq", "structUsbdDeviceReq.html", "structUsbdDeviceReq" ],
    [ "sceUsbbdClearFIFO", "pspusbbus_8h.html#a32da7b4b0c638cb8095681f90456d766", null ],
    [ "sceUsbbdRegister", "pspusbbus_8h.html#af88fb4ce7569677247b54c6eaba479ab", null ],
    [ "sceUsbbdReqCancelAll", "pspusbbus_8h.html#a7a4ab90f4f6aaf9639a9069dfc4cddd4", null ],
    [ "sceUsbbdReqRecv", "pspusbbus_8h.html#a36712839c607f8e4eff8fdb270b71453", null ],
    [ "sceUsbbdReqSend", "pspusbbus_8h.html#a5b72f07f70d94415e6ed30bcd3ddf092", null ],
    [ "sceUsbbdStall", "pspusbbus_8h.html#a6b1859e7c9b78180837048abc2e36e4a", null ],
    [ "sceUsbbdUnregister", "pspusbbus_8h.html#a9f29f68cb27b449561a790bfa2fb9803", null ]
];