PSPSDK: gu/sceGuInit.c File Reference
sceGuInit.c File Reference
#include "guInternal.h"
#include <pspkernel.h>
#include <pspge.h>
#include <pspdisplay.h>
Macros
#define ZV(command)
#define CV(command, value)
Functions
void callbackFin (int id, void *arg)
void callbackSig (int id, void *arg)
int sceGuInit (void)
Initalize the GU system.
Macro Definition Documentation
CV
#define CV (command, value)
Value:
(uint32_t)(command << 24 | value)
ZV
#define ZV (command)
Value:
(uint32_t)(command << 24 | 0x00000000)
Function Documentation
callbackFin()
void callbackFin (int id, void * arg)
References GuSettings::fin.
Referenced by sceGuInit().
callbackSig()
void callbackSig (int id, void * arg)
References GuSettings::kernel_event_flag, sceKernelSetEventFlag(), GuSettings::sig, GuSettings::signal_history, and GuSettings::signal_offset.
Referenced by sceGuInit().