PSPSDK: debug/screenshot.c File Reference
screenshot.c File Reference
#include "pspdebug.h"
#include "pspdisplay.h"
#include "pspuser.h"
Macros
#define PSP_SCREEN_HEIGHT 272
Functions
int bitmapWrite (void *frame_addr, int format, const char *file)
int pspScreenshotSave (const char *filename)
Save a screenshot to a file.
Macro Definition Documentation
PSP_SCREEN_HEIGHT
#define PSP_SCREEN_HEIGHT 272
Function Documentation
bitmapWrite()
int bitmapWrite (void * frame_addr, int format, const char * file)
References BitmapHeader::bitmapsize, BMP_ID, BMP_RGB_BYTES_PER_PIXEL, BitmapHeader::bpp, BitmapHeader::filesize, BitmapHeader::headsize, BitmapHeader::height, BitmapHeader::hres, BitmapHeader::id, BitmapHeader::offset, BitmapHeader::planes, PSP_DISPLAY_PIXEL_FORMAT_4444, PSP_DISPLAY_PIXEL_FORMAT_5551, PSP_DISPLAY_PIXEL_FORMAT_565, PSP_DISPLAY_PIXEL_FORMAT_8888, PSP_O_CREAT, PSP_O_TRUNC, PSP_O_WRONLY, PSP_SCREEN_HEIGHT, PSP_SCREEN_WIDTH, sceIoClose(), sceIoOpen(), BitmapHeader::vres, BitmapHeader::width, write_4444_line(), write_5551_line(), write_565_line(), and write_8888_line().
Referenced by pspScreenshotSave().