var topics =
[
    [ "User Audio Library", "group__Audio.html", "group__Audio" ],
    [ "Controller Kernel Library", "group__Ctrl.html", "group__Ctrl" ],
    [ "Debug Utility Library", "group__Debug.html", "group__Debug" ],
    [ "Graphics Utility Library", "group__GU.html", "group__GU" ],
    [ "Hprm Remote", "group__Hprm.html", "group__Hprm" ],
    [ "Interface to the sceIdStorage_driver library.", "group__IdStorage.html", "group__IdStorage" ],
    [ "Interrupt Manager Kernel", "group__IntrManKern.html", "group__IntrManKern" ],
    [ "Driver interface to IoFileMgr", "group__IoFileMgr__Kernel.html", "group__IoFileMgr__Kernel" ],
    [ "Interface to the KDebugForKernel library.", "group__Kdebug.html", "group__Kdebug" ],
    [ "Interface to the LoadCoreForKernel library.", "group__LoadCore.html", "group__LoadCore" ],
    [ "Interface to the LoadExecForKernel library.", "group__LoadExecKernel.html", "group__LoadExecKernel" ],
    [ "Kernel Module Manager Library", "group__ModuleMgrKern.html", "group__ModuleMgrKern" ],
    [ "Driver interface to Stdio", "group__Stdio__Kernel.html", "group__Stdio__Kernel" ],
    [ "Interface to the sceSyscon_driver library.", "group__Syscon.html", "group__Syscon" ],
    [ "System Memory Manager Kernel", "group__SysMemKern.html", "group__SysMemKern" ],
    [ "Interface to the sceSysreg_driver library.", "group__Sysreg.html", "group__Sysreg" ],
    [ "Thread Manager kernel functions", "group__ThreadmanKern.html", "group__ThreadmanKern" ],
    [ "PSPSDK Utility Library", "group__PSPSDK.html", "group__PSPSDK" ],
    [ "Integrated Remote Control System Library", "group__Sony.html", "group__Sony" ],
    [ "UMD Kernel Library", "group__UMD.html", "group__UMD" ],
    [ "Interrupt Manager", "group__IntrMan.html", "group__IntrMan" ],
    [ "File IO Library", "group__FileIO.html", "group__FileIO" ],
    [ "LoadExec Library", "group__LoadExec.html", "group__LoadExec" ],
    [ "Module Manager Library", "group__ModuleMgr.html", "group__ModuleMgr" ],
    [ "Stdio Library", "group__Stdio.html", "group__Stdio" ],
    [ "System Memory Manager", "group__SysMem.html", "group__SysMem" ],
    [ "Thread Manager Library", "group__ThreadMan.html", "group__ThreadMan" ],
    [ "Utils Library", "group__Utils.html", "group__Utils" ],
    [ "Chnnlsv Library", "group__Chnnlsv.html", "group__Chnnlsv" ],
    [ "Registry Kernel Library", "group__Reg.html", "group__Reg" ]
];