	.set noreorder

#include "pspimport.s"

#ifdef F_sceNet_lib_0000
	IMPORT_START	"sceNet_lib",0x00090000
#endif
#ifdef F_sceNet_lib_0001
	IMPORT_FUNC	"sceNet_lib",0x3B617AA0,sceNet_lib_3B617AA0
#endif
#ifdef F_sceNet_lib_0002
	IMPORT_FUNC	"sceNet_lib",0xDB88F458,sceNet_lib_DB88F458
#endif
#ifdef F_sceNet_lib_0003
	IMPORT_FUNC	"sceNet_lib",0xB6FC0A5B,sceNet_lib_B6FC0A5B
#endif
#ifdef F_sceNet_lib_0004
	IMPORT_FUNC	"sceNet_lib",0xC431A214,sceNet_lib_C431A214
#endif
#ifdef F_sceNet_lib_0005
	IMPORT_FUNC	"sceNet_lib",0xBFCFEFF6,sceNet_lib_BFCFEFF6
#endif
#ifdef F_sceNet_lib_0006
	IMPORT_FUNC	"sceNet_lib",0xE1F4696F,sceNet_lib_E1F4696F
#endif
#ifdef F_sceNet_lib_0007
	IMPORT_FUNC	"sceNet_lib",0x5216CBF5,sceNet_lib_5216CBF5
#endif
#ifdef F_sceNet_lib_0008
	IMPORT_FUNC	"sceNet_lib",0xD2422E4D,sceNet_lib_D2422E4D
#endif
#ifdef F_sceNet_lib_0009
	IMPORT_FUNC	"sceNet_lib",0xD1BE2CE9,sceNet_lib_D1BE2CE9
#endif
#ifdef F_sceNet_lib_0010
	IMPORT_FUNC	"sceNet_lib",0xAB7DD9A5,sceNet_lib_AB7DD9A5
#endif
#ifdef F_sceNet_lib_0011
	IMPORT_FUNC	"sceNet_lib",0x80E1933E,sceNet_lib_80E1933E
#endif
#ifdef F_sceNet_lib_0012
	IMPORT_FUNC	"sceNet_lib",0x7BA3ED91,sceNet_lib_7BA3ED91
#endif
#ifdef F_sceNet_lib_0013
	IMPORT_FUNC	"sceNet_lib",0x03164B12,sceNet_lib_03164B12
#endif
#ifdef F_sceNet_lib_0014
	IMPORT_FUNC	"sceNet_lib",0x389728AB,sceNet_lib_389728AB
#endif
#ifdef F_sceNet_lib_0015
	IMPORT_FUNC	"sceNet_lib",0x4BF9E1DE,sceNet_lib_4BF9E1DE
#endif
#ifdef F_sceNet_lib_0016
	IMPORT_FUNC	"sceNet_lib",0xD5B64E37,sceNet_lib_D5B64E37
#endif
#ifdef F_sceNet_lib_0017
	IMPORT_FUNC	"sceNet_lib",0xDA02F383,sceNet_lib_DA02F383
#endif
#ifdef F_sceNet_lib_0018
	IMPORT_FUNC	"sceNet_lib",0xAFA11338,sceNet_lib_AFA11338
#endif
#ifdef F_sceNet_lib_0019
	IMPORT_FUNC	"sceNet_lib",0xB20F84F8,sceNet_lib_B20F84F8
#endif
#ifdef F_sceNet_lib_0020
	IMPORT_FUNC	"sceNet_lib",0x83FE280A,sceNet_lib_83FE280A
#endif
#ifdef F_sceNet_lib_0021
	IMPORT_FUNC	"sceNet_lib",0x4F8F3808,sceNet_lib_4F8F3808
#endif
#ifdef F_sceNet_lib_0022
	IMPORT_FUNC	"sceNet_lib",0x891723D5,sceNet_lib_891723D5
#endif
#ifdef F_sceNet_lib_0023
	IMPORT_FUNC	"sceNet_lib",0x0DFF67F9,sceNet_lib_0DFF67F9
#endif
#ifdef F_sceNet_lib_0024
	IMPORT_FUNC	"sceNet_lib",0xF355C73B,sceNet_lib_F355C73B
#endif
#ifdef F_sceNet_lib_0025
	IMPORT_FUNC	"sceNet_lib",0xA55C914F,sceNet_lib_A55C914F
#endif
#ifdef F_sceNet_lib_0026
	IMPORT_FUNC	"sceNet_lib",0x0D633F53,sceNet_lib_0D633F53
#endif
#ifdef F_sceNet_lib_0027
	IMPORT_FUNC	"sceNet_lib",0x8D33C11D,sceNetConfigGetEtherAddr
#endif
#ifdef F_sceNet_lib_0028
	IMPORT_FUNC	"sceNet_lib",0x522A971B,sceNet_lib_522A971B
#endif
#ifdef F_sceNet_lib_0029
	IMPORT_FUNC	"sceNet_lib",0x1858883D,sceNetRand
#endif
#ifdef F_sceNet_lib_0030
	IMPORT_FUNC	"sceNet_lib",0x75D9985C,sceNet_lib_75D9985C
#endif
#ifdef F_sceNet_lib_0031
	IMPORT_FUNC	"sceNet_lib",0x25CC373A,sceNet_lib_25CC373A
#endif
#ifdef F_sceNet_lib_0032
	IMPORT_FUNC	"sceNet_lib",0xDCBC596E,sceNet_lib_DCBC596E
#endif
#ifdef F_sceNet_lib_0033
	IMPORT_FUNC	"sceNet_lib",0x7C86FBA4,sceNet_lib_7C86FBA4
#endif
#ifdef F_sceNet_lib_0034
	IMPORT_FUNC	"sceNet_lib",0xA8B6205A,sceNet_lib_A8B6205A
#endif
#ifdef F_sceNet_lib_0035
	IMPORT_FUNC	"sceNet_lib",0xA93A93E9,sceNet_lib_A93A93E9
#endif
#ifdef F_sceNet_lib_0036
	IMPORT_FUNC	"sceNet_lib",0x6B294EE4,sceNet_lib_6B294EE4
#endif
#ifdef F_sceNet_lib_0037
	IMPORT_FUNC	"sceNet_lib",0x51C209B2,sceNet_lib_51C209B2
#endif
#ifdef F_sceNet_lib_0038
	IMPORT_FUNC	"sceNet_lib",0xC9C97945,sceNet_lib_C9C97945
#endif
#ifdef F_sceNet_lib_0039
	IMPORT_FUNC	"sceNet_lib",0xB8C4A858,sceNet_lib_B8C4A858
#endif
#ifdef F_sceNet_lib_0040
	IMPORT_FUNC	"sceNet_lib",0x205E8D17,sceNet_lib_205E8D17
#endif
#ifdef F_sceNet_lib_0041
	IMPORT_FUNC	"sceNet_lib",0xF6DB0A0B,sceNet_lib_F6DB0A0B
#endif
#ifdef F_sceNet_lib_0042
	IMPORT_FUNC	"sceNet_lib",0x7574FDA1,sceNet_lib_7574FDA1
#endif
#ifdef F_sceNet_lib_0043
	IMPORT_FUNC	"sceNet_lib",0xCA3CF5EB,sceNet_lib_CA3CF5EB
#endif
#ifdef F_sceNet_lib_0044
	IMPORT_FUNC	"sceNet_lib",0x757085B0,sceNet_lib_757085B0
#endif
#ifdef F_sceNet_lib_0045
	IMPORT_FUNC	"sceNet_lib",0x435843CB,sceNet_lib_435843CB
#endif
#ifdef F_sceNet_lib_0046
	IMPORT_FUNC	"sceNet_lib",0xD861EF33,sceNet_lib_D861EF33
#endif
#ifdef F_sceNet_lib_0047
	IMPORT_FUNC	"sceNet_lib",0xBB2B3DDB,sceNet_lib_BB2B3DDB
#endif
#ifdef F_sceNet_lib_0048
	IMPORT_FUNC	"sceNet_lib",0x6D5D42D7,sceNet_lib_6D5D42D7
#endif
#ifdef F_sceNet_lib_0049
	IMPORT_FUNC	"sceNet_lib",0xC21E18B2,sceNet_lib_C21E18B2
#endif
#ifdef F_sceNet_lib_0050
	IMPORT_FUNC	"sceNet_lib",0x45452B7B,sceNet_lib_45452B7B
#endif
#ifdef F_sceNet_lib_0051
	IMPORT_FUNC	"sceNet_lib",0x94B44F26,sceNet_lib_94B44F26
#endif
#ifdef F_sceNet_lib_0052
	IMPORT_FUNC	"sceNet_lib",0x515B2F33,sceNet_lib_515B2F33
#endif
#ifdef F_sceNet_lib_0053
	IMPORT_FUNC	"sceNet_lib",0x6DC71518,sceNet_lib_6DC71518
#endif
#ifdef F_sceNet_lib_0054
	IMPORT_FUNC	"sceNet_lib",0x7C3B86C5,sceNet_lib_7C3B86C5
#endif
#ifdef F_sceNet_lib_0055
	IMPORT_FUNC	"sceNet_lib",0x05D525E4,sceNet_lib_05D525E4
#endif
#ifdef F_sceNet_lib_0056
	IMPORT_FUNC	"sceNet_lib",0x1D10419C,sceNet_lib_1D10419C
#endif
#ifdef F_sceNet_lib_0057
	IMPORT_FUNC	"sceNet_lib",0xC2EC2EEA,sceNet_lib_C2EC2EEA
#endif
#ifdef F_sceNet_lib_0058
	IMPORT_FUNC	"sceNet_lib",0x710BD467,sceNet_lib_710BD467
#endif
#ifdef F_sceNet_lib_0059
	IMPORT_FUNC	"sceNet_lib",0x701DDDC3,sceNet_lib_701DDDC3
#endif
#ifdef F_sceNet_lib_0060
	IMPORT_FUNC	"sceNet_lib",0xD5A03BC0,sceNet_lib_D5A03BC0
#endif
#ifdef F_sceNet_lib_0061
	IMPORT_FUNC	"sceNet_lib",0xFA6DE6A6,sceNet_lib_FA6DE6A6
#endif
#ifdef F_sceNet_lib_0062
	IMPORT_FUNC	"sceNet_lib",0xEDB11CB4,sceNet_lib_EDB11CB4
#endif
#ifdef F_sceNet_lib_0063
	IMPORT_FUNC	"sceNet_lib",0x8C55B410,sceNet_lib_8C55B410
#endif
#ifdef F_sceNet_lib_0064
	IMPORT_FUNC	"sceNet_lib",0x13A8B98A,sceNet_lib_13A8B98A
#endif
#ifdef F_sceNet_lib_0065
	IMPORT_FUNC	"sceNet_lib",0xEA42B353,sceNet_lib_EA42B353
#endif
#ifdef F_sceNet_lib_0066
	IMPORT_FUNC	"sceNet_lib",0x45945E8D,sceNet_lib_45945E8D
#endif
#ifdef F_sceNet_lib_0067
	IMPORT_FUNC	"sceNet_lib",0xD60225A3,sceNet_lib_D60225A3
#endif
#ifdef F_sceNet_lib_0068
	IMPORT_FUNC	"sceNet_lib",0xEB6DE71A,sceNet_lib_EB6DE71A
#endif
#ifdef F_sceNet_lib_0069
	IMPORT_FUNC	"sceNet_lib",0xEDCC871E,sceNet_lib_EDCC871E
#endif
#ifdef F_sceNet_lib_0070
	IMPORT_FUNC	"sceNet_lib",0x4B2B3416,sceNet_lib_4B2B3416
#endif
#ifdef F_sceNet_lib_0071
	IMPORT_FUNC	"sceNet_lib",0x2B42872F,sceNet_lib_2B42872F
#endif
#ifdef F_sceNet_lib_0072
	IMPORT_FUNC	"sceNet_lib",0xC4261339,sceNet_lib_C4261339
#endif
#ifdef F_sceNet_lib_0073
	IMPORT_FUNC	"sceNet_lib",0x41FD8B5C,sceNet_lib_41FD8B5C
#endif
#ifdef F_sceNet_lib_0074
	IMPORT_FUNC	"sceNet_lib",0x92633D8D,sceNet_lib_92633D8D
#endif
#ifdef F_sceNet_lib_0075
	IMPORT_FUNC	"sceNet_lib",0xB9C780C7,sceNet_lib_B9C780C7
#endif
#ifdef F_sceNet_lib_0076
	IMPORT_FUNC	"sceNet_lib",0xB68E1EEA,sceNet_lib_B68E1EEA
#endif
#ifdef F_sceNet_lib_0077
	IMPORT_FUNC	"sceNet_lib",0xE155112D,sceNet_lib_E155112D
#endif
#ifdef F_sceNet_lib_0078
	IMPORT_FUNC	"sceNet_lib",0x41621EB0,sceNet_lib_41621EB0
#endif
#ifdef F_sceNet_lib_0079
	IMPORT_FUNC	"sceNet_lib",0x2E005032,sceNet_lib_2E005032
#endif
#ifdef F_sceNet_lib_0080
	IMPORT_FUNC	"sceNet_lib",0x33B230BD,sceNet_lib_33B230BD
#endif
#ifdef F_sceNet_lib_0081
	IMPORT_FUNC	"sceNet_lib",0x976AB1E9,sceNet_lib_976AB1E9
#endif
#ifdef F_sceNet_lib_0082
	IMPORT_FUNC	"sceNet_lib",0x4C8FD452,sceNet_lib_4C8FD452
#endif
#ifdef F_sceNet_lib_0083
	IMPORT_FUNC	"sceNet_lib",0x5ED457BE,sceNet_lib_5ED457BE
#endif
#ifdef F_sceNet_lib_0084
	IMPORT_FUNC	"sceNet_lib",0x31F3CDA1,sceNet_lib_31F3CDA1
#endif
#ifdef F_sceNet_lib_0085
	IMPORT_FUNC	"sceNet_lib",0x1F94AFD9,sceNet_lib_1F94AFD9
#endif
#ifdef F_sceNet_lib_0086
	IMPORT_FUNC	"sceNet_lib",0x0A5A8751,sceNet_lib_0A5A8751
#endif
#ifdef F_sceNet_lib_0087
	IMPORT_FUNC	"sceNet_lib",0xB3A48B7F,sceNet_lib_B3A48B7F
#endif
#ifdef F_sceNet_lib_0088
	IMPORT_FUNC	"sceNet_lib",0x949F1FBB,sceNet_lib_949F1FBB
#endif
#ifdef F_sceNet_lib_0089
	IMPORT_FUNC	"sceNet_lib",0x13672F83,sceNet_lib_13672F83
#endif
#ifdef F_sceNet_lib_0090
	IMPORT_FUNC	"sceNet_lib",0x5C7C7381,sceNet_lib_5C7C7381
#endif
#ifdef F_sceNet_lib_0091
	IMPORT_FUNC	"sceNet_lib",0x86B6DCD9,sceNet_lib_86B6DCD9
#endif
#ifdef F_sceNet_lib_0092
	IMPORT_FUNC	"sceNet_lib",0x7AE91FB4,sceNet_lib_7AE91FB4
#endif
#ifdef F_sceNet_lib_0093
	IMPORT_FUNC	"sceNet_lib",0x572AD6ED,sceNet_lib_572AD6ED
#endif
#ifdef F_sceNet_lib_0094
	IMPORT_FUNC	"sceNet_lib",0x87DC7A7E,sceNet_lib_87DC7A7E
#endif
#ifdef F_sceNet_lib_0095
	IMPORT_FUNC	"sceNet_lib",0x991FF86D,sceNet_lib_991FF86D
#endif
#ifdef F_sceNet_lib_0096
	IMPORT_FUNC	"sceNet_lib",0x5505D820,sceNet_lib_5505D820
#endif
